### ISSUE TITLE
Exception in Shipment Schedule Update Process

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1022]
de.metas.inoutcandidate.async.UpdateInvalidShipmentSchedulesWorkpackageProcessor
creates issue:
```
org.adempiere.exceptions.AdempiereException: NullPointerException
	at org.adempiere.exceptions.AdempiereException.wrapIfNeeded(AdempiereException.java:78)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:835)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:669)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:577)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.run(WorkpackageProcessorTask.java:157)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at Thread.run(Thread.java:745)
Caused by: NullPointerException
	at de.metas.inoutcandidate.spi.impl.OrderLineInOutCandHandler.createCandidatesFor(OrderLineInOutCandHandler.java:146)
	at de.metas.inoutcandidate.api.impl.InOutCandHandlerBL.createMissingCandidates(InOutCandHandlerBL.java:163)
	at de.metas.inoutcandidate.api.impl.ShipmentScheduleUpdater.updateShipmentSchedule(ShipmentScheduleUpdater.java:83)
	at de.metas.inoutcandidate.async.UpdateInvalidShipmentSchedulesWorkpackageProcessor.processWorkPackage(UpdateInvalidShipmentSchedulesWorkpackageProcessor.java:75)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.processWorkpackage(WorkpackageProcessorTask.java:284)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.access$000(WorkpackageProcessorTask.java:84)
	at de.metas.async.processor.impl.WorkpackageProcessorTask$1.run(WorkpackageProcessorTask.java:167)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$1.call(TrxCallableWrappers.java:61)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$1.call(TrxCallableWrappers.java:51)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:757)
	... 8 more

```

## tried:
deleting t_lock and m_shipmentschedule_recompute
update still failing

**Comment by teosarca** [comment]
Hint for a hotfix/workaround: it might be that there is no UOM conversion for that product, from stocking UOM to order line's price UOM.

**Comment by metasnw** [comment]
they are changing UOMs at the moment so that could be quite possibly

**Comment by metasnw** [comment]
any idea how to fix ?

**Comment by teosarca** [comment]
for sure, we would need to throw a proper exception here,
but until then... i think you shall do some selects to check the orderlines, joining the products and checking for which product there is no C_UOM_Conversion from M_Product.C_UOM_ID to C_OrderLine.Price_UOM_ID....

**Comment by metasnw** [comment]
found it with:
```
 select  o.documentno from c_orderline ol
join c_order o on o.c_order_id = ol.c_order_id
left join  m_shipmentschedule ss on ol.c_orderline_id = ss.c_orderline_id
where ss.c_orderline_id  is null and o.docstatus = 'CO' and issotrx = 'Y' order by o.updated desc;
```

the real problem here is as soon as only one single product is missing UOM complete shipment schedule is broken
created this issue to prevent it in future: #1025
