### ISSUE TITLE
ShipmentScheduleBL.updateSchedules fails after C_Order was voided

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1059]
### Is this a bug or feature request?

Bug

### What is the current behavior?

If you void a C_Order that already has shipments, then the shipments are reversed (OK),
but the next time `ShipmentScheduleBL.updateSchedules()` is invoked, it tried to delete the shipment schedules in question. This fails with a message like

```
2017-03-02 14:14:18.067 ERROR 31570 --- [o aktualisieren] org.compiere.util.Trx                    : commitNative: FAILED - TrxRun_446adbb1-b969-46ee-a211-ebc2d922fd83 (throwException=true)

org.postgresql.util.PSQLException: ERROR: update or delete on table "m_shipmentschedule" violates foreign key constraint "mshipmentschedule_mshipmentsch" on table "m_shipmentschedule_qtypicked"
  Detail: Key (m_shipmentschedule_id)=(123) is still referenced from table "m_shipmentschedule_qtypicked".
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2458)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2158)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:291)
        at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:779)
        at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:800)
        at com.mchange.v2.c3p0.impl.NewProxyConnection.commit(NewProxyConnection.java:1007)
        at org.compiere.util.Trx.commitNative(Trx.java:344)
        at org.adempiere.ad.trx.api.impl.AbstractTrx.commit(AbstractTrx.java:253)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:763)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:669)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:570)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:501)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:486)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:480)
        at org.compiere.server.Scheduler.doWork(Scheduler.java:273)
        at org.compiere.server.AdempiereServer.run0(AdempiereServer.java:294)
        at org.compiere.server.AdempiereServer.run(AdempiereServer.java:238)
        at org.compiere.server.Scheduler.run(Scheduler.java:711)
```

*Important:* prior to the failure, there is the follosing warning in the log:
```
org.adempiere.exceptions.AdempiereException: Found QtyPicked record with non-zero qty even if the shipment schedule has QtyDelivered=0
 M_ShipmentSchedule_ID = 123
 QtyPicked = 490
        at de.metas.inoutcandidate.api.impl.ShipmentScheduleBL.updateSchedules(ShipmentScheduleBL.java:316)
        at de.metas.inoutcandidate.api.impl.ShipmentScheduleUpdater.updateShipmentSchedule(ShipmentScheduleUpdater.java:94)
        at de.metas.inoutcandidate.api.impl.ShipmentScheduleUpdater.updateShipmentSchedule(ShipmentScheduleUpdater.java:61)
        at de.metas.inoutcandidate.process.UpdateShipmentScheds.updateNow(UpdateShipmentScheds.java:59)
        at de.metas.inoutcandidate.process.UpdateShipmentScheds.doIt(UpdateShipmentScheds.java:47)
        at de.metas.process.JavaProcess.startProcess(JavaProcess.java:161)
        at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:559)
```

Looking at the code, it turns out that the `m_shipmentschedule_qtypicked` record in question is not deleted.
This code it very old. It probably didn't make a big difference before we had all those FK constraints in place ;-)

#### Which are the steps to reproduce?

Create a sales order and a shipment, then void the sale order

### What is the expected or desired behavior?

The shipment schedule should be deleted

**Comment by metas-dh** [comment]
Results of IT 1

tested on sp80 swing

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%231059.md: OK
