### ISSUE TITLE
Exception cannot be cast to java.math.BigDecimal when importing account elements

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1085]
### Is this a bug or feature request?
bug

### What is the current behavior?
error message appears when you click "Konten importieren" in window Import Elements.

Forum Post:
https://forum.metasfresh.org/t/import-kontendefinition-nicht-moglich/264

Trace:
```
ClassCastException: Integer cannot be cast to java.math.BigDecimal Integer cannot be cast to java.math.BigDecimal

ClassCastException: Integer cannot be cast to java.math.BigDecimal
at org.compiere.process.ImportAccount.prepare(ImportAccount.java:70)
at de.metas.process.JavaProcess.prepareProcess(JavaProcess.java:423)
at de.metas.process.JavaProcess.startProcess(JavaProcess.java:157)
at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:559)
at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:457)
at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:50)
at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:220)
at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:764)
at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:676)
at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:577)
at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:508)
at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:501)
at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:280)
at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:168)
at de.metas.process.ProcessExecutor.lambda$executeAsync$0(ProcessExecutor.java:116)
at Thread.run(Unknown Source)
```

**Comment by teosarca** [comment]
Note, that functionality it's before moon landing.
A complete refactoring is needed.
