### ISSUE TITLE
Process logs are not displayed in Swing

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1179]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
* In Swing client
* Run a process which you know it return process logs
* The process logs will not be displayed
* you will get an exception like following in console:
```
Exception in thread "AWT-EventQueue-0" org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: Bad value for type BigDecimal : ESModelIndexer{id=orders#C_OrderLine, modelTableName=C_OrderLine, denormalizer=ESPOModelDenormalizer{modelTableName=C_OrderLine}} - Indexed: ESIndexerResult{TotalCount=594, FailuresCount=0, Duration=373ms}
	SQL: SELECT Log_ID, P_Date, P_Number, P_Msg FROM AD_PInstance_Log WHERE AD_PInstance_ID=? ORDER BY Log_ID
	SQL params: [1210808]
	at de.metas.process.impl.ADPInstanceDAO.retrieveProcessInfoLogs(ADPInstanceDAO.java:395)
	at de.metas.process.ProcessExecutionResult.getLogsInnerList(ProcessExecutionResult.java:478)
	at de.metas.process.ProcessExecutionResult.getLogInfo(ProcessExecutionResult.java:398)
	at de.metas.process.ProcessExecutionResult.getLogInfo(ProcessExecutionResult.java:464)
	at org.compiere.apps.APanel.updateStatusLine(APanel.java:3232)
	at org.compiere.apps.APanel.unlockUI(APanel.java:3204)
	at de.metas.process.ui.ProcessPanel.unlockUI(ProcessPanel.java:630)
	at de.metas.process.ui.SwingProcessExecutionListener.lambda$1(SwingProcessExecutionListener.java:72)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: org.postgresql.util.PSQLException: Bad value for type BigDecimal : ESModelIndexer{id=orders#C_OrderLine, modelTableName=C_OrderLine, denormalizer=ESPOModelDenormalizer{modelTableName=C_OrderLine}} - Indexed: ESIndexerResult{TotalCount=594, FailuresCount=0, Duration=373ms}
	at org.postgresql.jdbc.PgResultSet.toBigDecimal(PgResultSet.java:2880)
	at org.postgresql.jdbc.PgResultSet.toBigDecimal(PgResultSet.java:2889)
	at org.postgresql.jdbc.PgResultSet.getBigDecimal(PgResultSet.java:2332)
	at org.postgresql.jdbc.PgResultSet.getBigDecimal(PgResultSet.java:400)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.getBigDecimal(NewProxyResultSet.java:1432)
	at de.metas.process.impl.ADPInstanceDAO.retrieveProcessInfoLogs(ADPInstanceDAO.java:386)
	... 21 more
```

### What is the expected or desired behavior?
* log shall be shown to user
* in case the loading the logs fails (precisely this case) don't propagate the exception because it will be lost or it will stop important execution (see Scheduler). Instead, return one log line which shall mention this error.

**Comment by teosarca** [comment]
tested on w101 while running ES_IndexTable. works.
