### ISSUE TITLE
Exception splitting aggregate HU with UOM that has no UOMType

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1282]
### Is this a bug or feature request?
Bug
### What is the current behavior?

When trying to split an aggregate HU whose single storage's UOM has no UOM-Type:
```
Error: The storage of M_HU_ID=25281571 (an aggregate HU) has a null UOM (i.e. contains substorages with incompatible UOMs)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.adempiere.util.Check.mkEx(Check.java:109)
        at org.adempiere.util.Check.throwOrLogEx(Check.java:120)
        at org.adempiere.util.Check.errorIf(Check.java:461)
        at org.adempiere.util.Check.errorIf(Check.java:445)
        at de.metas.handlingunits.allocation.impl.HUListAllocationSourceDestination.storeAggregateItemCuQty(HUListAllocationSourceDestination.java:246)
        at de.metas.handlingunits.allocation.impl.HUListAllocationSourceDestination.lambda$storeAggregateItemCuQty$1(HUListAllocationSourceDestination.java:258)
        at java.util.ArrayList.forEach(Unknown Source)
        at de.metas.handlingunits.allocation.impl.HUListAllocationSourceDestination.storeAggregateItemCuQty(HUListAllocationSourceDestination.java:258)
        at de.metas.handlingunits.allocation.impl.HUListAllocationSourceDestination.lambda$processRequest$0(HUListAllocationSourceDestination.java:185)
        at java.util.ArrayList.forEach(Unknown Source)
        at de.metas.handlingunits.allocation.impl.HUListAllocationSourceDestination.processRequest(HUListAllocationSourceDestination.java:184)
[...]
```

*Workaround:* set some UOMType to the UOM of the HU's storage

**Comment by metas-dh** [comment]
Results of IT1
tested on Swing

* splitting aggregated HUs with UOM that has no UOMType (e.g. Stk, Rolle): checked different splitting (new LU, new TU, VPI etc.): no exception, all worked fine: OK
