### ISSUE TITLE
Jasper not working on a single host with  invalid stream header

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1335]
### Is this a bug or feature request?
bug

### What is the current behavior?
print preview leads to:
`invalid stream header: 3C21444F`

full trace:

```
2017-04-19 06:38:21.350  WARN 18858 --- [Auftragsdruck-1009185] de.metas.process.ProcessExecutor         : Got error

java.lang.RuntimeException: invalid stream header: 3C21444F
	at de.metas.adempiere.report.jasper.client.JRClientUtil.toJasperPrint(JRClientUtil.java:51)
	at org.compiere.report.SwingJRViewerProvider.openViewer_JasperPrint(SwingJRViewerProvider.java:60)
	at org.compiere.report.SwingJRViewerProvider.openViewer(SwingJRViewerProvider.java:48)
	at org.compiere.report.ReportStarter.startProcessPrintPreview(ReportStarter.java:166)
	at org.compiere.report.ReportStarter.startProcess(ReportStarter.java:99)
	at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:557)
	at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:453)
	at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:49)
	at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:219)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:763)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:675)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:576)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:507)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:500)
	at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:279)
	at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:167)
	at de.metas.process.ProcessExecutor.access$1100(ProcessExecutor.java:49)
	at de.metas.process.ProcessExecutor$Builder.executeSync(ProcessExecutor.java:647)
	at org.compiere.print.ReportCtl.startDocumentPrint(ReportCtl.java:292)
	at org.compiere.print.ReportCtl.start(ReportCtl.java:94)
	at org.compiere.print.ReportCtl.access$300(ReportCtl.java:49)
	at org.compiere.print.ReportCtl$Builder.start(ReportCtl.java:391)
	at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:239)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:763)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:675)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:576)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:507)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:500)
	at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:279)
	at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:167)
	at de.metas.process.ProcessExecutor.lambda$executeAsync$0(ProcessExecutor.java:115)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.StreamCorruptedException: invalid stream header: 3C21444F
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:857)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:349)
	at de.metas.adempiere.report.jasper.client.JRClientUtil.toJasperPrint(JRClientUtil.java:45)
	... 35 common frames omitted
```

**Comment by metasnw** [comment]
@metas-jb fixed it by configuring the correct jasper server via sysconfig
