### ISSUE TITLE
npe in purchase order

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#1336]
### Is this a bug or feature request?
bug
### What is the current behavior?
NPE when you set isDropShip in purchase order
#### Which are the steps to reproduce?
1. create a new purchase order and set all mandatory fields
2. select isDropship => NPE (also you cannot add any products)
### What is the expected or desired behavior?
Should work without errors

**Comment by teosarca** [comment]
stacktrace:
```
Caused by: java.lang.NullPointerException: null
	at de.metas.adempiere.service.impl.AddressBuilder.getAD_Org_ID(AddressBuilder.java:64)
	at de.metas.adempiere.service.impl.AddressBuilder.getDisplaySequence(AddressBuilder.java:751)
	at de.metas.adempiere.service.impl.AddressBuilder.buildUserBlock(AddressBuilder.java:645)
	at de.metas.adempiere.service.impl.AddressBuilder.buildBPartnerFullAddressString(AddressBuilder.java:439)
	at org.adempiere.bpartner.service.impl.BPartnerBL.mkFullAddress(BPartnerBL.java:66)
	at de.metas.document.impl.DocumentLocationBL.setDeliveryToAddress(DocumentLocationBL.java:154)
	at de.metas.document.callout.DocumentLocation.deliveryLocationIdForWarehouse(DocumentLocation.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.model.CalloutEngine.lambda$createCalloutMethodExecutor$3(CalloutEngine.java:201)
	at org.compiere.model.CalloutEngine.start(CalloutEngine.java:71)
	... 53 common frames omitted

```

**Comment by teosarca** [comment]
note to IT: the test case is:
* have a purchase order which has a drop ship partner which has C_BPartner.AD_Org_ID=0
* click the dropship flag => error when trying to build the address string
