### ISSUE TITLE
Cannot reverse documents

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1343]
### Is this a bug or feature request?
Bug

### What is the current behavior?
Try reversing a document.
You get following error:
![image](https://cloud.githubusercontent.com/assets/1244701/25182419/2faec93c-251d-11e7-8e1a-3dd2b14b1ece.png)

Stacktrace:
```
Caused by: de.metas.lock.exceptions.UnlockFailedException: Unlocked more than counted
 Current locked count: 1
 Locked to subtract: 2
 Lock: Lock {
	mutex = org.adempiere.util.concurrent.CloseableReentrantLock@52b5b891[Locked by thread Process Cost Collector-1211758]
	lockDatabase = SqlLockDatabase {
	}
	owner = LockOwner(ownerName=DocumentEngine#processIt, ownerType=RealOwner)
	isAutoCleanup = true
	_countLocked = 1
	closed = true
}
	at de.metas.lock.api.impl.Lock.subtractCountLocked(Lock.java:112)
	at de.metas.lock.api.impl.Lock.unlockAll(Lock.java:156)
	at de.metas.lock.api.impl.Lock.close(Lock.java:175)
	at de.metas.lock.api.impl.AbstractLockAutoCloseable.closeNow(AbstractLockAutoCloseable.java:81)
	at de.metas.lock.api.impl.LockAutoCloseable.closeImpl(LockAutoCloseable.java:46)
	at de.metas.lock.api.impl.AbstractLockAutoCloseable.close(AbstractLockAutoCloseable.java:72)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:294)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:261)
	at org.eevolution.model.MPPCostCollector.processIt(MPPCostCollector.java:352)
	at de.metas.document.engine.impl.AbstractDocActionBL.processIt0(AbstractDocActionBL.java:135)
	at de.metas.document.engine.impl.AbstractDocActionBL$1.run(AbstractDocActionBL.java:94)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:1)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:771)
	... 42 common frames omitted
```

**Comment by metas-dh** [comment]
Results of IT1
tested on Swing, mf15 et al.

* reversing of documents working fine (checked e.g. invoice, inout, cost collector), no errors: OK

follow-up: https://github.com/metasfresh/metasfresh/issues/1388
