### ISSUE TITLE
Elastic Search Spamming App Log file in rare cases

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1377]
### Is this a bug or feature request?
bug

### What is the current behavior?
in unkonwn cases the app log file is spammed by 

```
2017-04-25 09:00:58.780  INFO 42 --- [de.metas.async.processor.impl.ThreadPoolQueueProcessor-Elasticsearch model indexer-pool-29-thread-1] d.m.a.p.impl.WorkpackageProcessorTask    : Skipped while processing workpackage by processor de.metas.elasticsearch.scheduler.async.AsyncAddToIndexProcessor; workpackage=X_C_Queue_WorkPackage[C_Queue_WorkPackage_ID=1005190, trxName=null]

de.metas.async.exceptions.WorkpackageSkipRequestException: No indexer found for modelIndexerId=orders#C_OrderLine
        at de.metas.async.exceptions.WorkpackageSkipRequestException.createWithTimeoutAndThrowable(WorkpackageSkipRequestException.java:67)
        at de.metas.elasticsearch.scheduler.async.AsyncAddToIndexProcessor.processWorkPackage(AsyncAddToIndexProcessor.java:70)
        at de.metas.async.processor.impl.WorkpackageProcessorTask.processWorkpackage(WorkpackageProcessorTask.java:284)
        at de.metas.async.processor.impl.WorkpackageProcessorTask.access$000(WorkpackageProcessorTask.java:84)
        at de.metas.async.processor.impl.WorkpackageProcessorTask$1.run(WorkpackageProcessorTask.java:167)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:103)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:93)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:771)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:683)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:591)
        at de.metas.async.processor.impl.WorkpackageProcessorTask.run(WorkpackageProcessorTask.java:157)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: No indexer found for modelIndexerId=orders#C_OrderLine
        at de.metas.elasticsearch.indexer.impl.ESModelIndexersRegistry.getModelIndexerById(ESModelIndexersRegistry.java:90)
        at de.metas.elasticsearch.scheduler.async.AsyncAddToIndexProcessor.processWorkPackage(AsyncAddToIndexProcessor.java:58)
        ... 14 common frames omitted
```

#### Which are the steps to reproduce?
not known

**Comment by metasnw** [comment]
might be related to: #1205 
idea: migration script part is missing which needs to be applied to old databases
