### ISSUE TITLE
FRESH-484 Error creating manual DD_Order

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#147]
got an error when i created a manual distribution order:

```
2016-07-05 14:13:27.028 ERROR 31043 --- [WT-EventQueue-0] org.compiere.model.CalloutInOut          : start: docType

org.adempiere.exceptions.AdempiereException: Interface interface org.compiere.model.I_M_InOut (tableName=M_InOut) is not compatible with GridTab{TabNo=0, Name=Distribution Order, AD_Tab_ID=53055, TableName=DD_Order} (tableName=DD_Order)
        at org.adempiere.model.GridTabWrapper.create(GridTabWrapper.java:114)
        at org.adempiere.model.GridTabWrapper.create(GridTabWrapper.java:58)
        at org.adempiere.model.InterfaceWrapperHelper.create(InterfaceWrapperHelper.java:233)
        at org.adempiere.model.InterfaceWrapperHelper.create(InterfaceWrapperHelper.java:178)
        at org.compiere.model.CalloutInOut.docType(CalloutInOut.java:186)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.compiere.model.CalloutEngine.start(CalloutEngine.java:109)
        at org.adempiere.ad.callout.api.impl.legacy.LegacyCalloutAdapter.onFieldChanged(LegacyCalloutAdapter.java:152)
        at org.adempiere.ad.callout.api.impl.DefaultCalloutInstance.execute(DefaultCalloutInstance.java:112)
        at org.adempiere.ad.callout.api.impl.CalloutExecutor.execute(CalloutExecutor.java:151)
        at org.adempiere.ad.callout.api.impl.CalloutExecutor.execute(CalloutExecutor.java:110)
        at org.compiere.model.GridTab.processCallout(GridTab.java:3290)
        at org.compiere.model.GridTab.processFieldChange(GridTab.java:3211)
        at org.compiere.grid.GridController.dataStatusChanged(GridController.java:1265)
        at org.compiere.model.GridTab.fireDataStatusChanged(GridTab.java:2660)
        at org.compiere.model.GridTab.dataStatusChanged(GridTab.java:2626)
        at org.compiere.model.GridTable.fireDataStatusChanged(GridTable.java:3298)
        at org.compiere.model.GridTable.setValueAt(GridTable.java:1244)
        at org.compiere.grid.GridController.vetoableChange(GridController.java:1750)
        at java.beans.VetoableChangeSupport.fireVetoableChange(VetoableChangeSupport.java:375)
        at java.beans.VetoableChangeSupport.fireVetoableChange(VetoableChangeSupport.java:271)
        at javax.swing.JComponent.fireVetoableChange(JComponent.java:4534)
        at org.compiere.grid.ed.VLookup.actionCombo(VLookup.java:1011)
        at org.compiere.grid.ed.VLookup.actionPerformed(VLookup.java:946)
        at javax.swing.JComboBox.fireActionEvent(JComboBox.java:1258)
        at javax.swing.JComboBox.setSelectedItem(JComboBox.java:586)
        at javax.swing.JComboBox.setSelectedIndex(JComboBox.java:622)
        at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(BasicComboPopup.java:852)
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
        at java.awt.Component.processMouseEvent(Component.java:6535)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(BasicComboPopup.java:501)
        at java.awt.Component.processEvent(Component.java:6300)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4891)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4713)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
        at java.awt.Container.dispatchEventImpl(Container.java:2280)
        at java.awt.Window.dispatchEventImpl(Window.java:2750)
        at java.awt.Component.dispatchEvent(Component.java:4713)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
[14:20:31] Daniela Hoffmann: 2016-07-05 14:13:27.057  WARN 31043 --- [WT-EventQueue-0] org.compiere.model.GridTab               : Interface interface org.compiere.model.I_M_InOut (tableName=M_InOut) is not compatible with GridTab{TabNo=0, Name=Distribution Order, AD_Tab_ID=53055, TableName=DD_Order} (tableName=DD_Order)
```

**Comment by teosarca** [comment]
bug introduced in #136

**Comment by metas-ts** [comment]
Internal ID: FRESH-484
