### ISSUE TITLE
script processes cannot be loaded/started when attached to a buttin

### ISSUE THREAD

**Issue by homebeaver** [metasfresh/metasfresh#1638]
### Is this a bug or feature request?

bug

### What is the current behavior?

- I have a working process implemented by a groovy script, example see https://github.com/metasfresh/metasfresh/issues/695#issuecomment-298888785
- I attach the procces to a button
- when pushing I get

```
2017-05-24 17:26:52.160  INFO 6332 --- [WT-EventQueue-0] org.compiere.apps.APanel                 : VButton[TestExportModel=null]
2017-05-24 17:26:52.160  INFO 6332 --- [WT-EventQueue-0] org.compiere.apps.APanel                 : Process_ID=53089, Record_ID=50000
2017-05-24 17:26:52.207  WARN 6332 --- [WT-EventQueue-0] de.metas.process.ProcessClassInfo        : No class found for @script:groovy:Hello
2017-05-24 17:26:52.238  WARN 6332 --- [WT-EventQueue-0] de.metas.process.ProcessInfo             : Failed instantiating class '@script:groovy:Hello'. Skipped.

java.lang.ClassNotFoundException: @script:groovy:Hello
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:89)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at de.metas.process.ProcessInfo.newProcessClassInstanceOrNull(ProcessInfo.java:292)
        at de.metas.process.ProcessDefaultParametersUpdater.createProcessDefaultParametersProvider(ProcessDefaultParametersUpdater.java:98)
        at de.metas.process.ProcessDefaultParametersUpdater.addDefaultParametersProvider(ProcessDefaultParametersUpdater.java:87)
        at de.metas.process.ui.ProcessParameterPanelModel.<init>(ProcessParameterPanelModel.java:78)
        at de.metas.process.ui.ProcessParametersPanel.<init>(ProcessParametersPanel.java:111)
        at de.metas.process.ui.ProcessPanel.init(ProcessPanel.java:438)
        at de.metas.process.ui.ProcessPanel.<init>(ProcessPanel.java:136)
        at de.metas.process.ui.ProcessDialogBuilder.buildPanel(ProcessDialogBuilder.java:87)
        at de.metas.process.ui.ProcessModalDialog.<init>(ProcessModalDialog.java:57)
        at de.metas.process.ui.ProcessDialogBuilder.showModal(ProcessDialogBuilder.java:65)
        at org.compiere.apps.APanel.actionButton0(APanel.java:3129)
        at org.compiere.apps.APanel.actionButton(APanel.java:2837)
        at org.compiere.apps.APanel.actionPerformed(APanel.java:1959)
        at org.compiere.grid.GridController$1.actionPerformed(GridController.java:335)

```

#### Which are the steps to reproduce?

- first prepare a groovy script, which i documented in #695 
- then take any prepared process attached to a button or define a new one, I tested it with ad_process_id=53089  "TestExportModel" - in mf it is implemented by a java class `org.adempiere.process.rpl.exp.ModelExporter` . For testing I switch the implementation to `classname="@script:groovy:Hello"`
- now start the export window and push the button

### What is the expected or desired behavior?

Processes (java or script) can be started from menu item or via button push.

PS: in old Adempiere and in Idempiere it works!

**Comment by teosarca** [comment]
hi @homebeaver 

The exception you attached it's just a warning which didn't prevent execution.
While that warning might be part of the problem, i think the actual issue was logged a bit below.

It would help us a lot if you could attach a bigger part of the log or even entire log  (via https://pastebin.com/ or alternatives).

**Comment by homebeaver** [comment]
Tkx @teosarca ,
I tried it once more. And ... it works as expected.
I forgot to start the script in the modal window in the first test.
So I close the ticket.
