### ISSUE TITLE
docker container webapi not started

### ISSUE THREAD

**Issue by maikhir** [metasfresh/metasfresh#17897]
Hi,
i have started the docker container with docker compose but webapi container has some errors:

16:22:06.471 [C3P0PooledConnectionPoolManager[identityToken->1bqq1hib21y0ax8dwm5y67|dfd3711, dataSourceName->metasfreshDS]-HelperThread-#1] DEBUG com.mchange.v2.resourcepool.BasicResourcePool - An exception occurred while acquiring a poolable resource. Will retry.
webapi_1    | **org.postgresql.util.PSQLException: **FATAL: no pg_hba.conf entry for host "172.17.0.6", user "metasfresh", database "metasfresh", no encryption****
webapi_1    |   at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:646)
webapi_1    |   at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:180)
webapi_1    |   at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
webapi_1    |   at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
webapi_1    |   at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
webapi_1    |   at org.postgresql.Driver.makeConnection(Driver.java:400)
webapi_1    |   at org.postgresql.Driver.connect(Driver.java:259)
webapi_1    |   at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
webapi_1    |   at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
webapi_1    |   at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:214)
webapi_1    |   at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1176)
webapi_1    |   at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1163)
webapi_1    |   at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
webapi_1    |   at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1908)
webapi_1    |   at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
webapi_1    |   Suppressed: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "172.17.0.6", user "metasfresh", database "metasfresh", no encryption
webapi_1    |           at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:646)
webapi_1    |           at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:180)
webapi_1    |           at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:244)
webapi_1    |           ... 12 common frames omitted

**Comment by maikhir** [comment]
[docker-compose.yml.txt](https://github.com/metasfresh/metasfresh/files/15048995/docker-compose.yml.txt)
