### ISSUE TITLE
FRESH-511 Error in material tracking if one partner has two contracts (with different conditions) for the same product

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#183]
Internal: FRESH-511

Note: 
* in the concrete case this happened by accidently and one of the contracts wasn't used at all
* ut it might be that at such a scenarion is desired, and technically, it can be solved by taking into account the `C_Invoice_Candidate`'s `M_Material_Tracking_ID`

This is the error:
```
Error: We can have only one non-sim term for X_C_Invoice_Candidate[C_Invoice_Candidate_ID=2941368, trxName=TrxRun_0ebda1e7-94a4-4d06-a4bd-ccaa57ff79f8], but we have the following terms with at least two being non-sim: [MCFlatrateTerm[C_Flatrate_Term_ID=1000136, trxName=TrxRun_0ebda1e7-94a4-4d06-a4bd-ccaa57ff79f8], MCFlatrateTerm[C_Flatrate_Term_ID=1000366, trxName=TrxRun_0ebda1e7-94a4-4d06-a4bd-ccaa57ff79f8]]

org.adempiere.exceptions.AdempiereException: Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
Bitte leiten Sie diese Meldung an metas weiter:

Error: We can have only one non-sim term for X_C_Invoice_Candidate[C_Invoice_Candidate_ID=2941368, trxName=TrxRun_0ebda1e7-94a4-4d06-a4bd-ccaa57ff79f8], but we have the following terms with at least two being non-sim: [MCFlatrateTerm[C_Flatrate_Term_ID=1000136, trxName=TrxRun_0ebda1e7-94a4-4d06-a4bd-ccaa57ff79f8], MCFlatrateTerm[C_Flatrate_Term_ID=1000366, trxName=TrxRun_0ebda1e7-94a4-4d06-a4bd-ccaa57ff79f8]]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.adempiere.util.Check.mkEx(Check.java:106)
        at org.adempiere.util.Check.throwOrLogEx(Check.java:117)
        at org.adempiere.util.Check.errorIf(Check.java:456)
        at org.adempiere.util.Check.errorIf(Check.java:440)
        at de.metas.flatrate.api.impl.FlatrateDAO.retrieveNonSimTermOrNull(FlatrateDAO.java:558)
        at de.metas.flatrate.modelvalidator.C_Invoice_Candidate.modelChange(C_Invoice_Candidate.java:86)
        at org.compiere.model.ModelValidationEngine.fireModelChange(ModelValidationEngine.java:911)
        at org.compiere.model.ModelValidationEngine.fireModelChange0(ModelValidationEngine.java:765)
        at org.compiere.model.ModelValidationEngine.access$000(ModelValidationEngine.java:89)
        at org.compiere.model.ModelValidationEngine$1.run(ModelValidationEngine.java:719)
        at org.compiere.model.ModelValidationEngine$2.run(ModelValidationEngine.java:744)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run0(AbstractTrxManager.java:656)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:569)
        at org.compiere.model.ModelValidationEngine.executeInTrx(ModelValidationEngine.java:738)
        at org.compiere.model.ModelValidationEngine.fireModelChange(ModelValidationEngine.java:714)
        at org.compiere.model.PO.fireModelChange(PO.java:4875)
        at org.compiere.model.PO.save0(PO.java:2751)
        at org.compiere.model.PO.access$100(PO.java:129)
        at org.compiere.model.PO$1.run(PO.java:2658)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run0(AbstractTrxManager.java:656)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:569)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:476)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:420)
        at org.compiere.model.PO.saveEx(PO.java:2651)
        at org.adempiere.model.POWrapper.save(POWrapper.java:775)
        at org.adempiere.model.InterfaceWrapperHelper.save(InterfaceWrapperHelper.java:572)
        at de.metas.invoicecandidate.api.impl.InvoiceCandBL.closeInvoiceCandidate(InvoiceCandBL.java:2030)
        at de.metas.invoicecandidate.api.impl.InvoiceCandBL.closeInvoiceCandidates(InvoiceCandBL.java:1987)
        at de.metas.invoicecandidate.process.C_Invoice_Candidate_Close.doIt(C_Invoice_Candidate_Close.java:51)
        at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:208)
        at org.adempiere.util.ProcessUtil.startJavaProcess0(ProcessUtil.java:173)
        at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:112)
        at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:690)
        at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:429)
        at java.lang.Thread.run(Unknown Source)
```

note that to fix this, the material tracking module needs to register some information (CompositeFilter?) that can be used to augment the where-clause

**Comment by metas-ts** [comment]
fixing this particular problem might be easier: the MV in question can just ignore the changes that are just about `C_Invoice_Candidate.Processed_Override`

**Comment by metas-ts** [comment]
note for testers: the problem above is triggered by problematic C_Flatrate_terms. the solution is about refactoring a C_Invoice_Cadnidate model validator. Testing should be focused on regression. E.g. please check for packaging contracts if the ICs have IsToClear etc
