### ISSUE TITLE
Error Table M_Product does not have a simple primary key

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1843]
### Is this a bug or feature request?

Bug

### What is the current behavior?

```
I get stuck in other windows (like Materialvorgang) with the same message 
Table M_Product does not have a simple primary key
```

```
2017-06-17 14:08:29.336  WARN 19282 --- [WT-EventQueue-0] org.compiere.model.GridTable             : SaveError - org.postgresql.util.PSQLException: ERROR: null value in column "m_product_id" violates not-null constraint
  Detail: Failing row contains (null, 1000000, 1000000, Y, 2017-06-17 14:08:29+02, 2188223, 2017-06-17 14:08:29.306413+02, null, null, test, null, null, null, null, null, 100, 2188223, N, Y, Y, Y, N, N, N, N, null, 2001590, null, 0, 0, 0, 0, 0, 0, null, N, null, N, null, I, null, null, null, null, null, null, 0, null, null, null, null, N, Y, null, N, N, null, null, null, 0, 0, N, N, N, N, null, null, null, null).
        SQL: INSERT INTO M_Product (AD_Client_ID,AD_Org_ID,Created,CreatedBy,Discontinued,ShelfWidth,ShelfHeight,IsSelfService,SalesRep_ID,IsActive,UnitsPerPack,IsStocked,IsPurchased,ShelfDepth,C_UOM_ID,IsDiverse,IsCategoryProduct,Name,Processing,IsSummary,IsVerified,ProductType,IsExcludeAutoDelivery,M_Product_Category_ID,IsInvoicePrintDetails,LowLevel,Weight,Fresh_WashSampleRequired,IsBOM,IsSold,IsWebStoreFeatured,Volume,IsDropShip,UnitsPerPallet,Fresh_CropPlanning,IsPickListPrintDetails) VALUES (1000000,1000000,TO_TIMESTAMP('2017-06-17 14:08:29','YYYY-MM-DD HH24:MI:SS'),2188223,'N',0,0,'Y',2188223,'Y',0,'Y','Y',0,100,'N','N','test','N','N','N','I','N',2001590,'N',0,0,'N','N','Y','N',0,'N',0,'N','N')
14:08:46,752 |-INFO in ReconfigureOnChangeTask(born:1497698566748) - Empty watch file list. Disabling 
14:09:16,752 |-INFO in ReconfigureOnChangeTask(born:1497698566748) - Empty watch file list. Disabling 
14:09:46,752 |-INFO in ReconfigureOnChangeTask(born:1497698566748) - Empty watch file list. Disabling 
14:10:16,752 |-INFO in ReconfigureOnChangeTask(born:1497698566748) - Empty watch file list. Disabling 
14:10:46,752 |-INFO in ReconfigureOnChangeTask(born:1497698566748) - Empty watch file list. Disabling 
14:11:16,752 |-INFO in ReconfigureOnChangeTask(born:1497698566748) - Empty watch file list. Disabling 
14:11:46,752 |-INFO in ReconfigureOnChangeTask(born:1497698566748) - Empty watch file list. Disabling 
14:12:16,752 |-INFO in ReconfigureOnChangeTask(born:1497698566748) - Empty watch file list. Disabling 
14:12:46,752 |-INFO in ReconfigureOnChangeTask(born:1497698566748) - Empty watch file list. Disabling 
2017-06-17 14:12:49.964 ERROR 19282 --- [WT-EventQueue-0] org.compiere.model.MProduct              : Column not found - ProductType

017-06-17 14:12:49.971 ERROR 19282 --- [WT-EventQueue-0] org.compiere.model.MProduct              : Column not found - IsBOM
2017-06-17 14:12:49.975 ERROR 19282 --- [WT-EventQueue-0] org.compiere.model.MProduct              : Column not found - IsInvoicePrintDetails
2017-06-17 14:12:49.979 ERROR 19282 --- [WT-EventQueue-0] org.compiere.model.MProduct              : Column not found - IsPickListPrintDetails
2017-06-17 14:12:49.983 ERROR 19282 --- [WT-EventQueue-0] org.compiere.model.MProduct              : Column not found - IsPurchased
2017-06-17 14:12:49.987 ERROR 19282 --- [WT-EventQueue-0] org.compiere.model.MProduct              : Column not found - IsSold
2017-06-17 14:12:49.991 ERROR 19282 --- [WT-EventQueue-0] org.compiere.model.MProduct              : Column not found - IsStocked
2017-06-17 14:12:49.995 ERROR 19282 --- [WT-EventQueue-0] org.compiere.model.MProduct              : Column not found - IsSummary
2017-06-17 14:12:49.999 ERROR 19282 --- [WT-EventQueue-0] org.compiere.model.MProduct              : Column not found - IsVerified
2017-06-17 14:12:50.003 ERROR 19282 --- [WT-EventQueue-0] org.compiere.model.MProduct              : Column not found - IsWebStoreFeatured
2017-06-17 14:12:50.007 ERROR 19282 --- [WT-EventQueue-0] org.compiere.model.MProduct              : Column not found - IsSelfService
2017-06-17 14:12:50.011 ERROR 19282 --- [WT-EventQueue-0] org.compiere.model.MProduct              : Column not found - IsExcludeAutoDelivery
2017-06-17 14:12:50.016 ERROR 19282 --- [WT-EventQueue-0] org.compiere.model.MProduct              : Column not found - Processing
2017-06-17 14:12:50.019 ERROR 19282 --- [WT-EventQueue-0] org.compiere.model.MProduct              : Column not found - LowLevel
2017-06-17 14:12:50.023  WARN 19282 --- [WT-EventQueue-0] org.compiere.model.MProduct              : Column not found - ProductType
2017-06-17 14:12:50.023 ERROR 19282 --- [WT-EventQueue-0] org.compiere.model.MProduct              : Column not found - IsStocked
2017-06-17 14:12:50.033 ERROR 19282 --- [WT-EventQueue-0] org.compiere.model.GridTable             : Error while saving on GridTable[M_Product,WindowNo=3,Tab=0]
 Type: SaveError

org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: ERROR: null value in column "m_product_id" violates not-null constraint
  Detail: Failing row contains (null, 1000000, 1000000, Y, 2017-06-17 14:12:49+02, 2188223, 2017-06-17 14:12:50.017865+02, null, null, test, null, null, null, null, null, 100, 2188223, N, Y, Y, Y, N, N, N, N, null, 2001590, null, 0, 0, 0, 0, 0, 0, null, N, null, N, null, I, null, null, null, null, null, null, 0, null, null, null, null, N, Y, null, N, N, null, null, null, 0, 0, N, N, N, N, null, null, null, null).
        SQL: INSERT INTO M_Product (AD_Client_ID,AD_Org_ID,Created,CreatedBy,Discontinued,ShelfWidth,ShelfHeight,IsSelfService,SalesRep_ID,IsActive,UnitsPerPack,IsStocked,IsPurchased,ShelfDepth,C_UOM_ID,IsDiverse,IsCategoryProduct,Name,Processing,IsSummary,IsVerified,ProductType,IsExcludeAutoDelivery,M_Product_Category_ID,IsInvoicePrintDetails,LowLevel,Weight,Fresh_WashSampleRequired,IsBOM,IsSold,IsWebStoreFeatured,Volume,IsDropShip,UnitsPerPallet,Fresh_CropPlanning,IsPickListPrintDetails) VALUES (1000000,1000000,TO_TIMESTAMP('2017-06-17 14:12:49','YYYY-MM-DD HH24:MI:SS'),2188223,'N',0,0,'Y',2188223,'Y',0,'Y','Y',0,100,'N','N','test','N','N','N','I','N',2001590,'N',0,0,'N','N','Y','N',0,'N',0,'N','N')
        at org.adempiere.exceptions.DBException.wrapIfNeeded(DBException.java:88)
        at org.compiere.util.DB.executeUpdate(DB.java:990)
        at org.compiere.model.PO.saveNew(PO.java:3694)
        at org.compiere.model.PO.save0(PO.java:2869)
        at org.compiere.model.PO.access$100(PO.java:134)
        at org.compiere.model.PO$1.run(PO.java:2771)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:771)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:683)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:584)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:515)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:500)
        at org.compiere.model.PO.saveEx(PO.java:2764)
        at org.compiere.model.GridTable.dataSavePO(GridTable.java:2139)
        at org.compiere.model.GridTable.dataSave(GridTable.java:1460)
        at org.compiere.model.GridTab.dataSave(GridTab.java:1321)
        at org.compiere.apps.APanel.cmd_save(APanel.java:2375)
        at org.compiere.apps.APanel.actionPerformed(APanel.java:1967)
        at org.compiere.apps.AppsAction.actionPerformed(AppsAction.java:454)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
        at java.awt.Component.processMouseEvent(Component.java:6533)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6298)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
        at java.awt.Container.dispatchEventImpl(Container.java:2280)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "m_product_id" violates not-null constraint
  Detail: Failing row contains (null, 1000000, 1000000, Y, 2017-06-17 14:12:49+02, 2188223, 2017-06-17 14:12:50.017865+02, null, null, test, null, null, null, null, null, 100, 2188223, N, Y, Y, Y, N, N, N, N, null, 2001590, null, 0, 0, 0, 0, 0, 0, null, N, null, N, null, I, null, null, null, null, null, null, 0, null, null, null, null, N, Y, null, N, N, null, null, null, 0, 0, N, N, N, N, null, null, null, null).
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:135)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:1449)
        at org.adempiere.sql.impl.CPreparedStatementProxy.executeUpdate(CPreparedStatementProxy.java:128)
        at org.compiere.util.DB.executeUpdate(DB.java:921)
        ... 55 common frames omitted

2017-06-17 14:12:50.040  WARN 19282 --- [WT-EventQueue-0] org.compiere.model.GridTable             : SaveError - org.postgresql.util.PSQLException: ERROR: null value in column "m_product_id" violates not-null constraint
  Detail: Failing row contains (null, 1000000, 1000000, Y, 2017-06-17 14:12:49+02, 2188223, 2017-06-17 14:12:50.017865+02, null, null, test, null, null, null, null, null, 100, 2188223, N, Y, Y, Y, N, N, N, N, null, 2001590, null, 0, 0, 0, 0, 0, 0, null, N, null, N, null, I, null, null, null, null, null, null, 0, null, null, null, null, N, Y, null, N, N, null, null, null, 0, 0, N, N, N, N, null, null, null, null).
        SQL: INSERT INTO M_Product (AD_Client_ID,AD_Org_ID,Created,CreatedBy,Discontinued,ShelfWidth,ShelfHeight,IsSelfService,SalesRep_ID,IsActive,UnitsPerPack,IsStocked,IsPurchased,ShelfDepth,C_UOM_ID,IsDiverse,IsCategoryProduct,Name,Processing,IsSummary,IsVerified,ProductType,IsExcludeAutoDelivery,M_Product_Category_ID,IsInvoicePrintDetails,LowLevel,Weight,Fresh_WashSampleRequired,IsBOM,IsSold,IsWebStoreFeatured,Volume,IsDropShip,UnitsPerPallet,Fresh_CropPlanning,IsPickListPrintDetails) VALUES (1000000,1000000,TO_TIMESTAMP('2017-06-17 14:12:49','YYYY-MM-DD HH24:MI:SS'),2188223,'N',0,0,'Y',2188223,'Y',0,'Y','Y',0,100,'N','N','test','N','N','N','I','N',2001590,'N',0,0,'N','N','Y','N',0,'N',0,'N','N')
14:13:16,752 |-INFO in ReconfigureOnChangeTask(born:1497698566748) - Empty w
```

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
cache reset process is not in menu anymore. OK
