### ISSUE TITLE
error with order that has just packaging lines

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1855]
### Is this a bug or feature request?
Bug
### What is the current behavior?

```
org.adempiere.exceptions.AdempiereException: Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
Bitte leiten Sie diese Meldung an metas weiter:

Assumption failure: One and only one was expected for: []
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.adempiere.util.Check.mkEx(Check.java:109)
        at org.adempiere.util.Check.throwOrLogEx(Check.java:120)
        at org.adempiere.util.Check.assume(Check.java:163)
        at org.adempiere.util.Check.assume(Check.java:147)
        at org.adempiere.util.collections.ListUtils.singleElement(ListUtils.java:277)
        at de.metas.adempiere.service.impl.OrderBL.updateOrderQtySums(OrderBL.java:922)
        at de.metas.order.model.interceptor.C_OrderLine.updateQuantities(C_OrderLine.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.executeNow(AnnotatedModelInterceptor.java:560)
        at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.execute(AnnotatedModelInterceptor.java:504)
        at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.execute(AnnotatedModelInterceptor.java:458)
        at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.onModelChange(AnnotatedModelInterceptor.java:436)
        at org.adempiere.ad.modelvalidator.ModelInterceptor2ModelValidatorWrapper.modelChange(ModelInterceptor2ModelValidatorWrapper.java:124)
        at org.compiere.model.ModelValidationEngine.fireModelChange(ModelValidationEngine.java:917)
        at org.compiere.model.ModelValidationEngine.fireModelChange0(ModelValidationEngine.java:780)
        at org.compiere.model.ModelValidationEngine.access$000(ModelValidationEngine.java:90)
        at org.compiere.model.ModelValidationEngine$1.run(ModelValidationEngine.java:735)
        at org.compiere.model.ModelValidationEngine$2.run(ModelValidationEngine.java:759)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:763)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:675)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:583)
        at org.compiere.model.ModelValidationEngine.executeInTrx(ModelValidationEngine.java:754)
        at org.compiere.model.ModelValidationEngine.fireModelChange(ModelValidationEngine.java:730)
        at org.compiere.model.PO.fireModelChange(PO.java:4929)
        at org.compiere.model.PO.saveFinish(PO.java:2941)
        at org.compiere.model.PO.saveUpdate(PO.java:3312)
        at org.compiere.model.PO.save0(PO.java:2876)
        at org.compiere.model.PO.access$100(PO.java:133)
        at org.compiere.model.PO$1.run(PO.java:2770)
```

**Comment by teosarca** [comment]
rolled on w101
