### ISSUE TITLE
Support multiple email recipients

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1953]
### Is this a bug or feature request?

Bug

### What is the current behavior?

* Enter one mail address in `AD_User.Email` => you can send a mail to that user
* Enter multiple `;` separated mail addreses => you can't send a mail

#### Which are the steps to reproduce?

try it..

### What is the expected or desired behavior?

there shall be a way to support multiple email addresses per user, which shall all receive a mail from e.g. purchase order

* suggestion1: 
add new field/column `AD_User.SecondaryEmails` and
  * when sending a mail to that user, all email addresses are used
* suggestion 2:
allow multiple email addresses in the `AD_User.Email`field, unless the user in question is supposed to log in with that mail address (`IsSytemUser` or `IsMFProcurementUser`)
  * question: how to provide multiple mailaddresses to those?

What also imho should be done while we are at it: do syntax validation of all those fields' values

**Comment by metas-ts** [comment]
cherry-picked to `release` and `20170628-release-157-br`

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

The email works only for one address, not for 2 addresses separated by ";"

**Comment by teosarca** [comment]
failing stacktrace is
```
javax.mail.internet.AddressException: Illegal semicolon, not in group
        at javax.mail.internet.InternetAddress.parse(InternetAddress.java:863)
        at javax.mail.internet.InternetAddress.parse(InternetAddress.java:575)
        at javax.mail.internet.InternetAddress.<init>(InternetAddress.java:107)
        at javax.mail.internet.InternetAddress.<init>(InternetAddress.java:135)
        at de.metas.email.EMail.addTo(EMail.java:534)
        at de.metas.email.EMail.<init>(EMail.java:145)
        at de.metas.email.impl.MailBL.createEMail(MailBL.java:172)
        at de.metas.email.impl.MailBL.createEMail(MailBL.java:150)
        at de.metas.ui.web.mail.MailRestController.sendEmail(MailRestController.java:217)
        at de.metas.ui.web.mail.MailRestController.lambda$sendEmail$1(MailRestController.java:195)
        at de.metas.ui.web.mail.MailRestController.lambda$changeEmail$5(MailRestController.java:283)
        at de.metas.ui.web.mail.WebuiMailRepository$WebuiEmailEntry.compute(WebuiMailRepository.java:167)
        at de.metas.ui.web.mail.WebuiMailRepository.changeEmail(WebuiMailRepository.java:117)
        at de.metas.ui.web.mail.MailRestController.changeEmail(MailRestController.java:281)
        at de.metas.ui.web.mail.MailRestController.sendEmail(MailRestController.java:195)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
```

**Comment by teosarca** [comment]
note to IT: 
* pls do regression for Swing too
* pls add this to testing catalog (if not already)

**Comment by metas-rc** [comment]
Results of IT

Tested on webui and swing, using mail hog.

Added several e-mai laddresses to a user.
Created a purchase order for that partner, completed it
Opened email, attached files, sent the email
The email was correctly received on all the addresses I set for that user. => OK

**Comment by metas-ts** [comment]
Cherry-picked the fix to the crrent `release` branch, see https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/196/
