### ISSUE TITLE
Error: Missing ESR creditor reference on CAMT 54 Import

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2107]
### Is this a bug or feature request?
Bug
### What is the current behavior?
If a camt.54 file contains no ESR reference, then loading the file fails, and there is a stack trace like this
```
org.adempiere.exceptions.AdempiereException: Error: Missing ESR creditor reference
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at reflect.Constructor.newInstance(Constructor.java:423)
	at org.adempiere.util.Check.mkEx(Check.java:84)
	at org.adempiere.util.Check.throwOrLogEx(Check.java:95)
	at org.adempiere.util.Check.errorUnless(Check.java:399)
	at org.adempiere.util.Check.errorUnless(Check.java:383)
	at de.metas.payment.esr.dataimporter.impl.camt54.ESRDataImporterCamt54.importData(ESRDataImporterCamt54.java:182)
	at de.metas.payment.esr.api.impl.ESRImportBL.loadAndEvaluateESRImportStream(ESRImportBL.java:189)
	at de.metas.payment.esr.api.impl.ESRImportBL.loadAndEvaluateESRImportFile0(ESRImportBL.java:175)
	at de.metas.payment.esr.api.impl.ESRImportBL.access$000(ESRImportBL.java:88)
	at de.metas.payment.esr.api.impl.ESRImportBL$1.run(ESRImportBL.java:158)
	at de.metas.payment.esr.api.impl.ESRImportBL.lockAndProcess(ESRImportBL.java:120)
	at de.metas.payment.esr.api.impl.ESRImportBL.loadESRImportFile(ESRImportBL.java:153)
	at de.metas.payment.esr.processor.impl.LoadESRImportFileWorkpackageProcessor.processWorkPackage(LoadESRImportFileWorkpackageProcessor.java:67)
	at de.metas.async.processor.impl.WorkpackageProcessor2Wrapper.processWorkPackage(WorkpackageProcessor2Wrapper.java:58)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.processWorkpackage(WorkpackageProcessorTask.java:274)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.access$000(WorkpackageProcessorTask.java:79)
	at de.metas.async.processor.impl.WorkpackageProcessorTask$1.run(WorkpackageProcessorTask.java:157)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$1.call(TrxCallableWrappers.java:61)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$1.ca
```

Instead of that, the XML file should be loaded with errors, so that the user has ca change to act on the problem.

**Comment by cristinamghita** [comment]
# Results of IT - tested on webui
## Setup
### Setup ESR
* First the esr needs to be enable. See http://docs.metasfresh.org/howto_collection/Wie_konfiguriere_ich_den_ESR_Zahlschein.html
* The make sure that bank account of the bpartner of the org is properly setup. See bellow.
  ![image](https://user-images.githubusercontent.com/15378036/35161764-d7070852-fd49-11e7-9b43-1c422189fdbf.png)
