### ISSUE TITLE
npe on zoom into header aggregation

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2240]
### Is this a bug or feature request?
bug
### What is the current behavior?
if you zoom into header aggregation in invoice candidates you get NPE
#### Which are the steps to reproduce?
1. go to invoice candidate window (540092)
2. select one and open doc view
3. zoom into header aggregation (Abrechnungsgruppe eff.)
=> swing: npe, webui: No windowId found

```
2017-08-24 13:38:47.225  WARN 2853 --- [WT-EventQueue-0] d.m.a.form.swing.SwingClientUIInstance   : java.lang.NullPointerException

java.lang.NullPointerException: null
	at org.compiere.apps.APanel.initPanel(APanel.java:800)
	at org.compiere.apps.AWindow.initWindow(AWindow.java:98)
	at org.compiere.grid.ed.menu.ZoomContextEditorAction.zoom(ZoomContextEditorAction.java:214)
	at org.compiere.grid.ed.menu.ZoomContextEditorAction.zoomGeneric(ZoomContextEditorAction.java:206)
	at org.compiere.grid.ed.menu.ZoomContextEditorAction.run0(ZoomContextEditorAction.java:134)
	at org.compiere.grid.ed.menu.ZoomContextEditorAction.run(ZoomContextEditorAction.java:114)
	at org.compiere.grid.ed.menu.EditorContextPopupMenu.executeAction(EditorContextPopupMenu.java:412)
	at org.compiere.grid.ed.menu.EditorContextPopupMenu.access$000(EditorContextPopupMenu.java:62)
	at org.compiere.grid.ed.menu.EditorContextPopupMenu$2.actionPerformed(EditorContextPopupMenu.java:257)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### What is the expected or desired behavior?
return a message that the window does not exist

**Comment by cristinamghita** [comment]
* Fixed by adding link the window 
* in webui still nor working because is missing the window for webui
See follow up  [#2715 Create webui window for C_Invoice_Candidate_Agg](https://github.com/metasfresh/metasfresh/issues/2715)

**Comment by metas-lc** [comment]
IT
webui: 
Error: Cannot find the detail...
Cannot find the detail tab to zoom into
OK
swing 
it opens the window
