### ISSUE TITLE
Can't save a new partner

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#2779]
### Is this a bug or feature request?
Bug
### What is the current behavior?
* The partner is not saved
#### Which are the steps to reproduce?
* create a new partner
* the partner is not saved
![image](https://user-images.githubusercontent.com/15378036/31816545-6b4761ae-b599-11e7-8102-91678733c2da.png)
And see trace:
```

java.lang.NullPointerException: null
    at de.metas.ui.web.window.model.sql.SqlDocumentsRepository.saveLabels(SqlDocumentsRepository.java:910)
    at de.metas.ui.web.window.model.sql.SqlDocumentsRepository.lambda$0(SqlDocumentsRepository.java:523)
    at de.metas.ui.web.window.model.sql.SqlDocumentsRepository.lambda$1(SqlDocumentsRepository.java:553)
    at java.util.ArrayList.forEach(ArrayList.java:1249)
    at de.metas.ui.web.window.model.sql.SqlDocumentsRepository.save(SqlDocumentsRepository.java:553)
    at de.metas.ui.web.window.model.Document.saveIfHasChanges(Document.java:1850)
    at de.metas.ui.web.window.model.Document.saveIfValidAndHasChanges(Document.java:1831)
    at de.metas.ui.web.window.model.DocumentCollection.commitRootDocument(DocumentCollection.java:378)
    at de.metas.ui.web.window.model.DocumentCollection.forRootDocumentWritable(DocumentCollection.java:300)
    at de.metas.ui.web.window.model.DocumentCollection.forDocumentWritable(DocumentCollection.java:229)
    at de.metas.ui.web.window.controller.WindowRestController.patchDocument0(WindowRestController.java:313)
    at de.metas.ui.web.window.controller.WindowRestController.lambda$8(WindowRestController.java:307)
    at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$4.call(TrxCallableWrappers.java:193)
    at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)
    at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:771)
    at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:683)
    at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:584)
    at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:515)
    at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:492)
    at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:469)
    at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$0(Execution.java:194)
    at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$2(Execution.java:237)
    at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)
    at de.metas.ui.web.window.controller.Execution.callInNewExecution(Execution.java:88)
    at de.metas.ui.web.window.controller.WindowRestController.patchDocument(WindowRestController.java:307)
    at de.metas.ui.web.window.controller.WindowRestController.patchRootDocument(WindowRestController.java:276)
```
### What is the expected or desired behavior?
* The partner shall be saved

**Comment by cristinamghita** [comment]
See [Can't save a new partner #639](https://github.com/metasfresh/metasfresh-webui-api/issues/639)
