### ISSUE TITLE
ExpressionEvaluationException when opening BankStatement window in webui

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#2817]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Error in log trace regarding StatementDate
```
d.m.u.w.s.WebRestApiContextProvider      : Created user session context: sessionId=a48ae958-a577-4012-9a19-aaa31bfcdf93, context={#IsWebuiServerContext=N}
2017-10-24 14:46:57.037  WARN 27392 [ 0:0:0:0:0:0:0:1][metasfresh] --- [nio-8181-exec-1] de.metas.ui.web.window.model.Document    : Failed initializing DocumentField{fieldName=C_BankStatement.StatementDate, value=null, initalValue=null}, mode=NewDocument using InitialFieldValueSupplier{type=Window, typeId=194, evaluatee=DocumentEvaluatee{Document{tableName=C_BankStatement, id=NEW, NEW=true, windowNo=8, writable=true, valid=Invalid-Initial('not validated yet'), validOnCheckout=Invalid-Initial('not validated yet'), saveStatus=DocumentSaveStatus{saved=false, hasChangesToBeSaved=true, error=false, reason=not yet checked}, saveStatusOnCheckout=DocumentSaveStatus{saved=false, hasChangesToBeSaved=true, error=false, reason=not yet checked}}}}. Keeping current initial value.

org.adempiere.ad.expression.exceptions.ExpressionEvaluationException: @NotFound@: Date
	at org.adempiere.ad.expression.api.impl.StringExpressionSupportTemplate$SingleParameterExpressionTemplate.evaluate(StringExpressionSupportTemplate.java:372)
	at de.metas.ui.web.window.model.Document$InitialFieldValueSupplier.getValue(Document.java:684)
	at de.metas.ui.web.window.model.Document.initializeField(Document.java:495)
	at de.metas.ui.web.window.model.Document.initializeFields(Document.java:413)
	at de.metas.ui.web.window.model.Document.access$5(Document.java:398)
	at de.metas.ui.web.window.model.Document$Builder.build(Document.java:2099)
	at de.metas.ui.web.window.model.Document$Builder.initializeAsNewDocument(Document.java:2173)
	at de.metas.ui.web.window.model.Document$Builder.initializeAsNewDocument(Document.java:2178)
	at de.metas.ui.web.window.model.sql.SqlDocumentsRepository.createNewDocument(SqlDocumentsRepository.java:304)
	at de.metas.ui.web.window.model.DocumentCollection.createRootDocument(DocumentCollection.java:326)
	at de.metas.ui.web.window.model.DocumentCollection.forRootDocumentWritable(DocumentCollection.java:259)
	at de.metas.ui.web.window.model.DocumentCollection.forDocumentWritable(DocumentCollection.java:229)
	at de.metas.ui.web.window.controller.WindowRestController.patchDocument0(WindowRestController.java:318)
```
#### Which are the steps to reproduce?
* Open Bank statement window
### What is the expected or desired behavior?
* No error should be in the console

**Comment by cristinamghita** [comment]
Discovered while testing [#2634 Make the CalloutBankStatement webui compliant](https://github.com/metasfresh/metasfresh/issues/2634)
