### ISSUE TITLE
Mass printing into calibrated PDF throws Heap Space error on docker environment

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2852]
### Is this a bug or feature request?
bug

### What is the current behavior?
cant print 250 invoices into calibrated PDF in docker environment

#### Which are the steps to reproduce?
1. have 250 invoices
1. print them all on metasfresh PDF printer
1. NOK after 45 minutes I got error "Java heap space" in async package

```
org.adempiere.exceptions.AdempiereException: Java heap space
	at org.adempiere.exceptions.AdempiereException.wrapIfNeeded(AdempiereException.java:87)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:854)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:683)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:591)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.run(WorkpackageProcessorTask.java:158)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at Thread.run(Thread.java:748)
Caused by: OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:191)
	at de.metas.printing.MergePdfByteArrays.getMergedPdfByteArray(MergePdfByteArrays.java:47)
	at de.metas.printing.async.spi.impl.PDFDocPrintingWorkpackageProcessor.print(PDFDocPrintingWorkpackageProcessor.java:165)
	at de.metas.printing.async.spi.impl.PDFDocPrintingWorkpackageProcessor.processWorkPackage(PDFDocPrintingWorkpackageProcessor.java:90)
	at de.metas.async.processor.impl.WorkpackageProcessor2Wrapper.processWorkPackage(WorkpackageProcessor2Wrapper.java:58)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.invokeProcessorAndHandleException(WorkpackageProcessorTask.java:293)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.processWorkpackage(WorkpackageProcessorTask.java:285)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.access$000(WorkpackageProcessorTask.java:85)
	at de.metas.async.processor.impl.WorkpackageProcessorTask$1.run(WorkpackageProcessorTask.java:168)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:103)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:93)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:771)
	... 8 more

```

### What is the expected or desired behavior?
shall work without exception

**Comment by metasnw** [comment]
same process works fine for single invoice. takes a few seconds to print into pdf

**Comment by metasnw** [comment]
1. was solved by increasing the RAM from 500 MB to higher value
1. set maxlinesperjob to 100

**Comment by metasnw** [comment]
lesson learned: the size and resolution of the logo used in the invoice has big impact to the speed
