### ISSUE TITLE
Can't order by Created in webui

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#2899]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Can't order by created in printing queue
#### Which are the steps to reproduce?
Try to order and you will get this:
```
SQL: INSERT INTO T_WEBUI_ViewSelection ( UUID, Line, Record_ID)
 SELECT 
  ?
, row_number() OVER (ORDER BY (Created) ASC)
, master.C_Printing_Queue_ID
 FROM T_WEBUI_ViewSelection sel
 LEFT OUTER JOIN C_Printing_Queue master ON (master.C_Printing_Queue_ID=sel.Record_ID)
 WHERE sel.UUID=?
	SQL params: [540165-8e74f4eef83d480787caa1a255aeb9e5, 540165-875c83175369472cadb8a011bcc550a3]
	at org.adempiere.exceptions.DBException.wrapIfNeeded(DBException.java:89)
	at org.compiere.util.DB.executeUpdate(DB.java:998)
	at org.compiere.util.DB.executeUpdateEx(DB.java:1048)
	at org.compiere.util.DB.executeUpdateEx(DB.java:1031)
	at de.metas.ui.web.view.SqlViewRowIdsOrderedSelectionFactory.createOrderedSelectionFromSelection(SqlViewRowIdsOrderedSelectionFactory.java:148)
	at de.metas.ui.web.view.SqlViewDataRepository.createOrderedSelectionFromSelection(SqlViewDataRepository.java:178)
	at de.metas.ui.web.view.DefaultView.lambda$2(DefaultView.java:345)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at de.metas.ui.web.view.DefaultView.getOrderedSelection(DefaultView.java:345)
	at de.metas.ui.web.view.DefaultView.getPage(DefaultView.java:295)
	at de.metas.ui.web.view.ViewRestController.getViewData(ViewRestController.java:231)
	at sun.reflect.GeneratedMethodAccessor939.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
```
### What is the expected or desired behavior?
Should be able to order.

**Comment by cristinamghita** [comment]
See [ #657 Can't order by Created in webui](https://github.com/metasfresh/metasfresh/issues/2899)
