### ISSUE TITLE
error in console when creating customer return

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2966]
### Is this a bug or feature request?
bug
### What is the current behavior?
it's not a showstopper, but it appears in console when you do a customer return:
https://pastebin.com/fJJFhHbN
#### Which are the steps to reproduce?
if there is enough data: just go to a sales inout that has real HUs and create a customer return using button: "Return from Customer"
=> error in console https://pastebin.com/fJJFhHbN
ELSE:
1. create and complete a purchase order, warehouse X
2. go to receipt candidates and create inout
3. create and complete a sales order, warehouse X
4. go to picking terminal and pick the hu from step 2
5. create a sales inout using the qty of the HU
6. go to shipment and select button: "Return from Customer", create customer return
=> error in console https://pastebin.com/fJJFhHbN
### What is the expected or desired behavior?
shall not be any errors

**Comment by metas-lc** [comment]
IT
repeated the testcase (in swing) and got this (note: it's not a showstopper. Only in console)

```org.adempiere.exceptions.AdempiereException: STACKTRACE
	at org.adempiere.ad.trx.api.impl.TrxListenerManager.registerListener(TrxListenerManager.java:103)
	at org.compiere.model.PO.retrieveAndSetIds(PO.java:3334)
	at org.compiere.model.PO.saveNew(PO.java:3360)
	at org.compiere.model.PO.save0(PO.java:2809)
	at org.compiere.model.PO.access$100(PO.java:138)
	at org.compiere.model.PO$1.run(PO.java:2711)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:771)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:683)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:584)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:515)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:500)
	at org.compiere.model.PO.saveEx(PO.java:2704)
	at org.adempiere.model.POWrapper.save(POWrapper.java:781)
	at org.adempiere.model.InterfaceWrapperHelper.save(InterfaceWrapperHelper.java:541)
	at de.metas.handlingunits.trace.HUTraceRepository.addEvent(HUTraceRepository.java:65)
	at de.metas.handlingunits.trace.HUTraceEventsService.createAndAddEvents(HUTraceEventsService.java:497)
	at de.metas.handlingunits.trace.HUTraceEventsService.createAndAddFor(HUTraceEventsService.java:159)
	at de.metas.handlingunits.trace.interceptor.M_Movement.addTraceEvent(M_Movement.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.executeNow0(AnnotatedModelInterceptor.java:607)
	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.executeNow(AnnotatedModelInterceptor.java:559)
	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.access$000(AnnotatedModelInterceptor.java:51)
	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor$1.afterCommit(AnnotatedModelInterceptor.java:527)
	at org.adempiere.ad.trx.api.impl.TrxListenerManager.lambda$fireAfterCommit$1(TrxListenerManager.java:135)
	at org.adempiere.ad.trx.api.impl.TrxListenerManager.fireListeners(TrxListenerManager.java:173)
	at org.adempiere.ad.trx.api.impl.TrxListenerManager.fireAfterCommit(TrxListenerManager.java:135)
	at org.adempiere.ad.trx.api.impl.AbstractTrx.commit(AbstractTrx.java:269)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:781)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:683)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:584)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:515)
	at de.metas.handlingunits.inout.impl.MultiCustomerHUReturnsInOutProducer.create(MultiCustomerHUReturnsInOutProducer.java:99)
	at de.metas.handlingunits.inout.impl.HUInOutBL.createCustomerReturnInOutForHUs(HUInOutBL.java:261)
	at de.metas.handlingunits.client.terminal.shipment.model.ReturnFromCustomerHUEditorModel.createCustomerReturn(ReturnFromCustomerHUEditorModel.java:96)
	at de.metas.handlingunits.client.terminal.shipment.view.ReturnFromCustomerHUEditorPanel.doReturnFromCustomer(ReturnFromCustomerHUEditorPanel.java:56)
	at de.metas.handlingunits.client.terminal.shipment.view.ReturnFromCustomerHUEditorPanel$1.propertyChangeEx(ReturnFromCustomerHUEditorPanel.java:90)
	at de.metas.adempiere.form.terminal.event.UIPropertyChangeListener.lambda$propertyChange$1(UIPropertyChangeListener.java:115)
	at de.metas.adempiere.form.swing.SwingClientUIInvoker$1.run(SwingClientUIInvoker.java:107)
	at de.metas.adempiere.form.AbstractClientUIInvoker$1.run(AbstractClientUIInvoker.java:133)
	at de.metas.adempiere.form.AbstractClientUIInvoker.invoke(AbstractClientUIInvoker.java:103)
	at de.metas.adempiere.form.AbstractClientUIInvoker.invoke(AbstractClientUIInvoker.java:68)
	at de.metas.adempiere.form.terminal.event.UIPropertyChangeListener.propertyChange(UIPropertyChangeListener.java:115)
	at org.adempiere.util.beans.WeakPropertyChangeListener.propertyChange(WeakPropertyChangeListener.java:168)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at de.metas.adempiere.form.terminal.swing.SwingTerminalButtonWrapper$1.actionPerformed(SwingTerminalButtonWrapper.java:80)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by metas-lc** [comment]
IT
repeated the testcase above =>  no errors OK
