### ISSUE TITLE
Move UI Element Action broken

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3100]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When using Move UI Element Action in Window Customizing, then an error appears.
#### Which are the steps to reproduce?
Ty to move an UI Element from 1 Section to another with Action "Move UI Element"
### What is the expected or desired behavior?
Shall work.

```
org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: ERROR: column "ad_ui_element.seqno" must appear in the GROUP BY clause or be used in an aggregate function
  Position: 104
        SQL: SELECT MAX(SeqNo) FROM AD_UI_Element
 WHERE ((IsActive=?) AND (AD_UI_ElementGroup_ID = ?))
 ORDER BY SeqNo ASC NULLS LAST
        at org.adempiere.ad.dao.impl.TypedSqlQuery.aggregateList(TypedSqlQuery.java:692)
        at org.adempiere.ad.dao.impl.TypedSqlQuery.aggregate(TypedSqlQuery.java:607)
        at org.compiere.model.IQuery.aggregate(IQuery.java:267)
        at org.adempiere.ad.window.api.impl.ADWindowDAO.retrieveUIElementNextSeqNo(ADWindowDAO.java:207)
        at org.adempiere.ad.window.api.impl.ADWindowDAO.moveElement(ADWindowDAO.java:289)
        at org.adempiere.ad.window.process.AD_UI_Element_Move.doIt(AD_UI_Element_Move.java:54)
        at de.metas.process.JavaProcess.startProcess(JavaProcess.java:291)
        at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:563)
        at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:459)
        at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:49)
        at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:223)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:771)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:683)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:584)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:515)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:500)
        at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:285)
        at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:170)
        at de.metas.process.ProcessExecutor.lambda$executeAsync$0(ProcessExecutor.java:118)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.postgresql.util.PSQLException: ERROR: column "ad_ui_element.seqno" must appear in the GROUP BY clause or be used in an aggregate function
  Position: 104
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1418)
        at org.adempiere.sql.impl.CPreparedStatementProxy.executeQuery(CPreparedStatementProxy.java:122)
        at org.adempiere.ad.dao.impl.TypedSqlQuery.createResultSet(TypedSqlQuery.java:1272)
        at org.adempiere.ad.dao.impl.TypedSqlQuery.aggregateList(TypedSqlQuery.java:676)
        ... 21 common frames omitted
```

![image](https://user-images.githubusercontent.com/13365687/33360581-98667242-d4d4-11e7-88d7-130336330758.png)

**Comment by metas-rc** [comment]
Results of IT

Tested on swing


* OK: The process Move UI Element works correctly now, with no error.
