### ISSUE TITLE
Import BPartner window: cannot see data

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#3138]
### Is this a bug or feature request?
bug
### What is the current behavior?
cannot see the data in Import BPartner window
#### Which are the steps to reproduce?
open Import BPartner window, see console:
```
2017-12-05 16:28:04.593 ERROR 949 --- [WT-EventQueue-0] org.compiere.model.GridTable             : SELECT Updated,CreatedBy,Created,UpdatedBy,I_BPartner_ID,I_IsImported,C_BPartner_ID,I_ErrorMsg,AD_Client_ID,OrgValue,AD_Org_ID,Value,Companyname,Name,Description,ShortDescription,TaxID,GroupValue,C_BP_Group_ID,C_BPartner_Location_ID,Address1,Address2,Address3,Address4,Postal,Postal_Add,City,RegionName,C_Region_ID,CountryCode,C_Country_ID,AD_User_ID,Title,Firstname,Lastname,ContactDescription,IsDefaultContact,Comments,Phone,Phone2,Fax,Birthday,EMail,BPContactGreeting,C_Greeting_ID,IsCustomer,IsEmployee,IsVendor,IsShipTo,IsShipToDefault,IsBillTo,IsBillToDefault,IsBillToContact_Default,IsShipToContact_Default,AD_Language,Name2,Name3,IsSEPASigned,Pharmaproductpermlaw52,IsPharmaciePermission,SwiftCode,IBAN,C_BP_BankAccount_ID,FirstSale,InvoiceSchedule,C_InvoiceSchedule_ID,PaymentRule,PaymentRulePO,PaymentTerm,PO_PaymentTerm_ID,Processing,Processed,DUNS,NAICS,IsActive,Password,R_InterestArea_ID,InterestAreaName FROM I_BPartner WHERE 1=1  AND 
 /* security-client */ I_BPartner.AD_Client_ID IN (0,1000000)
 /* security-record */ AND I_BPartner.I_BPartner_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 533 AND AD_User_ID <> 100 AND IsActive = 'Y' ) ORDER BY I_BPartner_ID

org.postgresql.util.PSQLException: ERROR: column "c_invoiceschedule_id" does not exist
  Position: 758
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1418)
	at org.adempiere.sql.impl.CPreparedStatementProxy.executeQuery(CPreparedStatementProxy.java:122)
	at org.compiere.model.GridTable$Loader.open(GridTable.java:3496)
	at org.compiere.model.GridTable.open(GridTable.java:684)
	at org.compiere.model.GridTable.dataRefreshAll(GridTable.java:2944)
	at org.compiere.model.GridTab.dataRefreshAll(GridTab.java:1237)
	at org.compiere.model.GridTab.dataRefreshAll(GridTab.java:1209)
	at org.compiere.apps.APanel.cmd_refresh(APanel.java:2444)
	at org.compiere.apps.APanel.actionPerformed(APanel.java:1978)
	at org.compiere.apps.AppsAction.actionPerformed(AppsAction.java:455)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
### What is the expected or desired behavior?
shall see data

**Comment by metas-lc** [comment]
IT
open Import BPartner window -> i can see data OK
