### ISSUE TITLE
Automatic Discount for Group Products

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3149]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to define and use Discounts for a Group-discount-product in metasfresh sales orders.
#### Which are the steps to reproduce?
Try in Sales order and Discount Schema and see what happens.
### What is the expected or desired behavior?
- User defines a discount schema and adds the discount for a discount product which shall be used in a discount group
- The user creates a group in sales orderlines and selects the discount product.

What shall happen:
- the discount product is added as line - happens already
- the compensation type is set to discount - happens already
- the compensation amount type is set to percent - happens already
- the compensation percentage is set to discount defined in discount schema - new
- the origin discount field is readonly for these discount group lines - new

![image](https://user-images.githubusercontent.com/13365687/33666486-693900ea-da9a-11e7-9c77-7a54d2aa931b.png)

**Comment by metasnw** [comment]
I tried it quickly here:
https://w101.metasfresh.com:8443/window/143/1000219

the discount is going into the wrong column in my opinion
![image](https://user-images.githubusercontent.com/16079655/33761838-c1d7f49c-dc0a-11e7-911e-993ff14affae.png)

**Comment by metasnw** [comment]
tested and got:
```
Error: java.lang.NullPointerException...
Server error
java.lang.NullPointerException
```

**Comment by teosarca** [comment]
fixed, NPE was:
```
2017-12-08 12:03:21.590 ERROR 30997 --- [http-nio-8080-exec-11] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.adempiere.exceptions.AdempiereException: java.lang.NullPointerException] with root cause
 
java.lang.NullPointerException: null
        at de.metas.contracts.interceptor.C_OrderLine.retrieveFirstFlatrateConditionsIdForCompensationGroup(C_OrderLine.java:78)
        at de.metas.contracts.interceptor.C_OrderLine.setSameFlatrateConditionsForWholeCompensationGroupWhenGroupIsCreated(C_OrderLine.java:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by metasnw** [comment]
testing together with #3150
