### ISSUE TITLE
console error when copying MDocType

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3208]
### Is this a bug or feature request?
Bug
### What is the current behavior?

when copying a sales order (probably any document), in the console you get something like:

```
2017-12-13 10:42:30.309  WARN 25261 --- [rbeiten-1000134] o.a.ad.dao.cache.impl.ModelCacheService  : Cannot create a copy of MDocType[1000030-Standardauftrag,DocNoSequence_ID=545479]. Returning null.
 
org.adempiere.exceptions.AdempiereException: Cannot create a new instance of MDocType[1000030-Standardauftrag,DocNoSequence_ID=545479]
    at org.compiere.model.PO.newInstance(PO.java:5153)
    at org.compiere.model.PO.copy(PO.java:5166)
    at org.adempiere.ad.dao.cache.impl.ModelCacheService.copyPO(ModelCacheService.java:299)
    at org.adempiere.ad.dao.cache.impl.ModelCacheService.retrieveObject(ModelCacheService.java:269)
    at org.adempiere.ad.persistence.TableModelLoader.getPO(TableModelLoader.java:110)
    at org.adempiere.ad.persistence.TableModelLoader.getPO(TableModelLoader.java:89)
    at org.adempiere.model.POWrapper.create(POWrapper.java:189)
    at org.adempiere.model.POWrapper.create(POWrapper.java:166)
    at org.adempiere.model.InterfaceWrapperHelper.create(InterfaceWrapperHelper.java:297)
    at de.metas.document.engine.impl.AbstractDocumentBL.getDocTypeOrNull(AbstractDocumentBL.java:388)
    at de.metas.document.spi.CounterDocumentHandlerAdapter.retrieveCounterDocTypeOrNull(CounterDocumentHandlerAdapter.java:85)
    at de.metas.document.spi.CounterDocumentHandlerAdapter.isCreateCounterDocument(CounterDocumentHandlerAdapter.java:61)
    at de.metas.document.impl.CounterDocBL.isCreateCounterDocument(CounterDocBL.java:52)
    at de.metas.document.model.interceptor.CounterDocHandlerInterceptor.onDocValidate(CounterDocHandlerInterceptor.java:85)
    at org.adempiere.ad.modelvalidator.ModelInterceptor2ModelValidatorWrapper.docValidate(ModelInterceptor2ModelValidatorWrapper.java:131)
    at org.compiere.model.ModelValidationEngine.fireDocValidate(ModelValidationEngine.java:1168)
    at org.compiere.model.ModelValidationEngine.fireDocValidate0(ModelValidationEngine.java:1138)
    at org.compiere.model.ModelValidationEngine.lambda$fireDocValidate$1(ModelValidationEngine.java:1124)
    at org.compiere.model.ModelValidationEngine$1.run(ModelValidationEngine.java:790)
    at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
    at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
    at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:771)
    at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:683)
    at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:591)
    at org.compiere.model.ModelValidationEngine.executeInTrx(ModelValidationEngine.java:785)
    at org.compiere.model.ModelValidationEngine.fireDocValidate(ModelValidationEngine.java:1124)
    at org.compiere.model.MOrder.completeIt(MOrder.java:1932)
    at de.metas.document.engine.impl.DocumentEngine.completeIt(DocumentEngine.java:438)
    at de.metas.document.engine.impl.DocumentEngine.processIt0(DocumentEngine.java:275)
    at de.metas.document.engine.impl.DocumentEngine.processIt(DocumentEngine.java:236)
    at de.metas.document.engine.impl.DocumentEngine.processIt(DocumentEngine.java:207)
    at de.metas.document.engine.impl.AbstractDocumentBL.processIt(AbstractDocumentBL.java:100)
    at org.compiere.model.MOrder.processIt(MOrder.java:1233)
    at org.compiere.wf.MWFActivity.performWork(MWFActivity.java:988)
    at org.compiere.wf.MWFActivity.run(MWFActivity.java:870)
    at org.compiere.wf.MWFProcess.startNext(MWFProcess.java:379)
    at org.compiere.wf.MWFProcess.checkActivities(MWFProcess.java:289)
    at org.compiere.wf.MWFActivity.setWFState(MWFActivity.java:298)
    at org.compiere.wf.MWFActivity.run(MWFActivity.java:890)
    at org.compiere.wf.MWFProcess.startNext(MWFProcess.java:379)
    at org.compiere.wf.MWFProcess.checkActivities(MWFProcess.java:289)
    at org.compiere.wf.MWFActivity.setWFState(MWFActivity.java:298)
    at org.compiere.wf.MWFActivity.run(MWFActivity.java:890)
    at org.compiere.wf.MWFProcess.startWork(MWFProcess.java:511)
    at org.compiere.wf.MWorkflow$1.call(MWorkflow.java:684)
    at org.compiere.wf.MWorkflow$1.call(MWorkflow.java:677)
    at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)
    at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:771)
    at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:683)
    at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:584)
    at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:515)
    at org.compiere.wf.MWorkflow.start(MWorkflow.java:676)
    at org.compiere.wf.MWorkflow.startWait(MWorkflow.java:710)
    at de.metas.process.ProcessExecutor.startWorkflow(ProcessExecutor.java:434)
    at de.metas.process.ProcessExecutor.access$600(ProcessExecutor.java:49)
    at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:218)
    at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
    at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
    at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:771)
    at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:683)
    at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:584)
    at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:515)
    at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:500)
    at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:285)
    at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:170)
    at de.metas.process.ProcessExecutor.lambda$executeAsync$0(ProcessExecutor.java:118)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException: null
    at sun.reflect.GeneratedConstructorAccessor83.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.compiere.model.PO.newInstance(PO.java:5149)
    ... 66 common frames omitted
Caused by: java.lang.NullPointerException: null
    at org.compiere.model.PO.get_ColumnIndex(PO.java:1409)
    at org.compiere.model.PO.set_Value(PO.java:938)
    at org.compiere.model.X_C_DocType.setDocumentCopies(X_C_DocType.java:571)
    at org.compiere.model.MDocType.<init>(MDocType.java:126)
    ... 70 common frames omitted
```

**Comment by metas-lc** [comment]
IT
swing: copy and copy with details works fine, no errors in console
webui: copy works fine, no errors in console 
OK
