### ISSUE TITLE
Error creating movement from DDOrder

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3350]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When trying to create a movement from a DDOrder via "Bereitstellung (POS)" or also via webui, you get this error: 
![image](https://user-images.githubusercontent.com/1264789/35102421-37c1d5c4-fc63-11e7-95ba-da68c424b27b.png)

and this stacktrace (for swing):
```
Assumption failure: ThreadInherited transaction shall be set at this point
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.adempiere.util.Check.mkEx(Check.java:109)
        at org.adempiere.util.Check.throwOrLogEx(Check.java:120)
        at org.adempiere.util.Check.assume(Check.java:163)
        at org.adempiere.util.Check.assume(Check.java:147)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.assertThreadInheritedTrxExists(AbstractTrxManager.java:1174)
        at de.metas.handlingunits.ddorder.api.impl.DDOrderLinesAllocator.process(DDOrderLinesAllocator.java:222)
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
        at de.metas.handlingunits.ddorder.api.impl.DDOrderLinesAllocator.process(DDOrderLinesAllocator.java:199)
        at de.metas.handlingunits.client.terminal.ddorder.api.impl.DDOrderFiltering.processDDOrderLines(DDOrderFiltering.java:346)
        at de.metas.handlingunits.client.terminal.ddorder.model.DDOrderHUSelectModel.processRows(DDOrderHUSelectModel.java:334)
        at de.metas.handlingunits.client.terminal.select.model.AbstractHUSelectModel.doProcessSelectedLines0(AbstractHUSelectModel.java:605)
        at de.metas.handlingunits.client.terminal.select.model.AbstractHUSelectModel.doProcessSelectedLines(AbstractHUSelectModel.java:553)
        at de.metas.handlingunits.client.terminal.ddorder.view.DDOrderHUSelectPanel.doProcessSelectedLines(DDOrderHUSelectPanel.java:88)
        at de.metas.handlingunits.client.terminal.ddorder.view.DDOrderHUSelectPanel.doProcessSelectedLines(DDOrderHUSelectPanel.java:42)
        at de.metas.handlingunits.client.terminal.select.view.AbstractHUSelectPanel$1.propertyChange0(AbstractHUSelectPanel.java:135)
        at de.metas.adempiere.beans.impl.UILoadingPropertyChangeListener$1.run(UILoadingPropertyChangeListener.java:67)
        at de.metas.adempiere.form.swing.SwingClientUIInvoker$1.run(SwingClientUIInvoker.java:107)
        at de.metas.adempiere.form.AbstractClientUIInvoker.invoke(AbstractClientUIInvoker.java:103)
        at de.metas.adempiere.form.AbstractClientUIInvoker.invoke(AbstractClientUIInvoker.java:68)
[...]
```

**Comment by metas-ts** [comment]
fixed in branches `master` and `2018-06`

**Comment by metas-dh** [comment]
Results of IT1
tested in customer db

* error not happening anymore: OK
* movement is created, HU moved to destination warehouse: OK
