### ISSUE TITLE
Can't credit memo a partially paid invoice

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#3402]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Can't credit memo partially paid invoices.
```

org.adempiere.exceptions.AdempiereException: Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
Bitte leiten Sie diese Meldung an metas weiter:

Assumption failure: MInvoice[1000058-170248,GrandTotal=2.14] has GrandTotal=0.62
	at sun.reflect.GeneratedConstructorAccessor2046.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.adempiere.util.Check.mkEx(Check.java:108)
	at org.adempiere.util.Check.throwOrLogEx(Check.java:119)
	at org.adempiere.util.Check.assume(Check.java:162)
	at org.adempiere.util.Check.assume(Check.java:146)
	at org.adempiere.invoice.service.impl.CreditMemoInvoiceCopyHandler.completeAndAllocateCreditMemo(CreditMemoInvoiceCopyHandler.java:289)
	at org.adempiere.invoice.service.impl.CreditMemoInvoiceCopyHandler.copyValues(CreditMemoInvoiceCopyHandler.java:100)
	at org.adempiere.invoice.service.impl.CreditMemoInvoiceCopyHandler.copyValues(CreditMemoInvoiceCopyHandler.java:1)
	at org.adempiere.invoice.service.impl.AbstractInvoiceBL.copyFrom(AbstractInvoiceBL.java:319)
	at org.adempiere.invoice.service.impl.AbstractInvoiceBL.creditInvoice(AbstractInvoiceBL.java:149)
	at org.adempiere.invoice.process.CreateCreditMemoFromInvoice.doIt(CreateCreditMemoFromInvoice.java:76)
```
#### Which are the steps to reproduce?
* Create a sales invoice
* Pay it partially
* Then try to credit memo .
![image](https://user-images.githubusercontent.com/15378036/35556598-4e9bb1d8-05ab-11e8-90db-bb881d4791ec.png)
### What is the expected or desired behavior?
* Should be able to credit memo partially paid invoices

**Comment by cristinamghita** [comment]
## Dev test
* Create a sales invoice
* Pay it partially
* Then try to credit memo .
![image](https://user-images.githubusercontent.com/15378036/35556598-4e9bb1d8-05ab-11e8-90db-bb881d4791ec.png)
* Invoice was credited with the missing amount and now is fully paid **OK**

**Comment by metas-lc** [comment]
IT
1. created invoice. Made credit memo
=> worked. Credit memo created and invoice is paid OK
2. create invoice. Partially pay it.
=> invoice is not paid OK
3. Create credit memo
=> worked. Credit memo created and invoice is paid OK
4. create invoice. Pay it
=> invoice is paid OK
5. Create credit memo
=> You cannot create it because the invoice is already paid. OK
