### ISSUE TITLE
Migitate "PO not handled: Document{tableName=M_InOut.." and similar warnings flooding the log

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3455]
### Is this a bug or feature request?
FR
### What is the current behavior?

the following shows up in the log now and then, when users work with metasfresh

```
2018-02-07 15:23:40.343 ERROR 31309 [ 0:0:0:0:0:0:0:1][ SuperUser] --- [http-nio-8282-exec-5] o.a.model.InterfaceWrapperHelper         : PO not handled: Document{tableName=M_InOut, id=1763254, windowNo=100, writable=true, valid=Valid, va
lidOnCheckout=Valid, saveStatus=DocumentSaveStatus{saved=true, hasChangesToBeSaved=false, error=false}, saveStatusOnCheckout=DocumentSaveStatus{saved=true, hasChangesToBeSaved=false, error=false}}(class=class com.sun.proxy.$Proxy246). Ig
nored.

org.adempiere.exceptions.AdempiereException: PO not handled: Document{tableName=M_InOut, id=1763254, windowNo=100, writable=true, valid=Valid, validOnCheckout=Valid, saveStatus=DocumentSaveStatus{saved=true, hasChangesToBeSaved=false, er
ror=false}, saveStatusOnCheckout=DocumentSaveStatus{saved=true, hasChangesToBeSaved=false, error=false}}(class=class com.sun.proxy.$Proxy246). Ignored.
        at org.adempiere.model.InterfaceWrapperHelper.save(InterfaceWrapperHelper.java:549)
        at de.metas.handlingunits.empties.EmptiesInOutLinesProducer.createDocumentLine(EmptiesInOutLinesProducer.java:121)
        at de.metas.handlingunits.impl.AbstractPackingMaterialDocumentLinesBuilder.createUpdateDeleteDocumentLineAndUpdateSources(AbstractPackingMaterialDocumentLinesBuilder.java:218)
        at de.metas.handlingunits.impl.AbstractPackingMaterialDocumentLinesBuilder.create(AbstractPackingMaterialDocumentLinesBuilder.java:183)
        at de.metas.handlingunits.empties.EmptiesInOutLinesProducer.create(EmptiesInOutLinesProducer.java:61)
        at de.metas.ui.web.quickinput.inout.EmptiesQuickInputProcessor.process(EmptiesQuickInputProcessor.java:44)
        at de.metas.ui.web.quickinput.QuickInput.complete(QuickInput.java:250)
        at de.metas.ui.web.quickinput.WindowQuickInputRestController.lambda$null$9(WindowQuickInputRestController.java:309)
        at de.metas.ui.web.quickinput.WindowQuickInputRestController.lambda$forQuickInputWritable$3(WindowQuickInputRestController.java:212)
        at de.metas.ui.web.window.model.DocumentCollection.forRootDocumentWritable(DocumentCollection.java:288)
        at de.metas.ui.web.quickinput.WindowQuickInputRestController.forQuickInputWritable(WindowQuickInputRestController.java:205)
        at de.metas.ui.web.quickinput.WindowQuickInputRestController.lambda$complete$10(WindowQuickInputRestController.java:308)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$4.call(TrxCallableWrappers.java:193)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:771)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:683)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:584)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:515)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:492)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:469)
        at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$0(Execution.java:194)
        at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)
        at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)
        at de.metas.ui.web.window.controller.Execution.callInNewExecution(Execution.java:88)
        at de.metas.ui.web.quickinput.WindowQuickInputRestController.complete(WindowQuickInputRestController.java:307)
```

**Comment by metas-rc** [comment]
Nothing to IT. Moving to done.
