### ISSUE TITLE
Workpackage with error for Update Invalid Shipment Schedules

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#3520]
### Is this a bug or feature request?
bug
### What is the current behavior?
de.metas.inoutcandidate.async.UpdateInvalidShipmentSchedulesWorkpackageProcessor has error on w101
#### Which are the steps to reproduce?
note this is happening only on w101
try to reactivate an order and then complete it. A de.metas.inoutcandidate.async.UpdateInvalidShipmentSchedulesWorkpackageProcessor will be created
=> 
```
org.adempiere.exceptions.AdempiereException: NullPointerException
Additional parameters:
 I_C_Queue_WorkPackage: X_C_Queue_WorkPackage[C_Queue_WorkPackage_ID=1184974, trxName=null]
 IQueueProcessor: ThreadPoolQueueProcessor{name=M_ShipmentSchedule_Update, executor=BlockingThreadPoolExecutor [getPoolSize()=1]}
 trxName: <<ThreadInherited>>
	at org.adempiere.exceptions.AdempiereException.wrapIfNeeded(AdempiereException.java:87)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.invokeProcessorAndHandleException(WorkpackageProcessorTask.java:302)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.processWorkpackage(WorkpackageProcessorTask.java:290)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.access$000(WorkpackageProcessorTask.java:90)
	at de.metas.async.processor.impl.WorkpackageProcessorTask$1.run(WorkpackageProcessorTask.java:173)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:103)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:93)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:771)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:683)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:591)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.run(WorkpackageProcessorTask.java:163)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at Thread.run(Thread.java:748)
Caused by: NullPointerException
	at de.metas.contracts.inoutcandidate.ShipmentScheduleSubscriptionReferenceProvider.provideFor(ShipmentScheduleSubscriptionReferenceProvider.java:56)
	at de.metas.inoutcandidate.spi.ShipmentScheduleReferencedLineFactory.createFor(ShipmentScheduleReferencedLineFactory.java:48)
	at de.metas.inoutcandidate.api.impl.ShipmentScheduleBL.updateWarehouseId(ShipmentScheduleBL.java:827)
	at de.metas.inoutcandidate.api.impl.ShipmentScheduleBL.updateSchedules(ShipmentScheduleBL.java:147)
	at de.metas.inoutcandidate.api.impl.ShipmentScheduleUpdater.updateShipmentSchedule(ShipmentScheduleUpdater.java:89)
	at de.metas.inoutcandidate.async.UpdateInvalidShipmentSchedulesWorkpackageProcessor.processWorkPackage(UpdateInvalidShipmentSchedulesWorkpackageProcessor.java:74)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.invokeProcessorAndHandleException(WorkpackageProcessorTask.java:298)
	... 14 more
  
```
### What is the expected or desired behavior?
no errors

**Comment by metas-ts** [comment]
there was nothing to clean up M_ShipmentSchedules when there C_SubscriptionProgress were removed.
therefore, we have 134 "dangling" shipment schedus on w101

**Comment by metas-rc** [comment]
Results of IT

Tested on w101 (webui + swing)

After I complete an order, the shipment schedule is created but it is not updated. I found this in async: 

org.adempiere.exceptions.AdempiereException: Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
Bitte leiten Sie diese Meldung an metas weiter:

```
Error: Unable to load the referenced C_SubscriptionProgress for M_ShipmentSchedule_ID=1000080; M_ShipmentSchedule.Record_ID=1000129
Additional parameters:
 I_C_Queue_WorkPackage: X_C_Queue_WorkPackage[C_Queue_WorkPackage_ID=1185698, trxName=null]
 IQueueProcessor: ThreadPoolQueueProcessor{name=M_ShipmentSchedule_Update, executor=BlockingThreadPoolExecutor [getPoolSize()=1]}
 trxName: <<ThreadInherited>>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at reflect.Constructor.newInstance(Constructor.java:423)
	at org.adempiere.util.Check.mkEx(Check.java:108)
	at org.adempiere.util.Check.throwOrLogEx(Check.java:119)
	at org.adempiere.util.Check.errorIf(Check.java:455)
	at org.adempiere.util.Check.errorIf(Check.java:436)
	at de.metas.contracts.inoutcandidate.ShipmentScheduleSubscriptionReferenceProvider.provideFor(ShipmentScheduleSubscriptionReferenceProvider.java:55)
	at de.metas.inoutcandidate.spi.ShipmentScheduleReferencedLineFactory.createFor(ShipmentScheduleReferencedLineFactory.java:48)
	at de.metas.inoutcandidate.api.impl.ShipmentScheduleBL.updateWarehouseId(ShipmentScheduleBL.java:843)
	at de.metas.inoutcandidate.api.impl.ShipmentScheduleBL.updateSchedules(ShipmentScheduleBL.java:172)
	at de.metas.inoutcandidate.api.impl.ShipmentScheduleUpdater.updateShipmentSchedule(ShipmentScheduleUpdater.java:92)
	at de.metas.inoutcandidate.async.UpdateInvalidShipmentSchedulesWorkpackageProcessor.processWorkPackage(UpdateInvalidShipmentSchedulesWorkpackageProcessor.java:74)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.invokeProcessorAndHandleException(WorkpackageProcessorTask.java:298)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.processWorkpackage(WorkpackageProcessorTask.java:290)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.access$000(WorkpackageProcessorTask.java:90)
	at de.metas.async.processor.impl.WorkpackageProcessorTask$1.run(WorkpackageProcessorTask.java:173)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:103)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:93)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:771)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:683)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:591)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.run(WorkpackageProcessorTask.java:163)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at Thread.run(Thread.java:748)
```

Can you, please, check if this is related and let me know if it's not, then I'll create another task.

Note that it is working well on mf15cloudit.

**Comment by metas-lc** [comment]
IT
complete an order => the shipment schedule is created and updated OK
(checked with several orders, also created inouts)
also complete - reactivate - complete order => shipment schedules were updated OK
