### ISSUE TITLE
Error in console when zoom into in sales oder

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3525]
### Is this a bug or feature request?
Bug
### What is the current behavior?
An error appears in console when you use zoom into in sales order sometimes (Swing).
#### Which are the steps to reproduce?
1. In Swing, create a sales order, set a flatrate term in orderline
2. Complete and use zoom into: ERROR: column pc.c_orderlinepo_id does not exist

```
2018-02-19 10:49:41.113  WARN 29182 --- [WT-EventQueue-0] org.adempiere.model.ZoomInfoFactory      : Failed retrieving zoom infos from RelationTypeZoomProvider{zoomInfoId=relationType-540198, internalName=relationType-540198, directed=false, source=RelationTypeZoomProvider.ZoomProviderDestination(adReferenceId=540666, tableRefInfo=TableRefInfo{name=C_Order_SOTrx_Source, tableName=C_Order, keyColumn=C_Order_ID, valueDisplayed=false, whereClause=IsSOTrx = 'Y', translated=false, zoomWindow=143, zoomWindowPO=181, overrideZoomWindow=143, autoComplete=false}, roleDisplayName=null, tableRecordIdTarget=false), target=RelationTypeZoomProvider.ZoomProviderDestination(adReferenceId=540768, tableRefInfo=TableRefInfo{name=C_Order (PO) Target for C_Order (SO), tableName=C_Order, keyColumn=C_Order_ID, displayColumn=DocumentNo, valueDisplayed=false, whereClause=exists (  select 1 from C_Order po  join C_OrderLine pol on po.C_Order_ID = pol.C_Order_ID  join C_PurchaseCandidate pc on pol.C_OrderLine_ID = pc.C_OrderLinePO_ID  join C_Order so on pc.C_OrderSO_ID = so.C_Order_ID  where so.C_Order_ID = @C_Order_ID/-1@ and so.IsSOTrx = 'Y' and po.C_Order_ID = C_Order.C_Order_ID ), translated=false, zoomWindow=143, zoomWindowPO=181, overrideZoomWindow=181, autoComplete=false}, roleDisplayName=null, tableRecordIdTarget=false), isReferenceTarget=false} for POZoomSource{po=C_Order[ID=1000001-DocumentNo=0002,IsSOTrx=true,C_DocType_ID=1000030,GrandTotal=0.65], AD_Window_ID=143}. Skipped.

org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: ERROR: column pc.c_orderlinepo_id does not exist
  Hint: Perhaps you meant to reference the column "pc.c_orderlineso_id".
  Position: 181
	SQL: SELECT COUNT(*)  FROM C_Order WHERE exists (  select 1 from C_Order po  join C_OrderLine pol on po.C_Order_ID = pol.C_Order_ID  join C_PurchaseCandidate pc on pol.C_OrderLine_ID = pc.C_OrderLinePO_ID  join C_Order so on pc.C_OrderSO_ID = so.C_Order_ID  where so.C_Order_ID = 1000001 and so.IsSOTrx = 'Y' and po.C_Order_ID = C_Order.C_Order_ID )
	at org.compiere.util.DB.getSQLValueEx(DB.java:1221)
	at org.adempiere.model.RelationTypeZoomProvider.updateRecordsCountAndZoomValue(RelationTypeZoomProvider.java:380)
	at org.adempiere.model.RelationTypeZoomProvider.retrieveZoomInfos(RelationTypeZoomProvider.java:175)
	at org.adempiere.model.ZoomInfoFactory.lambda$streamZoomInfos$0(ZoomInfoFactory.java:369)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.adempiere.model.ZoomInfoFactory.retrieveZoomInfos(ZoomInfoFactory.java:342)
	at org.compiere.apps.AZoomAcross.retrieveZoomTargets(AZoomAcross.java:116)
	at org.compiere.apps.AZoomAcross.<init>(AZoomAcross.java:85)
	at org.compiere.apps.AZoomAcross.<init>(AZoomAcross.java:65)
	at org.compiere.apps.APanel.cmd_zoomAcross(APanel.java:2490)
	at org.compiere.apps.APanel.actionPerformed(APanel.java:2060)
	at org.compiere.apps.AppsAction.actionPerformed(AppsAction.java:455)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: org.postgresql.util.PSQLException: ERROR: column pc.c_orderlinepo_id does not exist
  Hint: Perhaps you meant to reference the column "pc.c_orderlineso_id".
  Position: 181
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1418)
	at org.adempiere.sql.impl.CPreparedStatementProxy.executeQuery(CPreparedStatementProxy.java:123)
	at org.compiere.util.DB.getSQLValueEx(DB.java:1213)
	... 54 common frames omitted
```

Usually happens the 1st & 2nd time when using zoom into.
### What is the expected or desired behavior?
No error in console.

**Comment by teosarca** [comment]
issue introduced by https://github.com/metasfresh/metasfresh/issues/3437

@metas-ts  pls take a look

**Comment by metas-ts** [comment]
CPed `the fix to `release, see https://github.com/metasfresh/metasfresh/issues/3437#issuecomment-367089643

**Comment by teosarca** [comment]
moving this task to test because the task where the problem was solved is also in Test.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* error in console not happening anymore: OK
