### ISSUE TITLE
AD_Element_trl problem with autocomplete fields

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#3571]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* This error appears in console when adding fields with autocomplete
```
Caused by: org.postgresql.util.PSQLException: ERROR: missing FROM-clause entry for table "ad_element_trl"
  Position: 249
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
    at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
    at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)
    at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1418)
    at org.adempiere.sql.impl.CPreparedStatementProxy.executeQuery(CPreparedStatementProxy.java:123)
    at org.compiere.apps.search.FieldAutoCompleter.updateListData(FieldAutoCompleter.java:457)
    ... 19 more
```
#### Which are the steps to reproduce?
* Add a field with autocomplete. ( Talked with Teo and think this is the way, but will have to reproduce it to make sure) .
### What is the expected or desired behavior?
* No error shall occur.

**Comment by metas-rc** [comment]
Update: 
I managed to reproduce the error. It is happening when: 
* You add a new column
* You start writing the AD_Element's name in it

**Comment by metas-rc** [comment]
Update: caused by : org.compiere.grid.ed.VLookupAutoCompleter.createAutoCompleterValidationRule(MTable, MLookupInfo), 

```
// Case: translated column (FRESH-220)
					else if (c.isTranslated() && !isBaseLanguage)
					{
						// NOTE: we need to use the fully qualified name because else we will get sql errors like "ERROR: column reference "name" is ambiguous"
						searchColumnsSQL.add(tableName + "_Trl." + c.getColumnName());
					}
``` 
together with the select string, which does not contain a join of the AD_Element_Trl. 
I will have to debug the way the SELECT sql is created and add the join.

**Comment by metas-lc** [comment]
IT
logged in as sysadmin, opened a table (from table and columns window)
new column, start writing on element field (which is a search autocomplete field)
=> no errors in console OK
