### ISSUE TITLE
Compensation group interceptor fails to start when elasticsearch is enabled

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3671]
### Is this a bug or feature request?
bug
caused by https://github.com/metasfresh/metasfresh-webui-api/issues/853

### What is the current behavior?
When starting serverRoot you get in console:
```
1. org.adempiere.ad.modelvalidator.ModelInterceptorInitException: org.adempiere.model.validator.AdempiereBaseValidator: org.adempiere.exceptions.AdempiereException: There are no lookup display columns defined for C_CompensationGroup_SchemaLine table.
 HINT: please go to Table and columns, and set IsIdentifier=Y on columns which you want to be part of record's display string. (global)
	at org.compiere.model.ModelValidationEngine.addModelInterceptorInitError(ModelValidationEngine.java:277)
	at org.compiere.model.ModelValidationEngine.loadModuleActivatorClass(ModelValidationEngine.java:419)
	at org.compiere.model.ModelValidationEngine.init(ModelValidationEngine.java:216)
	at org.compiere.model.ModelValidationEngine.get(ModelValidationEngine.java:114)
	at org.compiere.Adempiere.startupEnvironment(Adempiere.java:767)
	at org.compiere.Adempiere.startup(Adempiere.java:726)
	at de.metas.ServerBoot.adempiere(ServerBoot.java:161)
	at de.metas.ServerBoot$$EnhancerBySpringCGLIB$$6b8572e6.CGLIB$adempiere$1(<generated>)
	at de.metas.ServerBoot$$EnhancerBySpringCGLIB$$6b8572e6$$FastClassBySpringCGLIB$$9616b1cc.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
	at de.metas.ServerBoot$$EnhancerBySpringCGLIB$$6b8572e6.adempiere(<generated>)
	at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.__refresh(AbstractApplicationContext.java:542)
	at org.springframework.context.support.AbstractApplicationContext.jrLockAndRefresh(AbstractApplicationContext.java)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
	at de.metas.ServerBoot.main(ServerBoot.java:99)
Caused by: org.adempiere.exceptions.AdempiereException: There are no lookup display columns defined for C_CompensationGroup_SchemaLine table.
 HINT: please go to Table and columns, and set IsIdentifier=Y on columns which you want to be part of record's display string.
	at org.adempiere.ad.service.impl.LookupDAO.retrieveLookupDisplayInfo(LookupDAO.java:928)
	at org.compiere.model.MLookupFactory.buildLookupInfo(MLookupFactory.java:461)
	at org.compiere.model.MLookupFactory.lambda$0(MLookupFactory.java:455)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5065)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060)
	at org.compiere.util.CCache.get(CCache.java:481)
	at org.compiere.util.CCache.getOrLoad(CCache.java:515)
	at org.compiere.model.MLookupFactory.getLookupInfo(MLookupFactory.java:455)
	at org.compiere.model.MLookupFactory.getLookup_TableDir(MLookupFactory.java:446)
	at org.compiere.model.MLookupFactory.getLookupInfo(MLookupFactory.java:221)
	at org.compiere.model.POInfoColumn.getLookupInfo(POInfoColumn.java:412)
	at org.compiere.model.POInfoColumn.getReferencedTableNameOrNull(POInfoColumn.java:392)
	at org.compiere.model.POInfo.getReferencedTableNameOrNull(POInfo.java:998)
	at de.metas.elasticsearch.denormalizers.impl.ESPOModelDenormalizer$ESPOModelDenormalizerBuilder.generateColumn(ESPOModelDenormalizer.java:374)
	at de.metas.elasticsearch.denormalizers.impl.ESPOModelDenormalizer$ESPOModelDenormalizerBuilder.build(ESPOModelDenormalizer.java:295)
	at de.metas.elasticsearch.denormalizers.impl.ESDenormalizerFactory.createDefaultModelDenormalizer(ESDenormalizerFactory.java:209)
	at de.metas.elasticsearch.denormalizers.impl.ESDenormalizerFactory.lambda$0(ESDenormalizerFactory.java:202)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5065)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060)
	at org.compiere.util.CCache.get(CCache.java:481)
	at org.compiere.util.CCache.getOrLoad(CCache.java:515)
	at de.metas.elasticsearch.denormalizers.impl.ESDenormalizerFactory.getModelDenormalizer(ESDenormalizerFactory.java:202)
	at de.metas.elasticsearch.indexer.impl.ESModelIndexerBuilder.getModelDenormalizer(ESModelIndexerBuilder.java:98)
	at de.metas.elasticsearch.indexer.impl.ESModelIndexer.<init>(ESModelIndexer.java:87)
	at de.metas.elasticsearch.indexer.impl.ESModelIndexerBuilder.build(ESModelIndexerBuilder.java:69)
	at de.metas.elasticsearch.indexer.impl.ESModelIndexersRegistry.addModelIndexer(ESModelIndexersRegistry.java:99)
	at de.metas.elasticsearch.ESServer.installConfig(ESServer.java:44)
	at de.metas.elasticsearch.impl.ESSystem.installConfig(ESSystem.java:96)
	at de.metas.elasticsearch.config.ESModelIndexerConfigBuilder.buildAndInstall(ESModelIndexerConfigBuilder.java:64)
	at de.metas.order.model.interceptor.OrderModuleInterceptor.registerInterceptors(OrderModuleInterceptor.java:52)
	at org.adempiere.ad.modelvalidator.AbstractModuleInterceptor.onInit(AbstractModuleInterceptor.java:70)
	at org.adempiere.ad.modelvalidator.AbstractModelInterceptor.initialize(AbstractModelInterceptor.java:44)
	at org.adempiere.ad.modelvalidator.ModelInterceptor2ModelValidatorWrapper.initialize(ModelInterceptor2ModelValidatorWrapper.java:110)
	at org.compiere.model.ModelValidationEngine.initialize(ModelValidationEngine.java:484)
	at org.compiere.model.ModelValidationEngine.addModelValidator(ModelValidationEngine.java:1432)
	at org.adempiere.model.validator.AdempiereBaseValidator.registerInterceptors(AdempiereBaseValidator.java:173)
	at org.adempiere.ad.modelvalidator.AbstractModuleInterceptor.onInit(AbstractModuleInterceptor.java:70)
	at org.adempiere.ad.modelvalidator.AbstractModelInterceptor.initialize(AbstractModelInterceptor.java:44)
	at org.adempiere.ad.modelvalidator.ModelInterceptor2ModelValidatorWrapper.initialize(ModelInterceptor2ModelValidatorWrapper.java:110)
	at org.compiere.model.ModelValidationEngine.initialize(ModelValidationEngine.java:484)
	at org.compiere.model.ModelValidationEngine.addModelValidator(ModelValidationEngine.java:1432)
	at org.compiere.model.ModelValidationEngine.loadModuleActivatorClass(ModelValidationEngine.java:390)
	... 64 more
```

**Comment by teosarca** [comment]
note to IT: there is nothing to test

**Comment by metas-ts** [comment]
:cherries:  to `release`

**Comment by metas-lc** [comment]
closing, since there is nothing to test
