### ISSUE TITLE
Setting a different invoice bpartner causes error

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3729]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you select a different invoice bpartner in order, you get an error.
#### Which are the steps to reproduce?
1. Create a bpartner relation, for bpartner and related bpartner B, check invoice address
2. Create a sales order for bpartner A
3. Set bpartner B as invoice bpartner:

```
Error: ERROR: syntax error at...
Server error
ERROR: syntax error at or near "," Position: 186
```
### What is the expected or desired behavior?
Should work.

**Comment by teosarca** [comment]
this looks like a frontend issue. where did u get that error?

**Comment by metas-dh** [comment]
in sales order, when i try to set an invoice partner != business partner

**Comment by teosarca** [comment]
yes, but did u got the error in browser console?

**Comment by metas-dh** [comment]
![2018-03-22 15_06_23-metasfresh](https://user-images.githubusercontent.com/18696715/37775354-07f3d08e-2de3-11e8-9f29-6ff1919cd993.png)

**Comment by teosarca** [comment]
pls always paste the stack trace when available, i.e.
![image](https://user-images.githubusercontent.com/1244701/37818204-08aa694e-2e82-11e8-93ab-068b2152bc23.png)

**Comment by metas-dh** [comment]
```
trace
:
["org.adempiere.ad.callout.exceptions.CalloutExecutionException: ERROR: syntax error at or near ","",…]
[0 … 99]
0
:
"org.adempiere.ad.callout.exceptions.CalloutExecutionException: ERROR: syntax error at or near ",""
1
:
"  Position: 186"
2
:
"	at org.compiere.model.CalloutEngine.start(CalloutEngine.java:75)"
3
:
"	at org.adempiere.ad.callout.api.impl.MethodNameCalloutInstance.execute(MethodNameCalloutInstance.java:120)"
4
:
"	at org.adempiere.ad.callout.api.impl.CalloutExecutor.execute(CalloutExecutor.java:262)"
5
:
"	at org.adempiere.ad.callout.api.impl.CalloutExecutor.execute(CalloutExecutor.java:119)"
6
:
"	at de.metas.ui.web.window.model.Document.setValue(Document.java:1209)"
7
:
"	at de.metas.ui.web.window.model.Document.processValueChange(Document.java:1111)"
8
:
"	at de.metas.ui.web.window.model.Document.processValueChanges(Document.java:1126)"
9
:
"	at de.metas.ui.web.window.controller.WindowRestController.lambda$patchDocument0$6(WindowRestController.java:322)"
10
:
"	at de.metas.ui.web.window.model.DocumentCollection.lambda$forDocumentWritable$3(DocumentCollection.java:245)"
11
:
"	at de.metas.ui.web.window.model.DocumentCollection.forRootDocumentWritable(DocumentCollection.java:288)"
12
:
"	at de.metas.ui.web.window.model.DocumentCollection.forDocumentWritable(DocumentCollection.java:228)"
13
:
"	at de.metas.ui.web.window.controller.WindowRestController.patchDocument0(WindowRestController.java:318)"
14
:
"	at de.metas.ui.web.window.controller.WindowRestController.lambda$patchDocument$5(WindowRestController.java:312)"
15
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$4.call(TrxCallableWrappers.java:193)"
16
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)"
17
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:771)"
18
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:683)"
19
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:584)"
20
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:515)"
21
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:492)"
22
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:469)"
23
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$0(Execution.java:194)"
24
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
25
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
26
:
"	at de.metas.ui.web.window.controller.Execution.callInNewExecution(Execution.java:88)"
27
:
"	at de.metas.ui.web.window.controller.WindowRestController.patchDocument(WindowRestController.java:312)"
28
:
"	at de.metas.ui.web.window.controller.WindowRestController.patchRootDocument(WindowRestController.java:281)"
29
:
"	at sun.reflect.GeneratedMethodAccessor314.invoke(Unknown Source)"
30
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
31
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
32
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
33
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
34
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
35
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
36
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
37
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
38
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
39
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
40
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
41
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)"
42
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
43
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
44
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
45
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
46
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
47
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
48
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
49
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
50
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
51
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
52
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
53
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
54
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
55
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
56
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
57
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
58
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)"
59
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
60
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
61
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
62
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
63
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
64
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
65
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
66
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
67
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
68
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
69
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
70
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
71
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
72
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
73
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
74
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
75
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
76
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
77
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
78
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
79
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
80
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
81
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
82
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
83
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
84
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
85
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
86
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
87
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
88
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
89
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
90
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
91
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
92
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
93
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
94
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
95
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
96
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
97
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
98
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
99
:
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
[100 … 105]
100
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
101
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
102
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
103
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
104
:
"	at java.lang.Thread.run(Thread.java:748)"
105
:
""
```

**Comment by teosarca** [comment]
issue was introduced by https://github.com/metasfresh/metasfresh/issues/3414

**Comment by metas-lc** [comment]
IT
1. tested the case above, on both purchase and sales: there are no errors when you select another bill bpartner, but right after you set it, the pricelist updates to Divers and the currency to CHF NOK
(have to see if it's related with this task)
2. regression
