### ISSUE TITLE
Compensation Group: Sequence of Lines is lost on Clone  

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#3745]
### Is this a bug or feature request?
bug

### What is the current behavior?
the sequence of Lines is lost on Clone and process creating sales order from quotation when using compensation groups 

#### Which are the steps to reproduce?
case No. 1  
1. create sales order 
1. have 2x compensation groups
1. add one manual discount
1. OK: all lines for one group are in one sequence (first group a, then b)
1. Clone the order 
1. lines of group a are interrupted by lines of group b 

case No. 2
1. create quotation
1. have 2x compensation groups
1. add one manual discount
1. OK: all lines for one group are in one sequence (first group a, then b)
1. use process to create order from quotation
1. lines of group a are interrupted by lines of group b 

### What is the expected or desired behavior?
sequence of orderlines is maintained

**Comment by teosarca** [comment]
note to IT: regression on copy+details

**Comment by metasnw** [comment]
Test on Branch System:
Original Problem is fixed
No Regression Test done

**Comment by metas-ts** [comment]
:cherries: picked to `release`

**Comment by metas-dh** [comment]
IT OK, see above
regression (mf15):

* copy with details, in Swing:

```
2018-03-26 14:50:57.196 ERROR 29645 --- [WT-EventQueue-0] org.compiere.apps.APanel                 : CopyDetails

java.lang.ArrayStoreException: de.metas.i18n.ImmutableTranslatableString
    at java.util.stream.Nodes$FixedNodeBuilder.accept(Nodes.java:1222)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Collections$2.tryAdvance(Collections.java:4717)
    at java.util.Collections$2.forEachRemaining(Collections.java:4725)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
    at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
    at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
    at org.compiere.apps.APanel.getSuggestedChildTablesToCopyWithDetails(APanel.java:3445)
    at org.compiere.apps.APanel.cmd_new(APanel.java:2193)
    at org.compiere.apps.APanel.actionPerformed(APanel.java:1970)
    at org.compiere.apps.AppsAction.actionPerformed(AppsAction.java:455)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6533)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6298)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4889)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2746)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by metas-ts** [comment]
:cherries: picked to `release`

**Comment by metas-dh** [comment]
Regression2 (mf15):

* copy with details (Swing): no error, orderlines are correctly copied to new order: OK
