### ISSUE TITLE
Picking TU Label error when GLN is missing in PartnerLocation

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#3767]
* Followup for https://github.com/metasfresh/metasfresh/issues/3576

### Is this a bug or feature request?
* Bug
### What is the current behavior?

* CUrrently, if I try to run the report for displaying the TU Picking Label and the HU's bpartner does not have a GLN set in the address, I get the following error: 

```
2018-03-28 10:33:38.356 ERROR 3830 --- [http-nio-8080-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.adempiere.exceptions.AdempiereException: java.lang.NullPointerException: Parameter msg must not be empty] with root cause

java.lang.NullPointerException: Parameter msg must not be empty
        at org.krysalis.barcode4j.impl.code128.EAN128Bean.generateBarcode(EAN128Bean.java:71)
        at net.sf.jasperreports.components.barcode4j.BarcodeSVGImageProducer.createImage(BarcodeSVGImageProducer.java:66)
        at net.sf.jasperreports.components.barcode4j.AbstractBarcodeEvaluator.evaluateBarcodeRenderable(AbstractBarcodeEvaluator.java:108)
        at net.sf.jasperreports.components.barcode4j.AbstractBarcodeEvaluator.visitEANCode128(AbstractBarcodeEvaluator.java:243)
        at net.sf.jasperreports.components.barcode4j.EAN128Component.receive(EAN128Component.java:80)
        at net.sf.jasperreports.components.barcode4j.AbstractBarcodeEvaluator.evaluateBarcode(AbstractBarcodeEvaluator.java:95)
        at net.sf.jasperreports.components.barcode4j.BarcodeFillComponent.evaluateBarcode(BarcodeFillComponent.java:81)
        at net.sf.jasperreports.components.barcode4j.BarcodeFillComponent.evaluate(BarcodeFillComponent.java:68)
        at net.sf.jasperreports.engine.fill.JRFillComponentElement.evaluate(JRFillComponentElement.java:109)
        at net.sf.jasperreports.engine.fill.JRFillElementContainer.evaluate(JRFillElementContainer.java:281)
        at net.sf.jasperreports.engine.fill.JRFillBand.evaluate(JRFillBand.java:504)
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillColumnBand(JRVerticalFiller.java:2026)
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillDetail(JRVerticalFiller.java:752)
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReportStart(JRVerticalFiller.java:259)
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReport(JRVerticalFiller.java:119)
        at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:558)
        at net.sf.jasperreports.engine.fill.BaseReportFiller.fill(BaseReportFiller.java:396)
        at net.sf.jasperreports.engine.fill.JRFillSubreport.fillSubreport(JRFillSubreport.java:742)
        at net.sf.jasperreports.engine.fill.JRSubreportRunnable.run(JRSubreportRunnable.java:58)
        at net.sf.jasperreports.engine.fill.AbstractThreadSubreportRunner.run(AbstractThreadSubreportRunner.java:216)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

#### Which are the steps to reproduce?
* Have something to pick for a partner that doesn't have a GLN set in the address.
* Pick
* Open HU Selection
* Go to action Picking TU Label, run it
* => NOK: You will get the error I posted
### What is the expected or desired behavior?
* Have a way to not get an IO error. We can either: 
1) When GLN is missing, display this report with no barcode ( Lili's idea) 
2) At least have a human readable error that leads the user to set a GLN in the address, or let them know that this missing GLN is the real reason for the error.

**Comment by metas-lc** [comment]
In case if gln is missing (null or empty) i put '0000000000000' instead

**Comment by metas-ts** [comment]
:cherries:picked to `2018-12`

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* if gln is missing label shows '0000000000000' instead: OK
* worked for manually printed picking TU label and automatically printed ones (pick to new HU action): OK
* GLN was still displayed correctly when set: OK
