### ISSUE TITLE
Error AnnotationConfigEmbeddedWebApplicationContext has not been refreshed yet

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3804]
### Is this a bug or feature request?
Bug
### What is the current behavior?

e.g. this:
```
org.adempiere.exceptions.AdempiereException: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@5fbdfdcf has not been refreshed yet
Additional parameters:
 I_C_Queue_WorkPackage: X_C_Queue_WorkPackage[C_Queue_WorkPackage_ID=1000934, trxName=null]
 IQueueProcessor: ThreadPoolQueueProcessor{name=M_ShipmentSchedule_Update, executor=BlockingThreadPoolExecutor [getPoolSize()=1]}
 trxName: <<ThreadInherited>>
	at org.adempiere.exceptions.AdempiereException.wrapIfNeeded(AdempiereException.java:89)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.invokeProcessorAndHandleException(WorkpackageProcessorTask.java:302)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.processWorkpackage(WorkpackageProcessorTask.java:290)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.access$000(WorkpackageProcessorTask.java:90)
	at de.metas.async.processor.impl.WorkpackageProcessorTask$1.run(WorkpackageProcessorTask.java:173)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:103)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:93)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:774)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:686)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:594)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.run(WorkpackageProcessorTask.java:163)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at Thread.run(Thread.java:748)
Caused by: IllegalStateException: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@5fbdfdcf has not been refreshed yet
	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1068)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1092)
	at org.compiere.Adempiere.getBean(Adempiere.java:196)
	at de.metas.inoutcandidate.api.impl.ShipmentScheduleBL.updateWarehouseId(ShipmentScheduleBL.java:842)
	at de.metas.inoutcandidate.api.impl.ShipmentScheduleBL.updateSchedules(ShipmentScheduleBL.java:172)
	at de.metas.inoutcandidate.api.impl.ShipmentScheduleUpdater.updateShipmentSchedule(ShipmentScheduleUpdater.java:92)
	at de.metas.inoutcandidate.async.UpdateInvalidShipmentSchedulesWorkpackageProcessor.processWorkPackage(UpdateInvalidShipmentSchedulesWorkpackageProcessor.java:74)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.invokeProcessorAndHandleException(WorkpackageProcessorTask.java:298)
	... 14 more
```

**Comment by metas-ts** [comment]
in the log, around server startup i found this:
```
2018-04-03 09:18:42.026  WARN 18560 --- [main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'MSV3StockAvailabilityService': Bean with name 'MSV3StockAvailabilityService' has been injected into other beans [m_Product] in its raw version as part of a circular reference, but has eventually been wrapped. This means that said other beans do not use the final version of the bean. This is often the result of over-eager type matching - consider using 'getBeanNamesOfType' with the 'allowEagerInit' flag turned off, for example.
```

**Comment by metas-ts** [comment]
:cherries: picked to `release`

**Comment by metas-lc** [comment]
IT
async woks fine now, no errors and documents are updated correctly 
OK
