### ISSUE TITLE
NPE on sales order complete

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3894]
### Is this a bug or feature request?
Bug
### What is the current behavior?
```
Caused by: java.lang.NullPointerException: additionalAmt"
 at org.adempiere.bpartner.service.IBPartnerStatsBL$CalculateSOCreditStatusRequest.<init>(IBPartnerStatsBL.java:44)"
 at org.adempiere.bpartner.service.IBPartnerStatsBL$CalculateSOCreditStatusRequest$CalculateSOCreditStatusRequestBuilder.build(IBPartnerStatsBL.java:44)"
 at de.metas.invoicecandidate.modelvalidator.C_Order.checkCreditLimit(C_Order.java:107)"
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
 at java.lang.reflect.Method.invoke(Method.java:498)"
 at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.executeNow0(AnnotatedModelInterceptor.java:611)"
 at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.executeNow(AnnotatedModelInterceptor.java:563)"
 ... 131 more
```

**Comment by metas-rc** [comment]
Results of IT


Tested on webui


OK: There is no NPE anymore.
