### ISSUE TITLE
Implement support for `der Kurier` shipper

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3926]
### Is this a bug or feature request?
FR

#### Shipper

* go to Lieferweg/Shipper
* create a new record with shipper-gateway-id="DerKurier":

![image](https://user-images.githubusercontent.com/1264789/39687731-03e891a8-51d0-11e8-8de1-133da16f42f4.png)

* the open the "Der Kurier Konfiguration" tab:
![image](https://user-images.githubusercontent.com/1264789/39688106-7a916a72-51d1-11e8-8fd4-53ae168808e4.png)

* Kundennummer: is generally provided by "Der Kurier"..for testing just enter any number
* Rest API base URL: https://leoz.derkurier.de:13000/rs/api/v1
* Mailserver and Mail address: if set, the system will send the delivery order as CSV to the resepective mail address, using the respective server
  * Note: delivery orders can contain personal data and therefore mails should be send directly (with TLS) to a mail server controlled by Der Kurier.
  * Note2: even if the cvs is not mailed, it is attached to the respectiove "Der Kurier Delivery order record
* Sendungsnummernkreis: click on the field name to jump to the sequence window and create new record.
  * Name: something like  "Der Kurier Sendungsnummernkreis"
  * Automatische Numerierung=yes
  * Decimal pattern=00000000000
![image](https://user-images.githubusercontent.com/1264789/39687928-ca7c11c8-51d0-11e8-9b26-5b44d5c5fc2f.png)

**Comment by metas-ts** [comment]
workspace-changes
* rename de.metas.shipper.gateway.api to de.metas.shipper.gateway.spi
* add de.metas.shipper.gateway.commons
* add de.metas.shipper.gateway.derkurier

**Comment by metas-ts** [comment]
Terminology - WIP

excel file header (note that we will actually send header-less CSV), vs https://leoz.derkurier.de:13000/rs/

|DE (excel)| `/v1/document/label`    | `v1/routing/request` |
| ------------- | ------------------ | -------------------- |
| Verladedatum |                     | sendDate
| KDNR | <stored in our master data> | 
| FirmaD | consignee.name1 |
| FirmaD2 | consignee.name2 |
| FirmaD3 | consignee.name3 |
| LandD | consignee.country |
| PLZD | consignee.zipCode |
| OrtD | consignee.city |
| StrasseD | consignee.street |
| StrNrD | consignee.streetNo |
| Lieferdepot |  |
| dtAuslieferung |  |
| dtTermin_von |  |
| dtTermin |  |
| OrderPos |  |
| GewichtReal |  |
| Laenge |  |
| Breite |  |
| Hoehe |  |
| Belegnummer | parcelNumber |
| Referenz | *orderNumber?* |
| Ex_Orderid |  |
| cReferenz |  |
| Tel-Empf |  |
| EA |  |
| EB |  |
| EC |  |
| NN |  |
| Gesamt | *parcelAmount?* |
| Email-Empf |  |

(note: https://help.github.com/articles/organizing-information-with-tables/)

**Comment by metas-lc** [comment]
Jasper contains:
Barcode (ParcelNumber)
weight, zipcode, package amt (if there are 3 you will see 1 von 3)
 ParcelNumber
desiredstation (only on middle for now)
sender (not set atm)
data from bp org: bp name, loc.address1, tel (via ad_user order by default desc limit 1), country, postal, city
desireddeliverydate time from - time to
receiver
data: name, name2, name3, phone, street, country, zipcode, city
logo
(might need changes later)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

SetUp:
* shipper entry with shipper-gateway-id="DerKurier"
* "Der Kurier Konfiguration" tab:
    * Kundennummer: provided by metas-ts
    * Rest API base URL: https://leoz.derkurier.de:13000/rs/api/v1
    * Sendungsnummernkreis: provided by metas-ts
    * CustomerCode and CollectorCode both = 20
    * delivery times = 09:00 - 17:00
    * set bpartner location with an existing postcode

Test:
1. Have HUs in Picking Tray Clearing Terminal
2. Have / cretae a Transportation Order
3. Select a HU in Picking Tray Clearing Terminal, on the left, and take it out
4. Select this HU on the right, and choose "Add to Transportation Order, Ship and Invoice" action
5. Select the Transportation Order, OK
=> notification for shipment being created: OK
=> no notification for invoice: bc not all QtyOrdered was delivered yet?
6. Check Der Kurier Delivery Orders:
* new entry: 
=> sender details correct (metasfresh, with location etc.): OK
=> preferred pickup date: taken from transportation order, OK i think
=> preferred pickup time from: empty, why?
=> preferred pickup time to: the time when the entry was created, OK??
* orderline:
=> customer no, consignee name and address (bpartner & location details) displayed correctly (empty if not set): OK
* consignee delivery date: 23.5.: why? => 1 day after date from transportation order? (that one was set for 22.5., and delivery order was created 24.5.)
* consignee depot: 50 (where is this taken from?)
=> package amt: 1, OK
=> parcel weight: 1: why? weight of product: 2.5, with PI (LU & TU): 28.74
7. Check the label in attachments:
=> sender data (name, address): OK
=> consignee data: no. is not displayed, only street name: NOK i think
=> parcel no. from sequence: OK
=> CustomerCode and CollectorCode: OK
=> Der Kurier logo: OK
8. Check the transportation order:
=> new line created for the package created (weight is all 0?)
=> reference to the shipment & Der Kurier delivery order: OK
9. Check the shipment:
=> references to the package and the HU: OK
10. Check the package:
=> shipment, shipper and HU displayed correctly: OK


To be tested:
Using Mailserver

**Comment by metas-dh** [comment]
Test with using mailserver (in release since the Mailserver works fine there):

got an error msg at 
5. Select the Transportation Order, OK:

```
{timestamp: 1527686548198, status: 500, error: "Internal Server Error",…}
error
:
"Internal Server Error"
exception
:
"org.adempiere.exceptions.AdempiereException"
message
:
"Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
↵Bitte leiten Sie diese Meldung an metas weiter:↵↵Assumption failure: username is not empty"
path
:
"/rest/api/process/ADP_540904/1001410/start"
status
:
500
timestamp
:
1527686548198
trace
:
[,…]
[0 … 99]
0
:
"org.adempiere.exceptions.AdempiereException: Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
"
1
:
"Bitte leiten Sie diese Meldung an metas weiter:"
2
:
""
3
:
"Assumption failure: username is not empty"
4
:
"	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)"
5
:
"	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)"
6
:
"	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)"
7
:
"	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)"
8
:
"	at org.adempiere.util.Check.mkEx(Check.java:108)"
9
:
"	at org.adempiere.util.Check.throwOrLogEx(Check.java:119)"
10
:
"	at org.adempiere.util.Check.assume(Check.java:163)"
11
:
"	at org.adempiere.util.Check.assumeNotEmpty(Check.java:309)"
12
:
"	at org.adempiere.util.Check.assumeNotEmpty(Check.java:293)"
13
:
"	at de.metas.email.Mailbox.<init>(Mailbox.java:95)"
14
:
"	at de.metas.email.Mailbox.<init>(Mailbox.java:43)"
15
:
"	at de.metas.email.Mailbox$MailboxBuilder.build(Mailbox.java:72)"
16
:
"	at de.metas.shipper.gateway.derkurier.misc.DerKurierShipperConfigRepository.loadMailboxOrNull(DerKurierShipperConfigRepository.java:84)"
17
:
"	at de.metas.shipper.gateway.derkurier.misc.DerKurierShipperConfigRepository.retrieveConfigForShipperId(DerKurierShipperConfigRepository.java:55)"
18
:
"	at de.metas.shipper.gateway.derkurier.misc.DerKurierShipperConfigRepository$$FastClassBySpringCGLIB$$45159efd.invoke(<generated>)"
19
:
"	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)"
20
:
"	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)"
21
:
"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)"
22
:
"	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)"
23
:
"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)"
24
:
"	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)"
25
:
"	at de.metas.shipper.gateway.derkurier.misc.DerKurierShipperConfigRepository$$EnhancerBySpringCGLIB$$f6196929.retrieveConfigForShipperId(<generated>)"
26
:
"	at de.metas.shipper.gateway.derkurier.DerKurierDraftDeliveryOrderCreator.createDraftDeliveryOrder(DerKurierDraftDeliveryOrderCreator.java:87)"
27
:
"	at de.metas.shipper.gateway.commons.ShipperGatewayFacade.createAndSendDeliveryOrder(ShipperGatewayFacade.java:141)"
28
:
"	at com.google.common.collect.SingletonImmutableBiMap.forEach(SingletonImmutableBiMap.java:65)"
29
:
"	at de.metas.shipper.gateway.commons.ShipperGatewayFacade.createAndSendDeliveryOrdersForPackages(ShipperGatewayFacade.java:76)"
30
:
"	at de.metas.handlingunits.shipmentschedule.api.HUShippingFacade.generateShipperDeliveryOrderIfNeeded(HUShippingFacade.java:258)"
31
:
"	at com.google.common.collect.SingletonImmutableBiMap.forEach(SingletonImmutableBiMap.java:65)"
32
:
"	at de.metas.handlingunits.shipmentschedule.api.HUShippingFacade.generateShipperDeliveryOrdersIfNeeded(HUShippingFacade.java:225)"
33
:
"	at de.metas.handlingunits.shipmentschedule.api.HUShippingFacade.generateShippingDocuments0(HUShippingFacade.java:152)"
34
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$1.call(TrxCallableWrappers.java:56)"
35
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$1.call(TrxCallableWrappers.java:46)"
36
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
37
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
38
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
39
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
40
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:513)"
41
:
"	at org.adempiere.ad.trx.api.ITrxManager.runInThreadInheritedTrx(ITrxManager.java:221)"
42
:
"	at de.metas.handlingunits.shipmentschedule.api.HUShippingFacade.generateShippingDocuments(HUShippingFacade.java:143)"
43
:
"	at de.metas.ui.web.pickingslotsClearing.process.WEBUI_PackingHUsView_AddHUsToShipperTransportationShipAndInvoice.doIt(WEBUI_PackingHUsView_AddHUsToShipperTransportationShipAndInvoice.java:77)"
44
:
"	at de.metas.process.JavaProcess.startProcess(JavaProcess.java:293)"
45
:
"	at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:564)"
46
:
"	at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:460)"
47
:
"	at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:50)"
48
:
"	at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:224)"
49
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)"
50
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)"
51
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
52
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
53
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
54
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
55
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:506)"
56
:
"	at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:286)"
57
:
"	at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:171)"
58
:
"	at de.metas.process.ProcessExecutor.access$1100(ProcessExecutor.java:50)"
59
:
"	at de.metas.process.ProcessExecutor$Builder.executeSync(ProcessExecutor.java:651)"
60
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.executeADProcess(ADProcessInstanceController.java:285)"
61
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.startProcess(ADProcessInstanceController.java:262)"
62
:
"	at de.metas.ui.web.process.ProcessRestController.lambda$null$8(ProcessRestController.java:261)"
63
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.forProcessInstanceWritable(ADProcessInstancesRepository.java:419)"
64
:
"	at de.metas.ui.web.process.ProcessRestController.lambda$startProcess$9(ProcessRestController.java:260)"
65
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
66
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
67
:
"	at de.metas.ui.web.process.ProcessRestController.startProcess(ProcessRestController.java:259)"
68
:
"	at sun.reflect.GeneratedMethodAccessor354.invoke(Unknown Source)"
69
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
70
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
71
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
72
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
73
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
74
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
75
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
76
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
77
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
78
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
79
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
80
:
"	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
81
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
82
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
83
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
84
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
85
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
86
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
87
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
88
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
89
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
90
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
91
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
92
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
93
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
94
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
95
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
96
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
97
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
98
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
99
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)"
[100 … 146]
100
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
101
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
102
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
103
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
104
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
105
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
106
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
107
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
108
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
109
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
110
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
111
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
112
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
113
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
114
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
115
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
116
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
117
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
118
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
119
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
120
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
121
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
122
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
123
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
124
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
125
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
126
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
127
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
128
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
129
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
130
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
131
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
132
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
133
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
134
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
135
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
136
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
137
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
138
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
139
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
140
:
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
141
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
142
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
143
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
144
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
145
:
"	at java.lang.Thread.run(Thread.java:748)"
146
:
""
```
