### ISSUE TITLE
Pricing Conditions error when save

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4016]
### Is this a bug or feature request?
Bug
follow-up of https://github.com/metasfresh/metasfresh/issues/3925

### What is the current behavior?
When trying to save the temp. Pricing Conditions in Sales Order, then an error appears.

<details>

```
"org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: ERROR: null value in column "seqno" violates not-null constraint"
1
:
"  Detail: Failing row contains (1000015, 1000000, 1000000, Y, 2018-05-07 16:54:59+02, 2188223, 2018-05-07 16:54:59+02, 2188223, 1000003, null, null, 10, null, null, N, null, null, null, null, null, Y, F, 0, 50, Y, null)."
2
:
"	SQL: INSERT INTO M_DiscountSchemaBreak (AD_Client_ID,AD_Org_ID,BreakDiscount,Created,CreatedBy,IsActive,IsPriceOverride,IsValid,M_DiscountSchemaBreak_ID,M_DiscountSchema_ID,PriceBase,PriceStd,Std_AddAmt,Updated,UpdatedBy) VALUES (1000000,1000000,10,TO_TIMESTAMP('2018-05-07 16:54:59','YYYY-MM-DD HH24:MI:SS'),2188223,'Y','Y','Y',nextval('m_discountschemabreak_seq'),1000003,'F',50,0,TO_TIMESTAMP('2018-05-07 16:54:59','YYYY-MM-DD HH24:MI:SS'),2188223) RETURNING M_DiscountSchemaBreak_ID"
3
:
"	at org.adempiere.exceptions.DBException.wrapIfNeeded(DBException.java:89)"
4
:
"	at org.compiere.util.DB.executeUpdate(DB.java:993)"
5
:
"	at org.compiere.model.PO.saveNew(PO.java:3649)"
6
:
"	at org.compiere.model.PO.save0(PO.java:2830)"
7
:
"	at org.compiere.model.PO.access$100(PO.java:139)"
8
:
"	at org.compiere.model.PO$1.run(PO.java:2733)"
9
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)"
10
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)"
11
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
12
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
13
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
14
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
15
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:506)"
16
:
"	at org.compiere.model.PO.saveEx(PO.java:2727)"
17
:
"	at org.adempiere.model.POWrapper.save(POWrapper.java:799)"
18
:
"	at org.adempiere.model.InterfaceWrapperHelper.save(InterfaceWrapperHelper.java:561)"
19
:
"	at de.metas.pricing.conditions.service.impl.PricingConditionsRepository.changePricingConditionsBreak0(PricingConditionsRepository.java:345)"
20
:
"	at de.metas.pricing.conditions.service.impl.PricingConditionsRepository.lambda$changePricingConditionsBreak$3(PricingConditionsRepository.java:266)"
21
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)"
22
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
23
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
24
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
25
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
26
:
"	at de.metas.pricing.conditions.service.impl.PricingConditionsRepository.changePricingConditionsBreak(PricingConditionsRepository.java:266)"
27
:
"	at de.metas.ui.web.order.sales.pricingConditions.view.PricingConditionsRowsSaver.save(PricingConditionsRowsSaver.java:72)"
28
:
"	at de.metas.ui.web.order.sales.pricingConditions.process.PricingConditionsView_SaveEditableRow.doIt(PricingConditionsView_SaveEditableRow.java:66)"
29
:
"	at de.metas.process.JavaProcess.startProcess(JavaProcess.java:293)"
30
:
"	at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:564)"
31
:
"	at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:460)"
32
:
"	at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:50)"
33
:
"	at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:224)"
34
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)"
35
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)"
36
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
37
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
38
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
39
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
40
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:506)"
41
:
"	at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:286)"
42
:
"	at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:171)"
43
:
"	at de.metas.process.ProcessExecutor.access$1100(ProcessExecutor.java:50)"
44
:
"	at de.metas.process.ProcessExecutor$Builder.executeSync(ProcessExecutor.java:651)"
45
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.executeADProcess(ADProcessInstanceController.java:285)"
46
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.startProcess(ADProcessInstanceController.java:262)"
47
:
"	at de.metas.ui.web.process.ProcessRestController.lambda$null$8(ProcessRestController.java:261)"
48
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.forProcessInstanceWritable(ADProcessInstancesRepository.java:419)"
49
:
"	at de.metas.ui.web.process.ProcessRestController.lambda$startProcess$9(ProcessRestController.java:260)"
50
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
51
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
52
:
"	at de.metas.ui.web.process.ProcessRestController.startProcess(ProcessRestController.java:259)"
53
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
54
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
55
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
56
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
57
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
58
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
59
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
60
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
61
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
62
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
63
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
64
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
65
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
66
:
"	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
67
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
68
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
69
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
70
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
71
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
72
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
73
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
74
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
75
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
76
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
77
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
78
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
79
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
80
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
81
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
82
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
83
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
84
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
85
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)"
86
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
87
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
88
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
89
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
90
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
91
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
92
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
93
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
94
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
95
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
96
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
97
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
98
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
99
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
```

</details>

#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Shall work.

**Comment by metas-lc** [comment]
IT 
tested together with https://github.com/metasfresh/metasfresh/issues/3925
have a bpartner that has a discount schema, but no lines matching your product
create a new sales order for that bpartner, add product
go to actions "Pricing conditions", copy or manually set the data in editable line, press save
=> no errors OK
=> in discount schema a new line was added, for your product, with the data you set OK

note: you must have a discount schema on your bpartner, else you won't see the button
