### ISSUE TITLE
NPE when deleting inoutline with empty product

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4052]
### Is this a bug or feature request?
Bug
### What is the current behavior?

> found this on w101 and 5.56 customer system when deleting a line of a manual shipment :

<details>

```
2018-05-14 17:24:43.339 ERROR 107 --- [https-jsse-nio-8443-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.adempiere.exceptions.AdempiereException: java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
        at de.metas.contracts.impl.FlatrateDAO.retrieveRefundableDataEntry(FlatrateDAO.java:808)
        at de.metas.contracts.impl.FlatrateBL.updateFlatrateDataEntryQty(FlatrateBL.java:1524)
        at de.metas.contracts.interceptor.M_InOutLine.updateFLatrateDataEntryQtySubstract(M_InOutLine.java:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
```

</details>

**Comment by metas-lc** [comment]
IT
1. created a new sales inout (shipment), with a line without product. 
2. Delete the line
=> you can delete it, no errors OK
3. add the line again and delete the document 
=> you can delete it, no errors OK
4. repeat the same testcase with purchase inout (receipt)
=> works the same OK
5. repeat the same testcase with empties receive
=> works the same OK
6. repeat the same testcase with empties return
=> you cannot add a line without a product OK
