### ISSUE TITLE
Sales order: BPartner with multiple locations #967

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#4108]
### Is this a bug or feature request?
bug
### What is the current behavior?
you cannot create an order, in some cases, when you have a bpartner with multiple locations
#### Which are the steps to reproduce?
1. create a bpartner. Add 2 locations: one from e.g. RO, one from DE (make sure you don't have any pricelist from RO). You can use this one https://w101.metasfresh.com:8443/window/123/2156467
2. make the bpartner customer, with pricelist Customer Prices
3. create a new sales order, add this bpartner
=> error
Server error
Zum angegebenen Preissystem "Customer Prices" konnte keine Verkaufspreisliste gefunden werden.
NOK

### What is the expected or desired behavior?
should work. e.g. set the first location, and leave pricelist empty. You should be able to change locations and set the pricelist

**Comment by cristinamghita** [comment]
```
"org.adempiere.ad.callout.exceptions.CalloutExecutionException: Zum angegebenen Preissystem "Customer Prices" konnte keine Verkaufspreisliste gefunden werden."
1
:
"	at org.adempiere.ad.callout.exceptions.CalloutExecutionException.of(CalloutExecutionException.java:28)"
2
:
"	at org.adempiere.ad.callout.exceptions.CalloutExecutionException.of(CalloutExecutionException.java:25)"
3
:
"	at org.compiere.model.CalloutEngine.start(CalloutEngine.java:86)"
4
:
"	at org.adempiere.ad.callout.api.impl.MethodNameCalloutInstance.execute(MethodNameCalloutInstance.java:120)"
5
:
"	at org.adempiere.ad.callout.api.impl.CalloutExecutor.execute(CalloutExecutor.java:262)"
6
:
"	at org.adempiere.ad.callout.api.impl.CalloutExecutor.execute(CalloutExecutor.java:119)"
7
:
"	at de.metas.ui.web.window.model.Document.setValue(Document.java:1209)"
8
:
"	at de.metas.ui.web.window.model.Document.processValueChange(Document.java:1111)"
9
:
"	at de.metas.ui.web.window.model.Document.processValueChanges(Document.java:1126)"
10
:
"	at de.metas.ui.web.window.controller.WindowRestController.lambda$patchDocument0$6(WindowRestController.java:322)"
11
:
"	at de.metas.ui.web.window.model.DocumentCollection.lambda$forDocumentWritable$3(DocumentCollection.java:245)"
12
:
"	at de.metas.ui.web.window.model.DocumentCollection.forRootDocumentWritable(DocumentCollection.java:288)"
13
:
"	at de.metas.ui.web.window.model.DocumentCollection.forDocumentWritable(DocumentCollection.java:228)"
14
:
"	at de.metas.ui.web.window.controller.WindowRestController.patchDocument0(WindowRestController.java:318)"
15
:
"	at de.metas.ui.web.window.controller.WindowRestController.lambda$patchDocument$5(WindowRestController.java:312)"
16
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$4.call(TrxCallableWrappers.java:193)"
17
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)"
18
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
19
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
20
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
21
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
22
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:498)"
23
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:475)"
24
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$0(Execution.java:194)"
25
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
26
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
27
:
"	at de.metas.ui.web.window.controller.Execution.callInNewExecution(Execution.java:88)"
28
:
"	at de.metas.ui.web.window.controller.WindowRestController.patchDocument(WindowRestController.java:312)"
29
:
"	at de.metas.ui.web.window.controller.WindowRestController.patchRootDocument(WindowRestController.java:281)"
30
:
"	at sun.reflect.GeneratedMethodAccessor388.invoke(Unknown Source)"
31
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
32
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
33
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
34
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
35
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
36
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
37
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
38
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
39
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
40
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
41
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
42
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)"
43
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
44
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
45
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
46
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
47
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
48
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
49
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
50
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
51
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
52
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
53
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
54
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
55
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
56
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
57
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
58
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
59
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)"
60
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
61
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
62
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
63
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
64
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
65
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
66
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
67
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
68
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
69
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
70
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
71
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
72
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
73
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
74
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
75
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
76
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
77
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
78
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
79
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
80
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
81
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
82
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
83
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
84
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
85
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
86
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
87
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
88
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
89
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
90
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
91
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
92
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
93
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
94
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
95
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
96
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
97
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
98
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
99
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
101
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
102
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
103
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
104
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
105
:
"	at java.lang.Thread.run(Thread.java:748)"
106
:
"Caused by: de.metas.pricing.exceptions.PriceListNotFoundException: Zum angegebenen Preissystem "Customer Prices" konnte keine Verkaufspreisliste gefunden werden."
107
:
"	at de.metas.order.impl.OrderBL.setPriceList(OrderBL.java:191)"
108
:
"	at de.metas.order.impl.OrderBL.setM_PricingSystem_ID(OrderBL.java:164)"
109
:
"	at de.metas.adempiere.callout.OrderPricingSystem.cBPartnerId(OrderPricingSystem.java:21)"
110
:
"	at sun.reflect.GeneratedMethodAccessor530.invoke(Unknown Source)"
111
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
112
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
113
:
"	at org.compiere.model.CalloutEngine.lambda$createCalloutMethodExecutor$3(CalloutEngine.java:201)"
114
:
"	at org.compiere.model.CalloutEngine.start(CalloutEngine.java:71)"
115
:
"	... 102 more"
```
"org.adempiere.ad.callout.exceptions.CalloutExecutionException: Zum angegebenen Preissystem "Customer Prices" konnte keine Verkaufspreisliste gefunden werden."
1
:
"	at org.adempiere.ad.callout.exceptions.CalloutExecutionException.of(CalloutExecutionException.java:28)"
2
:
"	at org.adempiere.ad.callout.exceptions.CalloutExecutionException.of(CalloutExecutionException.java:25)"
3
:
"	at org.compiere.model.CalloutEngine.start(CalloutEngine.java:86)"
4
:
"	at org.adempiere.ad.callout.api.impl.MethodNameCalloutInstance.execute(MethodNameCalloutInstance.java:120)"
5
:
"	at org.adempiere.ad.callout.api.impl.CalloutExecutor.execute(CalloutExecutor.java:262)"
6
:
"	at org.adempiere.ad.callout.api.impl.CalloutExecutor.execute(CalloutExecutor.java:119)"
7
:
"	at de.metas.ui.web.window.model.Document.setValue(Document.java:1209)"
8
:
"	at de.metas.ui.web.window.model.Document.processValueChange(Document.java:1111)"
9
:
"	at de.metas.ui.web.window.model.Document.processValueChanges(Document.java:1126)"
10
:
"	at de.metas.ui.web.window.controller.WindowRestController.lambda$patchDocument0$6(WindowRestController.java:322)"
11
:
"	at de.metas.ui.web.window.model.DocumentCollection.lambda$forDocumentWritable$3(DocumentCollection.java:245)"
12
:
"	at de.metas.ui.web.window.model.DocumentCollection.forRootDocumentWritable(DocumentCollection.java:288)"
13
:
"	at de.metas.ui.web.window.model.DocumentCollection.forDocumentWritable(DocumentCollection.java:228)"
14
:
"	at de.metas.ui.web.window.controller.WindowRestController.patchDocument0(WindowRestController.java:318)"
15
:
"	at de.metas.ui.web.window.controller.WindowRestController.lambda$patchDocument$5(WindowRestController.java:312)"
16
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$4.call(TrxCallableWrappers.java:193)"
17
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)"
18
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
19
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
20
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
21
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
22
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:498)"
23
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:475)"
24
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$0(Execution.java:194)"
25
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
26
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
27
:
"	at de.metas.ui.web.window.controller.Execution.callInNewExecution(Execution.java:88)"
28
:
"	at de.metas.ui.web.window.controller.WindowRestController.patchDocument(WindowRestController.java:312)"
29
:
"	at de.metas.ui.web.window.controller.WindowRestController.patchRootDocument(WindowRestController.java:281)"
30
:
"	at sun.reflect.GeneratedMethodAccessor388.invoke(Unknown Source)"
31
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
32
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
33
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
34
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
35
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
36
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
37
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
38
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
39
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
40
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
41
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
42
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)"
43
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
44
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
45
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
46
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
47
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
48
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
49
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
50
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
51
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
52
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
53
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
54
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
55
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
56
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
57
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
58
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
59
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)"
60
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
61
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
62
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
63
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
64
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
65
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
66
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
67
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
68
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
69
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
70
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
71
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
72
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
73
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
74
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
75
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
76
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
77
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
78
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
79
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
80
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
81
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
82
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
83
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
84
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
85
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
86
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
87
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
88
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
89
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
90
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
91
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
92
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
93
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
94
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
95
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
96
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
97
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
98
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
99
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
101
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
102
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
103
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
104
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
105
:
"	at java.lang.Thread.run(Thread.java:748)"
106
:
"Caused by: de.metas.pricing.exceptions.PriceListNotFoundException: Zum angegebenen Preissystem "Customer Prices" konnte keine Verkaufspreisliste gefunden werden."
107
:
"	at de.metas.order.impl.OrderBL.setPriceList(OrderBL.java:191)"
108
:
"	at de.metas.order.impl.OrderBL.setM_PricingSystem_ID(OrderBL.java:164)"
109
:
"	at de.metas.adempiere.callout.OrderPricingSystem.cBPartnerId(OrderPricingSystem.java:21)"
110
:
"	at sun.reflect.GeneratedMethodAccessor530.invoke(Unknown Source)"
111
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
112
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
113
:
"	at org.compiere.model.CalloutEngine.lambda$createCalloutMethodExecutor$3(CalloutEngine.java:201)"
114
:
"	at org.compiere.model.CalloutEngine.start(CalloutEngine.java:71)"
115
:
"	... 102 more"
```
