### ISSUE TITLE
Transform action throws error

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#4122]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Calling the "Transform" action in e.g. material receipt candidates throws an error.
#### Which are the steps to reproduce?
1. Select a TU or CU line in e.g. Material Receipt Candidates, HU Editor (window/540196)
2. Select "Transform":

```
Error: Cannot convert QtyCU's value...
Server error
Cannot convert QtyCU's value '30.000 kg (source: 30.000 kg)' (class de.metas.quantity.Quantity) to class java.math.BigDecimal LookupDataSource: null

{timestamp: 1527502233687, status: 500, error: "Internal Server Error",…}
error
:
"Internal Server Error"
exception
:
"org.adempiere.exceptions.AdempiereException"
message
:
"Cannot convert QtyCU's value '30.000 kg (source: 30.000 kg)' (class de.metas.quantity.Quantity) to class java.math.BigDecimal↵ LookupDataSource: null"
path
:
"/rest/api/process/ADP_540763"
status
:
500
timestamp
:
1527502233687
trace
:
[,…]
[0 … 99]
0
:
"org.adempiere.exceptions.AdempiereException: Cannot convert QtyCU's value '30.000 kg (source: 30.000 kg)' (class de.metas.quantity.Quantity) to class java.math.BigDecimal"
1
:
" LookupDataSource: null"
2
:
"	at de.metas.ui.web.window.descriptor.DocumentFieldDescriptor.convertToValueClass(DocumentFieldDescriptor.java:690)"
3
:
"	at de.metas.ui.web.window.descriptor.DocumentFieldDescriptor.convertToValueClass(DocumentFieldDescriptor.java:373)"
4
:
"	at de.metas.ui.web.window.model.DocumentField.convertToValueClass(DocumentField.java:338)"
5
:
"	at de.metas.ui.web.window.model.DocumentField.convertToValueClass(DocumentField.java:293)"
6
:
"	at de.metas.ui.web.window.model.DocumentField.convertToValueClassAndCorrect(DocumentField.java:304)"
7
:
"	at de.metas.ui.web.window.model.DocumentField.setValue(DocumentField.java:207)"
8
:
"	at de.metas.ui.web.window.model.Document.setValue(Document.java:1193)"
9
:
"	at de.metas.ui.web.window.model.Document.processValueChange(Document.java:1111)"
10
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.lambda$createNewProcessInstance0$2(ADProcessInstancesRepository.java:178)"
11
:
"	at de.metas.process.ProcessDefaultParametersUpdater.updateDefaultValue(ProcessDefaultParametersUpdater.java:164)"
12
:
"	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)"
13
:
"	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)"
14
:
"	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)"
15
:
"	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)"
16
:
"	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)"
17
:
"	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)"
18
:
"	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)"
19
:
"	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)"
20
:
"	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)"
21
:
"	at de.metas.process.ProcessDefaultParametersUpdater.updateDefaultValue(ProcessDefaultParametersUpdater.java:195)"
22
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.createNewProcessInstance0(ADProcessInstancesRepository.java:179)"
23
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.createNewProcessInstance(ADProcessInstancesRepository.java:145)"
24
:
"	at de.metas.ui.web.process.ProcessRestController.lambda$createInstanceFromRequest$4(ProcessRestController.java:196)"
25
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$4.call(TrxCallableWrappers.java:193)"
26
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)"
27
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
28
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
29
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
30
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
31
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:498)"
32
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:475)"
33
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$0(Execution.java:194)"
34
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
35
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
36
:
"	at de.metas.ui.web.window.controller.Execution.callInNewExecution(Execution.java:88)"
37
:
"	at de.metas.ui.web.process.ProcessRestController.createInstanceFromRequest(ProcessRestController.java:195)"
38
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
39
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
40
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
41
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
42
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
43
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
44
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
45
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
46
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
47
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
48
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
49
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
50
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
51
:
"	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)"
52
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)"
53
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
54
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
55
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
56
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
57
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
58
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
59
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
60
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
61
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
62
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
63
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
64
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
65
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
66
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
67
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
68
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
69
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
70
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)"
71
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
72
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
73
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
74
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
75
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
76
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
77
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
78
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
79
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
80
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
81
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
82
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
83
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
84
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
85
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
86
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
87
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
88
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
89
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
90
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
91
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
92
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
93
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
94
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
95
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
96
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
97
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
98
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
99
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
[100 … 117]
100
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
101
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
102
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
103
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
104
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
105
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
106
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
107
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
108
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
109
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
110
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
111
:
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
112
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
113
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
114
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
115
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
116
:
"	at java.lang.Thread.run(Thread.java:748)"
117
:
""
```

=> same for CUs with UOM: Kg or Pce
### What is the expected or desired behavior?
Shall work.

**Comment by metas-rc** [comment]
Probably introduced by https://github.com/metasfresh/metasfresh/issues/3463

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* Transform action does not throw error anymore: OK (checked material receipt candidates, HU Editor window, Picking Terminal and Picking Tray Clearing Terminal)
=> Assumption failure when calling Transform action for aggregated CU line, in Handling Unit Editor window: https://github.com/metasfresh/metasfresh/issues/4176
* Transform actions working fine: OK (checked in material receipt candidates, for LU / TU / CU, with UOMs Kg & PCE)

**Comment by metas-ts** [comment]
:cherries: picked to `release`
