### ISSUE TITLE
Dunning Jasper does not work

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#4123]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Dunning Jasper does not work, calling the action throws an error.
#### Which are the steps to reproduce?
1. Create a dunning document
2. Run the action for the Jasper (Mahnbrief):

<details>

```
Error: org.adempiere.exceptions.AdempiereException: Caught class java.io.IOException...
Server error
org.adempiere.exceptions.AdempiereException: Caught class java.io.IOException trying to invoke URL http://mf15releasetest:8080/adempiereJasper/ReportServlet?AD_Process_ID=1000000&AD_PInstance_ID=1000766&AD_Language=de_DE&output=PDF; message: Server returned HTTP response code: 500 for URL: http://mf15releasetest:8080/adempiereJasper/ReportServlet?AD_Process_ID=1000000&AD_PInstance_ID=1000766&AD_Language=de_DE&output=PDF

{timestamp: 1527514451779, status: 500, error: "Internal Server Error",…}
error
:
"Internal Server Error"
exception
:
"org.adempiere.exceptions.AdempiereException"
message
:
"org.adempiere.exceptions.AdempiereException: Caught class java.io.IOException trying to invoke URL http://mf15releasetest:8080/adempiereJasper/ReportServlet?AD_Process_ID=1000000&AD_PInstance_ID=1000764&AD_Language=de_DE&output=PDF; message: Server returned HTTP response code: 500 for URL: http://mf15releasetest:8080/adempiereJasper/ReportServlet?AD_Process_ID=1000000&AD_PInstance_ID=1000764&AD_Language=de_DE&output=PDF"
path
:
"/rest/api/process/ADP_1000000/1000764/start"
status
:
500
timestamp
:
1527514451779
trace
:
[,…]
[0 … 99]
0
:
"org.adempiere.exceptions.AdempiereException: org.adempiere.exceptions.AdempiereException: Caught class java.io.IOException trying to invoke URL http://mf15releasetest:8080/adempiereJasper/ReportServlet?AD_Process_ID=1000000&AD_PInstance_ID=1000764&AD_Language=de_DE&output=PDF; message: Server returned HTTP response code: 500 for URL: http://mf15releasetest:8080/adempiereJasper/ReportServlet?AD_Process_ID=1000000&AD_PInstance_ID=1000764&AD_Language=de_DE&output=PDF"
1
:
"	at org.adempiere.exceptions.AdempiereException.wrapIfNeeded(AdempiereException.java:89)"
2
:
"	at de.metas.adempiere.report.jasper.client.JRClient.report(JRClient.java:155)"
3
:
"	at de.metas.adempiere.report.jasper.client.JRClient.report(JRClient.java:176)"
4
:
"	at org.compiere.report.ReportStarter.startProcessPrintPreview(ReportStarter.java:160)"
5
:
"	at org.compiere.report.ReportStarter.startProcess(ReportStarter.java:94)"
6
:
"	at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:564)"
7
:
"	at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:460)"
8
:
"	at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:50)"
9
:
"	at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:224)"
10
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)"
11
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)"
12
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
13
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
14
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
15
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
16
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:506)"
17
:
"	at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:286)"
18
:
"	at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:171)"
19
:
"	at de.metas.process.ProcessExecutor.access$1100(ProcessExecutor.java:50)"
20
:
"	at de.metas.process.ProcessExecutor$Builder.executeSync(ProcessExecutor.java:651)"
21
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.executeADProcess(ADProcessInstanceController.java:285)"
22
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.startProcess(ADProcessInstanceController.java:262)"
23
:
"	at de.metas.ui.web.process.ProcessRestController.lambda$null$8(ProcessRestController.java:261)"
24
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.forProcessInstanceWritable(ADProcessInstancesRepository.java:419)"
25
:
"	at de.metas.ui.web.process.ProcessRestController.lambda$startProcess$9(ProcessRestController.java:260)"
26
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
27
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
28
:
"	at de.metas.ui.web.process.ProcessRestController.startProcess(ProcessRestController.java:259)"
29
:
"	at sun.reflect.GeneratedMethodAccessor354.invoke(Unknown Source)"
30
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
31
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
32
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
33
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
34
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
35
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
36
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
37
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
38
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
39
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
40
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
41
:
"	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
42
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
43
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
44
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
45
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
46
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
47
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
48
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
49
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
50
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
51
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
52
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
53
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
54
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
55
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
56
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
57
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
58
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
59
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
60
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)"
61
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
62
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
63
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
64
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
65
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
66
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
67
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
68
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
69
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
70
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
71
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
72
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
73
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
74
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
75
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
76
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
77
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
78
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
79
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
80
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
81
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
82
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
83
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
84
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
85
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
86
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
87
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
88
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
89
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
90
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
91
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
92
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
93
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
94
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
95
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
96
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
97
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
98
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
99
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
[100 … 121]
100
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
101
:
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
102
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
103
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
104
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
105
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
106
:
"	at java.lang.Thread.run(Thread.java:748)"
107
:
"Caused by: java.lang.RuntimeException: org.adempiere.exceptions.AdempiereException: Caught class java.io.IOException trying to invoke URL http://mf15releasetest:8080/adempiereJasper/ReportServlet?AD_Process_ID=1000000&AD_PInstance_ID=1000764&AD_Language=de_DE&output=PDF; message: Server returned HTTP response code: 500 for URL: http://mf15releasetest:8080/adempiereJasper/ReportServlet?AD_Process_ID=1000000&AD_PInstance_ID=1000764&AD_Language=de_DE&output=PDF"
108
:
"	at de.metas.adempiere.report.jasper.server.RemoteServletServer.report(RemoteServletServer.java:85)"
109
:
"	at de.metas.adempiere.report.jasper.client.JRClient.report(JRClient.java:151)"
110
:
"	... 104 more"
111
:
"Caused by: org.adempiere.exceptions.AdempiereException: Caught class java.io.IOException trying to invoke URL http://mf15releasetest:8080/adempiereJasper/ReportServlet?AD_Process_ID=1000000&AD_PInstance_ID=1000764&AD_Language=de_DE&output=PDF; message: Server returned HTTP response code: 500 for URL: http://mf15releasetest:8080/adempiereJasper/ReportServlet?AD_Process_ID=1000000&AD_PInstance_ID=1000764&AD_Language=de_DE&output=PDF"
112
:
"	at de.metas.adempiere.report.jasper.server.RemoteServletServer.report0(RemoteServletServer.java:119)"
113
:
"	at de.metas.adempiere.report.jasper.server.RemoteServletServer.report(RemoteServletServer.java:81)"
114
:
"	... 105 more"
115
:
"Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://mf15releasetest:8080/adempiereJasper/ReportServlet?AD_Process_ID=1000000&AD_PInstance_ID=1000764&AD_Language=de_DE&output=PDF"
116
:
"	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)"
117
:
"	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)"
118
:
"	at java.net.URL.openStream(URL.java:1045)"
119
:
"	at de.metas.adempiere.report.jasper.server.RemoteServletServer.report0(RemoteServletServer.java:102)"
120
:
"	... 106 more"
121
:
""
```

</details>

### What is the expected or desired behavior?
Shall work.

**Comment by metas-ts** [comment]
Hi @metas-dh when i invoke the error-message's URL, i just get an empty page PDF.
Can you please reproduce the problem while someone looks at the log file?

Note: aparently the error happened at May 28, 2018 1:34:11.779 PM, but on mf15releasetest there is not log file covering that date (probably created a new RC later?)

**Comment by metas-ts** [comment]
```
Caused by: org.postgresql.util.PSQLException: ERROR: column al.c_order_id does not exist
  Where: PL/pgSQL function documentpaid(numeric,numeric,numeric,numeric) line 50 at FOR over SELECT rows
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1418)
        at net.sf.jasperreports.engine.query.JRJdbcQueryExecuter.createDatasource(JRJdbcQueryExecuter.java:310)
        ... 11 common frames omitted
```

**Comment by metas-lc** [comment]
checked.
c_order_id seems to be removed from C_AllocationLine.
was used in Documentpaid(numeric, numeric, numeric, numeric) function

**Comment by cristinamghita** [comment]
@metas-dh , @metas-lc metas C_Order_ID was removed from C_AllocationLine in this task [#4035 Proforma Invoice via Sales Order workflow](https://github.com/metasfresh/metasfresh/issues/4035)
Now, the order can be taken from the invoice set in C_AllocationLine.
I will adjust the function

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Dunning Jasper (Mahnbrief) works as before, no error: OK

**Comment by metas-ts** [comment]
:cherries: picked to `release`
