### ISSUE TITLE
Sometimes I got NPE when posting an allocation

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4125]
### Is this a bug or feature request?
Bug

### What is the current behavior?

![image](https://user-images.githubusercontent.com/1264789/40659882-cdf34bba-634f-11e8-8716-9aa4b92efebb.png)

# Error message as text

```
Posting error
Posted: Verbuchungs-Fehler (Error) document: MAllocationHdr[1196066-1194629: Freigabe-Betrag=0 (#1)] Preserve Posted status: false
```

# Stack trace that is returned to the swing client:

<details>

```
org.compiere.acct.PostingExecutionException: Posting error
 Posted: Verbuchungs-Fehler (Error)
 document: MAllocationHdr[1196066-1194629: Freigabe-Betrag=0 (#1)]
 Preserve Posted status: false
        at org.adempiere.acct.api.impl.PostingRequestBuilder.setPostedError(PostingRequestBuilder.java:529)
        at org.adempiere.acct.api.impl.PostingRequestBuilder.access$200(PostingRequestBuilder.java:61)
        at org.adempiere.acct.api.impl.PostingRequestBuilder$3.run(PostingRequestBuilder.java:186)
        at org.adempiere.acct.api.impl.PostingRequestBuilder.postAfterTrxCommit(PostingRequestBuilder.java:601)
        at org.adempiere.acct.api.impl.PostingRequestBuilder.postIt(PostingRequestBuilder.java:176)
        at org.adempiere.acct.api.impl.PostingRequestBuilder$1.run(PostingRequestBuilder.java:102)
        at de.metas.adempiere.form.swing.SwingClientUIInvoker$1.run(SwingClientUIInvoker.java:107)
        at de.metas.adempiere.form.AbstractClientUIInvoker$1.run(AbstractClientUIInvoker.java:133)
        at de.metas.adempiere.form.AbstractClientUIInvoker.invoke(AbstractClientUIInvoker.java:103)
        at org.compiere.apps.AEnv.postImmediate(AEnv.java:1007)
        at org.compiere.apps.APanel.actionButton0(APanel.java:3007)
        at org.compiere.apps.APanel.actionButton(APanel.java:2817)
        at org.compiere.apps.APanel.actionPerformed(APanel.java:1945)
        at org.compiere.grid.GridController$1.actionPerformed(GridController.java:334)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
        at java.awt.Component.processMouseEvent(Component.java:6533)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6298)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
        at java.awt.Container.dispatchEventImpl(Container.java:2280)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82
```

</details>

# From the server log
```
org.compiere.acct.PostingException: Posting error
 @Posted@: @PostingError-E@ (Error)
 @Document@: MAllocationHdr[1196066-1194629: Freigabe-Betrag=0 (#1)]
 Preserve Posted status: false
        at org.compiere.acct.Doc.newPostingException(Doc.java:2286)
        at org.compiere.acct.Doc$1.doCatch(Doc.java:449)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.doCatch(TrxCallableWrappers.java:158)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:803)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:686)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:587)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:534)
        at org.compiere.acct.Doc.post(Doc.java:432)
        at org.adempiere.acct.api.impl.PostingRequestBuilder.postIt_Directly(PostingRequestBuilder.java:247)
        at org.adempiere.acct.api.impl.PostingRequestBuilder.access$000(PostingRequestBuilder.java:61)
        at org.adempiere.acct.api.impl.PostingRequestBuilder$2.run(PostingRequestBuilder.java:142)
        at org.adempiere.acct.api.impl.PostingRequestBuilder.postAfterTrxCommit(PostingRequestBuilder.java:601)
        at org.adempiere.acct.api.impl.PostingRequestBuilder.postIt(PostingRequestBuilder.java:137)
        at org.compiere.session.ServerBase.postImmediate(ServerBase.java:107)
        at sun.reflect.GeneratedMethodAccessor650.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:189)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
        at org.apache.cxf.transport.jms.JMSDestination.onMessage(JMSDestination.java:233)
        at org.apache.cxf.transport.jms.util.PollingMessageListenerContainer$Poller.run(PollingMessageListenerContainer.java:69)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: null
        at org.compiere.acct.Fact.dispose(Fact.java:119)
        at org.compiere.acct.Doc.post0(Doc.java:622)
        at org.compiere.acct.Doc.access$100(Doc.java:127)
        at org.compiere.acct.Doc$1.run(Doc.java:443)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:774)
        ... 26 common frames omitted
```

#### Which are the steps to reproduce?
Cannot reproduce. Happens only sometimes

### What is the expected or desired behavior?
Shall work

### Note to IT
Just make sure u can post some allocations and that's it.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* posted all allocations that were created when testing #4035, some with value: 0.00 and some with status: Reversed: all worked fine, OK
* re-posted some allocations as well: all worked fine, OK
