### ISSUE TITLE
NPE in CalloutOrder.bPartner

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#420]
Pls Fix.

2016-09-21 13:25:36.992  WARN 1024 --- [WT-EventQueue-0] org.compiere.model.GridTab               : java.lang.NullPointerException

org.adempiere.ad.callout.exceptions.CalloutExecutionException: java.lang.NullPointerException
        at org.adempiere.ad.callout.exceptions.CalloutExecutionException.of(CalloutExecutionException.java:28)
        at org.adempiere.ad.callout.exceptions.CalloutExecutionException.of(CalloutExecutionException.java:25)
        at org.compiere.model.CalloutEngine.start(CalloutEngine.java:86)
        at org.adempiere.ad.callout.api.impl.MethodNameCalloutInstance.execute(MethodNameCalloutInstance.java:120)
        at org.adempiere.ad.callout.api.impl.CalloutExecutor.execute(CalloutExecutor.java:236)
        at org.adempiere.ad.callout.api.impl.CalloutExecutor.execute(CalloutExecutor.java:109)
        at org.compiere.model.GridTab.processCallout(GridTab.java:3322)
        at org.compiere.model.GridTab.processFieldChange(GridTab.java:3243)
        at org.compiere.grid.GridController.dataStatusChanged(GridController.java:1265)
        at org.compiere.model.GridTab.fireDataStatusChanged(GridTab.java:2685)
        at org.compiere.model.GridTab.dataStatusChanged(GridTab.java:2651)
        at org.compiere.model.GridTable.fireDataStatusChanged(GridTable.java:3298)
        at org.compiere.model.GridTable.setValueAt(GridTable.java:1244)
        at org.compiere.grid.GridController.vetoableChange(GridController.java:1750)
        at java.beans.VetoableChangeSupport.fireVetoableChange(VetoableChangeSupport.java:375)
        at java.beans.VetoableChangeSupport.fireVetoableChange(VetoableChangeSupport.java:271)
        at javax.swing.JComponent.fireVetoableChange(JComponent.java:4534)
        at org.compiere.grid.ed.VLookup.actionCombo(VLookup.java:1011)
        at org.compiere.grid.ed.VLookupAutoCompleter.setUserObject(VLookupAutoCompleter.java:377)
        at org.compiere.apps.search.FieldAutoCompleter.acceptedListItem(FieldAutoCompleter.java:430)
        at org.compiere.apps.search.FieldAutoCompleter$3.actionPerformed(FieldAutoCompleter.java:190)
        at javax.swing.JComponent$ActionStandin.actionPerformed(JComponent.java:3425)
        at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
        at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
        at org.compiere.swing.CTextField.processKeyBinding(CTextField.java:302)
        at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
        at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
        at java.awt.Component.processEvent(Component.java:6310)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
        at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
        at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
        at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
        at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
        at java.awt.Component.dispatchEventImpl(Component.java:4760)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException: null
        at org.compiere.model.CalloutOrder.bPartner(CalloutOrder.java:408)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.compiere.model.CalloutEngine.lambda$createCalloutMethodExecutor$3(CalloutEngine.java:201)
        at org.compiere.model.CalloutEngine.start(CalloutEngine.java:71)
        ... 56 common frames omitted

**Comment by metas-rc** [comment]
Results of IT1:
I got an infinite loop.
Steps to reproduce:
Go to a partner and unchecked all the checkboxes ( from the lower part of the window ) but I left it active
Use that partner in a sales order
=> Infinite loop
=> The console if flooded with errors from the callout 
=> An error-like popup appeared but it was empty
I checked and the problem is that the callout org.compiere.model.CalloutOrder.bPartnerLocation(ICalloutField) is triggering itself.:
if (null == order.getC_BPartner_Location()) true
orderBL.setBPLocation(order, order.getC_BPartner()) sets the location but it's not saved. The callout is triggered nevertheless.
and so on.
Note: org.compiere.model.CalloutOrder.bPartnerLocation(ICalloutField) has a big FIXME at the begining.

**Comment by metas-rc** [comment]
Here is a part of the log from the console:
org.adempiere.ad.callout.exceptions.CalloutExecutionException: java.lang.StackOverflowError
at org.adempiere.ad.callout.exceptions.CalloutExecutionException.of(CalloutExecutionException.java:28)
at org.adempiere.ad.callout.exceptions.CalloutExecutionException.of(CalloutExecutionException.java:25)
at org.compiere.model.CalloutEngine.start(CalloutEngine.java:86)
at org.adempiere.ad.callout.api.impl.MethodNameCalloutInstance.execute(MethodNameCalloutInstance.java:120)
at org.adempiere.ad.callout.api.impl.CalloutExecutor.execute(CalloutExecutor.java:260)
at org.adempiere.ad.callout.api.impl.CalloutExecutor.execute(CalloutExecutor.java:118)
at org.compiere.model.GridTab.processCallout(GridTab.java:3322)
at org.compiere.model.GridTab.processFieldChange(GridTab.java:3243)
at org.compiere.grid.GridController.dataStatusChanged(GridController.java:1265)
at org.compiere.model.GridTab.fireDataStatusChanged(GridTab.java:2685)
at org.compiere.model.GridTab.dataStatusChanged(GridTab.java:2651)
at org.compiere.model.GridTable.fireDataStatusChanged(GridTable.java:3298)
at org.compiere.model.GridTable.setValueAt(GridTable.java:1244)
at org.compiere.model.GridTab.setValue(GridTab.java:3182)
at org.compiere.model.GridTab.setValue(GridTab.java:3131)
at org.adempiere.model.GridTabWrapper.setValue(GridTabWrapper.java:432)
at org.adempiere.model.GridTabWrapper.invoke(GridTabWrapper.java:293)
at com.sun.proxy.$Proxy116.setC_BPartner_Location_ID(Unknown Source)
at de.metas.adempiere.service.impl.OrderBL.setBPLocation(OrderBL.java:645)
at org.compiere.model.CalloutOrder.bPartnerLocation(CalloutOrder.java:283)
at sun.reflect.GeneratedMethodAccessor97.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.compiere.model.CalloutEngine.lambda$createCalloutMethodExecutor$3(CalloutEngine.java:201)
at org.compiere.model.CalloutEngine.start(CalloutEngine.java:71)
at org.adempiere.ad.callout.api.impl.MethodNameCalloutInstance.execute(MethodNameCalloutInstance.java:120)

**Comment by metas-rc** [comment]
The NPE is still there:

2016-09-28 17:12:35.013  WARN 15856 --- [AWT-EventQueue-0] org.compiere.model.GridTab               : java.lang.NullPointerException

org.adempiere.ad.callout.exceptions.CalloutExecutionException: java.lang.NullPointerException
	at org.adempiere.ad.callout.exceptions.CalloutExecutionException.of(CalloutExecutionException.java:28)
	at org.adempiere.ad.callout.exceptions.CalloutExecutionException.of(CalloutExecutionException.java:25)
	at org.compiere.model.CalloutEngine.start(CalloutEngine.java:86)
	at org.adempiere.ad.callout.api.impl.MethodNameCalloutInstance.execute(MethodNameCalloutInstance.java:120)
	at org.adempiere.ad.callout.api.impl.CalloutExecutor.execute(CalloutExecutor.java:260)
	at org.adempiere.ad.callout.api.impl.CalloutExecutor.execute(CalloutExecutor.java:118)
	at org.compiere.model.GridTab.processCallout(GridTab.java:3322)
	at org.compiere.model.GridTab.dataNew(GridTab.java:1510)
	at org.compiere.apps.APanel.cmd_new(APanel.java:2226)
	at org.compiere.apps.APanel.actionPerformed(APanel.java:1992)
	at org.compiere.apps.AppsAction.actionPerformed(AppsAction.java:441)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException: null
	at org.compiere.model.CalloutOrder.bPartnerBill(CalloutOrder.java:668)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.compiere.model.CalloutEngine.lambda$createCalloutMethodExecutor$3(CalloutEngine.java:201)
	at org.compiere.model.CalloutEngine.start(CalloutEngine.java:71)
	... 45 common frames omitted
