### ISSUE TITLE
Can't open custom forms in swing anymore

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#4269]
### Is this a bug or feature request?
Bug follow up of
* https://github.com/metasfresh/metasfresh/issues/3772
* https://github.com/metasfresh/metasfresh/issues/4260

### What is the current behavior?
Can't open custom forms
#### Which are the steps to reproduce?
Try to open window 'File import'
### What is the expected or desired behavior?
Shall work

**Comment by metas-lc** [comment]
IT
opened Ladeprogramm für Import-Datei => opens OK
also tried some POS windows => opens OK

**Comment by teosarca** [comment]
note to IT:
* make sure windows opening, closing works in Swing
* no errors/exceptions related to windows are in console

**Comment by metas-ts** [comment]
:cherries: picked to `release` branch

**Comment by metas-lc** [comment]
IT
noticed warnings in console when:
- open a jasper process, e.g. Umsatzreport geschaftspartner

<details/>
2018-06-28 14:05:07.018  WARN 24869 --- [pool-5-thread-8] o.a.a.v.impl.GridTabValidationContext    : Possible invalid definition of GridTabValidationContext: windowNo=1, tabNo=-100, tableName=AD_Org

org.adempiere.exceptions.AdempiereException: Possible invalid definition of GridTabValidationContext: windowNo=1, tabNo=-100, tableName=AD_Org
	at org.adempiere.ad.validationRule.impl.GridTabValidationContext.<init>(GridTabValidationContext.java:59)
	at org.adempiere.ad.validationRule.impl.ValidationRuleFactory.createValidationContext(ValidationRuleFactory.java:224)
	at org.compiere.model.MLookup.<init>(MLookup.java:189)
	at org.compiere.model.GridField.createLookup(GridField.java:225)
	at org.compiere.model.GridField$1.get(GridField.java:154)
	at org.compiere.model.GridField$1.get(GridField.java:150)
	at org.adempiere.util.lang.ExtendedMemorizingSupplier.get(ExtendedMemorizingSupplier.java:65)
	at org.compiere.model.GridField.getLookup(GridField.java:259)
	at org.compiere.grid.ed.VEditorFactory.getEditor(VEditorFactory.java:166)
	at org.compiere.grid.ed.VEditorFactory.getEditor(VEditorFactory.java:68)
	at org.compiere.grid.ed.api.impl.SwingEditorFactory.getEditor(SwingEditorFactory.java:67)
	at de.metas.process.ui.ProcessParametersPanel.createEditorForField(ProcessParametersPanel.java:249)
	at de.metas.process.ui.ProcessParametersPanel.createEditors(ProcessParametersPanel.java:219)
	at de.metas.process.ui.ProcessParametersPanel.initEditors(ProcessParametersPanel.java:171)
	at de.metas.process.ui.ProcessParametersPanel.<init>(ProcessParametersPanel.java:123)
	at de.metas.process.ui.ProcessPanel.init(ProcessPanel.java:440)
	at de.metas.process.ui.ProcessPanel.<init>(ProcessPanel.java:138)
	at de.metas.process.ui.ProcessDialogBuilder.buildPanel(ProcessDialogBuilder.java:88)
	at de.metas.process.ui.ProcessFrame.<init>(ProcessFrame.java:59)
	at de.metas.process.ui.ProcessDialogBuilder.show(ProcessDialogBuilder.java:73)
	at org.compiere.apps.AMenuStartItem.startProcess(AMenuStartItem.java:331)
	at org.compiere.apps.AMenuStartItem.doInBackground(AMenuStartItem.java:196)
	at org.compiere.apps.AMenuStartItem.doInBackground(AMenuStartItem.java:53)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</details>

- open like 3 random windows, use close all windows (alle fenster schliessen)
<details/>
2018-06-28 14:08:33.692  WARN 24869 --- [WT-EventQueue-0] de.metas.process.ui.ProcessPanel         : Calling dispose again for de.metas.process.ui.ProcessPanel@57dfe1b2

java.lang.Exception: trace
	at de.metas.process.ui.ProcessPanel.dispose(ProcessPanel.java:414)
	at de.metas.process.ui.ProcessFrame.dispose(ProcessFrame.java:76)
	at org.compiere.apps.WindowManager.close(WindowManager.java:76)
	at org.compiere.apps.WindowMenu$1.actionPerformed(WindowMenu.java:152)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

</details>

.
The other windows seems fine. i'll check it again after https://github.com/metasfresh/metasfresh/issues/4295
