### ISSUE TITLE
Error when changing promised date in order

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#4313]
### Is this a bug or feature request?
bug
### What is the current behavior?
Error when changing promised date in order
#### Which are the steps to reproduce?
1. create a new sales order. Don't add lines!
2. change date promised or preparation date
=> Error Assumption failure: queries is not empty
<details/>
2018-07-03 10:56:30.863  INFO 17224 --- [WT-EventQueue-0] org.compiere.grid.ed.Calendar            : startTS=2018-07-03 23:59:00.0
2018-07-03 10:56:30.863  INFO 17224 --- [WT-EventQueue-0] org.compiere.grid.ed.Calendar            : displayType=16
2018-07-03 10:56:32.357  INFO 17224 --- [WT-EventQueue-0] org.compiere.grid.ed.VLookup             : M_HU_PI_Item_Product_ID - comboBoxChanged, ComboValue=null
2018-07-03 10:56:33.777 ERROR 17224 --- [WT-EventQueue-0] o.a.a.m.AnnotatedModelInterceptor        : Model interceptor method de.metas.material.dispo.commons.interceptor.C_Order#updateQtyAvailableToPromiseWhenPreparationDateIsChanged threw an exception.
You can disable this method with SysConfig InterceptorEnabled_de.metas.material.dispo.commons.interceptor.C_Order#updateQtyAvailableToPromiseWhenPreparationDateIsChanged='N' (with AD_Client_ID and AD_Org_ID=0!)
2018-07-03 10:56:33.805  WARN 17224 --- [WT-EventQueue-0] o.adempiere.ad.trx.api.impl.TrxManager   : AbstractTrxManager.call0 - caught class org.adempiere.exceptions.AdempiereException with message=Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
Bitte leiten Sie diese Meldung an metas weiter:

Assumption failure: queries is not empty
2018-07-03 10:56:33.805  WARN 17224 --- [WT-EventQueue-0] o.adempiere.ad.trx.api.impl.TrxManager   : AbstractTrxManager.call0 - caught class org.adempiere.exceptions.AdempiereException with message=Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
Bitte leiten Sie diese Meldung an metas weiter:

Assumption failure: queries is not empty
2018-07-03 10:56:33.806 ERROR 17224 --- [WT-EventQueue-0] org.compiere.model.GridTable             : Error while saving on GridTable[C_Order,WindowNo=3,Tab=0]
 Type: SaveError

org.adempiere.exceptions.AdempiereException: Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
Bitte leiten Sie diese Meldung an metas weiter:

Assumption failure: queries is not empty
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.adempiere.util.Check.mkEx(Check.java:108)
	at org.adempiere.util.Check.throwOrLogEx(Check.java:119)
	at org.adempiere.util.Check.assume(Check.java:163)
	at org.adempiere.util.Check.assumeNotEmpty(Check.java:342)
	at org.adempiere.util.Check.assumeNotEmpty(Check.java:326)
	at de.metas.material.dispo.commons.repository.AvailableToPromiseMultiQuery.<init>(AvailableToPromiseMultiQuery.java:82)
	at de.metas.material.dispo.commons.repository.AvailableToPromiseMultiQuery.<init>(AvailableToPromiseMultiQuery.java:38)
	at de.metas.material.dispo.commons.repository.AvailableToPromiseMultiQuery$AvailableToPromiseMultiQueryBuilder.build(AvailableToPromiseMultiQuery.java:77)
	at de.metas.material.dispo.commons.interceptor.OrderAvailableToPromiseTool.updateOrderLineRecords(OrderAvailableToPromiseTool.java:84)
	at de.metas.material.dispo.commons.interceptor.C_Order.updateQtyAvailableToPromiseWhenPreparationDateIsChanged(C_Order.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.executeNow0(AnnotatedModelInterceptor.java:611)
	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.executeNow(AnnotatedModelInterceptor.java:563)
	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.execute(AnnotatedModelInterceptor.java:521)
	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.execute(AnnotatedModelInterceptor.java:464)
	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.onModelChange(AnnotatedModelInterceptor.java:442)
	at org.adempiere.ad.modelvalidator.ModelInterceptor2ModelValidatorWrapper.modelChange(ModelInterceptor2ModelValidatorWrapper.java:123)
	at org.compiere.model.ModelValidationEngine.invokeModelChangeMethod(ModelValidationEngine.java:970)
	at org.compiere.model.ModelValidationEngine.invokeModelChangeMethods(ModelValidationEngine.java:947)
	at org.compiere.model.ModelValidationEngine.fireModelChange0(ModelValidationEngine.java:829)
	at org.compiere.model.ModelValidationEngine.lambda$fireModelChange$0(ModelValidationEngine.java:784)
	at org.compiere.model.ModelValidationEngine$1.run(ModelValidationEngine.java:806)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:596)
	at org.compiere.model.ModelValidationEngine.executeInTrx(ModelValidationEngine.java:801)
	at org.compiere.model.ModelValidationEngine.fireModelChange(ModelValidationEngine.java:784)
	at org.compiere.model.PO.fireModelChange(PO.java:4849)
	at org.compiere.model.PO.save0(PO.java:2825)
	at org.compiere.model.PO.access$100(PO.java:139)
	at org.compiere.model.PO$1.run(PO.java:2733)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:506)
	at org.compiere.model.PO.saveEx(PO.java:2727)
	at org.compiere.model.GridTable.dataSavePO(GridTable.java:2135)
	at org.compiere.model.GridTable.dataSave(GridTable.java:1450)
	at org.compiere.model.GridTab.dataSave(GridTab.java:1323)
	at org.compiere.apps.APanel.cmd_save(APanel.java:2363)
	at org.compiere.apps.APanel.actionPerformed(APanel.java:1966)
	at org.compiere.apps.AppsAction.actionPerformed(AppsAction.java:455)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

2018-07-03 10:56:33.814  WARN 17224 --- [WT-EventQueue-0] org.compiere.model.GridTable             : SaveError - Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
Bitte leiten Sie diese Meldung an metas weiter:

Assumption failure: queries is not empty
2018-07-03 10:56:33.814  INFO 17224 --- [WT-EventQueue-0] org.compiere.apps.ADialog                : SaveError - Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
Bitte leiten Sie diese Meldung an metas weiter:

Assumption failure: queries is not empty

</details>

### What is the expected or desired behavior?
no errors, order shall be saved

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* changing date promised is saved without errors (date of provisioning changed as well): OK
* changing date of provisioning is saved without errors (date promised is left as it was): OK

**Comment by metas-ts** [comment]
:cherries: picked to `release`
