### ISSUE TITLE
Error when creating a bpartner on the fly and not setting a name

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#4349]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you create a bpartner on the fly, in order, and don't set a name for a contact, you get an error, see below; but the name field is not marked as mandatory (and was not mandatory before):

<details/>
{timestamp: 1531128922414, status: 500, error: "Internal Server Error",…}
error
:
"Internal Server Error"
exception
:
"org.adempiere.exceptions.DBException"
message
:
"ERROR: null value in column "name" violates not-null constraint↵  Detail: Failing row contains (2188227, 1000000, 1000000, Y, 2018-07-09 11:35:22+02, 2188223, 2018-07-09 11:35:22+02, 2188223, null, null, null, null, null, 2156430, N, null, null, null, null, null, null, null, null, null, null, null, null, null, E, Y, null, null, noname, null, N, N, null, null, null, N, N, null, A, null, null, null, null, null, null, null, null, null, null, null, N, null, N, Y, null, null, N, null, N, Y, null, null, null, N, N, N, N, N, N, N, null).↵	SQL: INSERT INTO AD_User (AD_Client_ID,AD_Org_ID,AD_User_ID,C_BPartner_ID,Created,CreatedBy,IsActive,IsFullBPAccess,IsPurchaseContact,IsPurchaseContact_Default,NotificationType,Processing,Updated,UpdatedBy,Value) VALUES (1000000,1000000,nextval('ad_user_seq'),2156430,TO_TIMESTAMP('2018-07-09 11:35:22','YYYY-MM-DD HH24:MI:SS'),2188223,'Y','Y','Y','Y','E','N',TO_TIMESTAMP('2018-07-09 11:35:22','YYYY-MM-DD HH24:MI:SS'),2188223,'noname') RETURNING AD_User_ID"
path
:
"/rest/api/window/540327/1000000/processNewRecord"
status
:
500
timestamp
:
1531128922414
trace
:
[,…]
[0 … 99]
0
:
"org.adempiere.exceptions.DBException: ERROR: null value in column "name" violates not-null constraint"
1
:
"  Detail: Failing row contains (2188227, 1000000, 1000000, Y, 2018-07-09 11:35:22+02, 2188223, 2018-07-09 11:35:22+02, 2188223, null, null, null, null, null, 2156430, N, null, null, null, null, null, null, null, null, null, null, null, null, null, E, Y, null, null, noname, null, N, N, null, null, null, N, N, null, A, null, null, null, null, null, null, null, null, null, null, null, N, null, N, Y, null, null, N, null, N, Y, null, null, null, N, N, N, N, N, N, N, null)."
2
:
"	SQL: INSERT INTO AD_User (AD_Client_ID,AD_Org_ID,AD_User_ID,C_BPartner_ID,Created,CreatedBy,IsActive,IsFullBPAccess,IsPurchaseContact,IsPurchaseContact_Default,NotificationType,Processing,Updated,UpdatedBy,Value) VALUES (1000000,1000000,nextval('ad_user_seq'),2156430,TO_TIMESTAMP('2018-07-09 11:35:22','YYYY-MM-DD HH24:MI:SS'),2188223,'Y','Y','Y','Y','E','N',TO_TIMESTAMP('2018-07-09 11:35:22','YYYY-MM-DD HH24:MI:SS'),2188223,'noname') RETURNING AD_User_ID"
3
:
"	at org.adempiere.exceptions.DBException.wrapIfNeeded(DBException.java:91)"
4
:
"	at org.compiere.util.DB.executeUpdate(DB.java:1007)"
5
:
"	at org.compiere.model.PO.saveNew(PO.java:3649)"
6
:
"	at org.compiere.model.PO.save0(PO.java:2830)"
7
:
"	at org.compiere.model.PO.access$100(PO.java:139)"
8
:
"	at org.compiere.model.PO$1.run(PO.java:2733)"
9
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)"
10
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)"
11
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
12
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
13
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
14
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
15
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:506)"
16
:
"	at org.compiere.model.PO.saveEx(PO.java:2727)"
17
:
"	at org.adempiere.model.POWrapper.save(POWrapper.java:799)"
18
:
"	at org.adempiere.model.InterfaceWrapperHelper.save(InterfaceWrapperHelper.java:595)"
19
:
"	at de.metas.bpartner.service.impl.BPartnerBL.createFromTemplate(BPartnerBL.java:348)"
20
:
"	at de.metas.ui.web.window.descriptor.factory.NewRecordDescriptorsProvider.lambda$new$0(NewRecordDescriptorsProvider.java:67)"
21
:
"	at de.metas.ui.web.window.controller.WindowRestController.lambda$null$13(WindowRestController.java:756)"
22
:
"	at de.metas.ui.web.window.model.DocumentCollection.lambda$forDocumentWritable$3(DocumentCollection.java:245)"
23
:
"	at de.metas.ui.web.window.model.DocumentCollection.forRootDocumentWritable(DocumentCollection.java:288)"
24
:
"	at de.metas.ui.web.window.model.DocumentCollection.forDocumentWritable(DocumentCollection.java:228)"
25
:
"	at de.metas.ui.web.window.controller.WindowRestController.lambda$processRecord$14(WindowRestController.java:747)"
26
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$4.call(TrxCallableWrappers.java:193)"
27
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)"
28
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
29
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
30
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
31
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
32
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:498)"
33
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:475)"
34
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$0(Execution.java:194)"
35
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
36
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
37
:
"	at de.metas.ui.web.window.controller.Execution.callInNewExecution(Execution.java:88)"
38
:
"	at de.metas.ui.web.window.controller.WindowRestController.processRecord(WindowRestController.java:747)"
39
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
40
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
41
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
42
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
43
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
44
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
45
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
46
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
47
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
48
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
49
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
50
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
51
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
52
:
"	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
53
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
54
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
55
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
56
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
57
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
58
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
59
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
60
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
61
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
62
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
63
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
64
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
65
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
66
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
67
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
68
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
69
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
70
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
71
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)"
72
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
73
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
74
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
75
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
76
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
77
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
78
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
79
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
80
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
81
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
82
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
83
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
84
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
85
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
86
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
87
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
88
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
89
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
90
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
91
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
92
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
93
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
94
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
95
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
96
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
97
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
98
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
99
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
[100 … 132]
100
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
101
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
102
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
103
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
104
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
105
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
106
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
107
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
108
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
109
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
110
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
111
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
112
:
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
113
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
114
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
115
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
116
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
117
:
"	at java.lang.Thread.run(Thread.java:748)"
118
:
"Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "name" violates not-null constraint"
119
:
"  Detail: Failing row contains (2188227, 1000000, 1000000, Y, 2018-07-09 11:35:22+02, 2188223, 2018-07-09 11:35:22+02, 2188223, null, null, null, null, null, 2156430, N, null, null, null, null, null, null, null, null, null, null, null, null, null, E, Y, null, null, noname, null, N, N, null, null, null, N, N, null, A, null, null, null, null, null, null, null, null, null, null, null, N, null, N, Y, null, null, N, null, N, Y, null, null, null, N, N, N, N, N, N, N, null)."
120
:
"	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)"
121
:
"	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)"
122
:
"	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)"
123
:
"	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)"
124
:
"	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)"
125
:
"	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)"
126
:
"	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)"
127
:
"	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1418)"
128
:
"	at org.adempiere.sql.impl.CPreparedStatementProxy.executeQuery(CPreparedStatementProxy.java:123)"
129
:
"	at org.adempiere.sql.impl.CPreparedStatementProxy.executeQueryAndLogMigationScripts(CPreparedStatementProxy.java:130)"
130
:
"	at org.compiere.util.DB.executeUpdate(DB.java:920)"
131
:
"	... 113 more"
132
:
""
</details>

When i set a name for the user, the error did not pop up and the bpartner was created, but i could not access the sales order window for a while. 
#### Which are the steps to reproduce?
Try and see.

### What is the expected or desired behavior?
BPartner is created without error (if the contact name is mandatory now for creating a bpartner on the fly, pls mark the resp. field as such).

**Comment by metas-ts** [comment]
:cherries: picked to release `release`
