### ISSUE TITLE
Error Zooming from material receipt to HU tracing

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4365]
### Is this a bug or feature request?
Bug
### What is the current behavior?

![image](https://user-images.githubusercontent.com/1264789/42567806-4e46beaa-850b-11e8-8480-381fbe355cfb.png)

leads to 

<details>

```
java.lang.ClassCastException: java.lang.Integer cannot be cast to de.metas.ui.web.window.datatypes.LookupValue
	at de.metas.ui.web.handlingunits.trace.HuTraceQueryCreator.updateInOutIdFromParameter(HuTraceQueryCreator.java:270)
	at de.metas.ui.web.handlingunits.trace.HuTraceQueryCreator.updateQueryFromParams(HuTraceQueryCreator.java:108)
	at de.metas.ui.web.handlingunits.trace.HuTraceQueryCreator.createTraceQueryFromDocumentFilter0(HuTraceQueryCreator.java:97)
	at de.metas.ui.web.handlingunits.trace.HuTraceQueryCreator.createTraceQueryFromDocumentFilter(HuTraceQueryCreator.java:77)
	at de.metas.ui.web.handlingunits.trace.HUTraceResultExtender.getSql(HUTraceResultExtender.java:67)
	at de.metas.ui.web.document.filter.sql.SqlDocumentFilterConverter.getSql(SqlDocumentFilterConverter.java:75)
	at de.metas.ui.web.view.descriptor.SqlViewSelectionQueryBuilder.buildSqlWhereClause(SqlViewSelectionQueryBuilder.java:477)
	at de.metas.ui.web.view.descriptor.SqlViewSelectionQueryBuilder.buildSqlCreateSelection_WithoutGrouping(SqlViewSelectionQueryBuilder.java:272)
	at de.metas.ui.web.view.descriptor.SqlViewSelectionQueryBuilder.buildSqlCreateSelectionFrom(SqlViewSelectionQueryBuilder.java:207)
	at de.metas.ui.web.view.SqlViewRowIdsOrderedSelectionFactory.createOrderedSelection(SqlViewRowIdsOrderedSelectionFactory.java:104)
	at de.metas.ui.web.view.SqlViewDataRepository.createOrderedSelection(SqlViewDataRepository.java:183)
	at de.metas.ui.web.view.DefaultView.lambda$0(DefaultView.java:158)
	at org.adempiere.util.lang.ExtendedMemorizingSupplier.get(ExtendedMemorizingSupplier.java:65)
	at de.metas.ui.web.view.DefaultView.size(DefaultView.java:252)
	at de.metas.ui.web.view.ViewResult.<init>(ViewResult.java:162)
	at de.metas.ui.web.view.ViewResult.ofView(ViewResult.java:90)
	at de.metas.ui.web.view.ViewRestController.createView(ViewRestController.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
```

</details>

**Comment by metas-lc** [comment]
IT
1. create a new material receipt (purchase order -> receive HUs)
2. go to referenced documents, open Handling Unit Trace
=> window Handling Unit Trace opens, filtered on your material receipt, no errors OK
