### ISSUE TITLE
Create purchase orders action can only be used once

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#4385]
### Is this a bug or feature request?
Bug
### What is the current behavior?
You can use the Create purchase orders action only once, when trying a 2nd time you get an error.
#### Which are the steps to reproduce?
1. Setup a product and discount schema for a vendor so you can use the Create purchase orders action
2. Create a sales order for the product, and use the Create purchase orders modal for creating a purchase order, e.g. set a qty < qty in sales orderline
3. Click OK
4. Select the same orderline again and select the action again:

<details/>
{timestamp: 1531825927670, status: 500, error: "Internal Server Error",…}
error
:
"Internal Server Error"
exception
:
"org.adempiere.exceptions.AdempiereException"
message
:
"Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
↵Bitte leiten Sie diese Meldung an metas weiter:↵↵Assumption failure: adTableId > 0"
path
:
"/rest/api/process/ADP_540887/1002133/start"
status
:
500
timestamp
:
1531825927670
trace
:
[,…]
[0 … 99]
0
:
"org.adempiere.exceptions.AdempiereException: Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
"
1
:
"Bitte leiten Sie diese Meldung an metas weiter:"
2
:
""
3
:
"Assumption failure: adTableId > 0"
4
:
"	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)"
5
:
"	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)"
6
:
"	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)"
7
:
"	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)"
8
:
"	at org.adempiere.util.Check.mkEx(Check.java:110)"
9
:
"	at org.adempiere.util.Check.throwOrLogEx(Check.java:121)"
10
:
"	at org.adempiere.util.Check.assume(Check.java:168)"
11
:
"	at org.adempiere.util.Check.assume(Check.java:149)"
12
:
"	at org.adempiere.util.lang.impl.TableRecordReference.<init>(TableRecordReference.java:286)"
13
:
"	at org.adempiere.util.lang.impl.TableRecordReference.ofReferenced(TableRecordReference.java:173)"
14
:
"	at de.metas.purchasecandidate.purchaseordercreation.remotepurchaseitem.PurchaseItemRepository.loadPurchaseItem(PurchaseItemRepository.java:172)"
15
:
"	at de.metas.purchasecandidate.purchaseordercreation.remotepurchaseitem.PurchaseItemRepository.lambda$loadPurchaseItems$0(PurchaseItemRepository.java:165)"
16
:
"	at java.util.ArrayList.forEach(ArrayList.java:1257)"
17
:
"	at de.metas.purchasecandidate.purchaseordercreation.remotepurchaseitem.PurchaseItemRepository.loadPurchaseItems(PurchaseItemRepository.java:165)"
18
:
"	at de.metas.purchasecandidate.purchaseordercreation.remotepurchaseitem.PurchaseItemRepository$$FastClassBySpringCGLIB$$66ce8b97.invoke(<generated>)"
19
:
"	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)"
20
:
"	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)"
21
:
"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)"
22
:
"	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)"
23
:
"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)"
24
:
"	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)"
25
:
"	at de.metas.purchasecandidate.purchaseordercreation.remotepurchaseitem.PurchaseItemRepository$$EnhancerBySpringCGLIB$$cfdfb93d.loadPurchaseItems(<generated>)"
26
:
"	at de.metas.purchasecandidate.PurchaseCandidateRepository.toPurchaseCandidate(PurchaseCandidateRepository.java:414)"
27
:
"	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)"
28
:
"	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)"
29
:
"	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)"
30
:
"	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)"
31
:
"	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)"
32
:
"	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)"
33
:
"	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)"
34
:
"	at de.metas.purchasecandidate.PurchaseCandidateRepository.getAllByIds(PurchaseCandidateRepository.java:143)"
35
:
"	at de.metas.purchasecandidate.PurchaseCandidateRepository$$FastClassBySpringCGLIB$$cfe72433.invoke(<generated>)"
36
:
"	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)"
37
:
"	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)"
38
:
"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)"
39
:
"	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)"
40
:
"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)"
41
:
"	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)"
42
:
"	at de.metas.purchasecandidate.PurchaseCandidateRepository$$EnhancerBySpringCGLIB$$c60fc491.getAllByIds(<generated>)"
43
:
"	at de.metas.purchasecandidate.PurchaseDemandWithCandidatesService.getExistingPurchaseCandidatesGroups(PurchaseDemandWithCandidatesService.java:128)"
44
:
"	at de.metas.purchasecandidate.PurchaseDemandWithCandidatesService.getOrCreatePurchaseCandidatesGroups(PurchaseDemandWithCandidatesService.java:96)"
45
:
"	at de.metas.ui.web.order.sales.purchasePlanning.view.PurchaseViewFactoryTemplate.createView(PurchaseViewFactoryTemplate.java:179)"
46
:
"	at de.metas.ui.web.order.sales.purchasePlanning.view.PurchaseViewFactoryTemplate.createView(PurchaseViewFactoryTemplate.java:60)"
47
:
"	at de.metas.ui.web.view.ViewsRepository.createView(ViewsRepository.java:260)"
48
:
"	at sun.reflect.GeneratedMethodAccessor328.invoke(Unknown Source)"
49
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
50
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
51
:
"	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)"
52
:
"	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)"
53
:
"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)"
54
:
"	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)"
55
:
"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)"
56
:
"	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)"
57
:
"	at com.sun.proxy.$Proxy119.createView(Unknown Source)"
58
:
"	at de.metas.ui.web.process.adprocess.ADProcessPostProcessService.createResultAction(ADProcessPostProcessService.java:321)"
59
:
"	at de.metas.ui.web.process.adprocess.ADProcessPostProcessService.postProcess(ADProcessPostProcessService.java:102)"
60
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.executeADProcess(ADProcessInstanceController.java:291)"
61
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.startProcess(ADProcessInstanceController.java:262)"
62
:
"	at de.metas.ui.web.process.ProcessRestController.lambda$null$8(ProcessRestController.java:261)"
63
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.forProcessInstanceWritable(ADProcessInstancesRepository.java:419)"
64
:
"	at de.metas.ui.web.process.ProcessRestController.lambda$startProcess$9(ProcessRestController.java:260)"
65
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
66
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
67
:
"	at de.metas.ui.web.process.ProcessRestController.startProcess(ProcessRestController.java:259)"
68
:
"	at sun.reflect.GeneratedMethodAccessor427.invoke(Unknown Source)"
69
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
70
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
71
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
72
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
73
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
74
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
75
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
76
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
77
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
78
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
79
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
80
:
"	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
81
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
82
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
83
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
84
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
85
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
86
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
87
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
88
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
89
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
90
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
91
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
92
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
93
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
94
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
95
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
96
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
97
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
98
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
99
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)"
[100 … 146]
100
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
101
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
102
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
103
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
104
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
105
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
106
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
107
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
108
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
109
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
110
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
111
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
112
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
113
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
114
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
115
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
116
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
117
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
118
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
119
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
120
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
121
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
122
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
123
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
124
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
125
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
126
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
127
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
128
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
129
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
130
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
131
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
132
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
133
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
134
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
135
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
136
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
137
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
138
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
139
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
140
:
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
141
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
142
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
143
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
144
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
145
:
"	at java.lang.Thread.run(Thread.java:748)"
146
:
""
</details>

### What is the expected or desired behavior?
No error, the action shall be available for multiple usage.

**Comment by metas-dh** [comment]
Update: e2e 23.07.:
this worked fine again, no error when calling the action for the 2nd time; will test further with actualy using the action 2 or more times etc.
