### ISSUE TITLE
JSON Fehler "Der Kurier"

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4415]
### Is this a bug or feature request?
Bug
### What is the current behavior?

API base-URL: "https://leoz.derkurier.de:13000/rs/api/v1"

<details>

```

Assumption failure: Parameter sector may not be empty
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at reflect.Constructor.newInstance(Constructor.java:423)
	at org.adempiere.util.Check.mkEx(Check.java:108)
	at org.adempiere.util.Check.throwOrLogEx(Check.java:119)
	at org.adempiere.util.Check.assume(Check.java:163)
	at org.adempiere.util.Check.assumeNotEmpty(Check.java:309)
	at org.adempiere.util.Check.assumeNotEmpty(Check.java:293)
	at de.metas.shipper.gateway.derkurier.restapi.models.Participant.<init>(Participant.java:89)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at reflect.Constructor.newInstance(Constructor.java:423)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:274)
	... 33 more
"
```

</details>

### What is the expected or desired behavior?

shall be lenient with empty `sector` value

**Comment by metas-ts** [comment]
tested on customer dev instance
