### ISSUE TITLE
Report Revenue Business Partner without Attributes

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4418]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the report Business Partner Revenue does not show the Attributes anymore.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Please fix. Attributes shall be shown if available.

**Comment by cristinamghita** [comment]
### Except for that code change, we need also to add the attributes in M_ShipmentSchedule_AttributeConfig
![image](https://user-images.githubusercontent.com/15378036/43638987-6228fbfc-9723-11e8-873c-fb31f2d2b5dc.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

could not post / create manual invoices including attributes, bc. https://github.com/metasfresh/metasfresh/issues/4426

**Comment by metas-dh** [comment]
problems:
* Report Business Partner revenue is not working anymore in swing, #4464
* in WebUI running a report causes error: 

<details>

```
{timestamp: 1533625569949, status: 500, error: "Internal Server Error",…}
error
:
"Internal Server Error"
exception
:
"org.adempiere.exceptions.AdempiereException"
message
:
"ClassCastException: org.compiere.report.ReportStarter cannot be cast to de.metas.process.JavaProcess"
path
:
"/rest/api/process/ADP_540754/1001671"
status
:
500
timestamp
:
1533625569949
trace
:
[,…]
[0 … 99]
0
:
"org.adempiere.exceptions.AdempiereException: ClassCastException: org.compiere.report.ReportStarter cannot be cast to de.metas.process.JavaProcess"
1
:
"	at org.adempiere.exceptions.AdempiereException.wrapIfNeeded(AdempiereException.java:89)"
2
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:865)"
3
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
4
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
5
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
6
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:498)"
7
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:475)"
8
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$0(Execution.java:194)"
9
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
10
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
11
:
"	at de.metas.ui.web.window.controller.Execution.callInNewExecution(Execution.java:88)"
12
:
"	at de.metas.ui.web.process.ProcessRestController.processParametersChangeEvents(ProcessRestController.java:231)"
13
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
14
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
15
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
16
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
17
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
18
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
19
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
20
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
21
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
22
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
23
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
24
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
25
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
26
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)"
27
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
28
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
29
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
30
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
31
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
32
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
33
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
34
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
35
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
36
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
37
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
38
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
39
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
40
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
41
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
42
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
43
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)"
44
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
45
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
46
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
47
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
48
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
49
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
50
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
51
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
52
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
53
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
54
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
55
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
56
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
57
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
58
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
59
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
60
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
61
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
62
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
63
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
64
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
65
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
66
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
67
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
68
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
69
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
70
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
71
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
72
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
73
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
74
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
75
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
76
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
77
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
78
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
79
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
80
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
81
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
82
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
83
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
84
:
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
85
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
86
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
87
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
88
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
89
:
"	at java.lang.Thread.run(Thread.java:748)"
90
:
"Caused by: java.lang.ClassCastException: org.compiere.report.ReportStarter cannot be cast to de.metas.process.JavaProcess"
91
:
"	at de.metas.process.JavaProcess.currentInstance(JavaProcess.java:135)"
92
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.updateParametersDocumentFromJavaProcessAnnotatedFields(ADProcessInstanceController.java:229)"
93
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.processParameterValueChanges(ADProcessInstanceController.java:224)"
94
:
"	at de.metas.ui.web.process.ProcessRestController.lambda$null$6(ProcessRestController.java:237)"
95
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.forProcessInstanceWritable(ADProcessInstancesRepository.java:419)"
96
:
"	at de.metas.ui.web.process.ProcessRestController.lambda$processParametersChangeEvents$7(ProcessRestController.java:235)"
97
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$4.call(TrxCallableWrappers.java:193)"
98
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)"
99
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
[100 … 101]
100
:
"	... 87 more"
101
:
""
```

</details>

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

1. reports working in Swing & WebUI: OK
2. attributes shown if available:
* no attributes set: report header: all, OK
* 1 attribute set, e.g. Bio: report header: Bio, OK
* more attributes set, e.g. country, Bio, AdR: all shown in report header, OK
