### ISSUE TITLE
Advanced BLs to create inventory lines

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4448]
### Is this a bug or feature request?
FR
### What is the current behavior?
There is some process to create inventory lines which the user can then use to do an inventory

### What is the expected or desired behavior?

this issue is about having a process to generate drafted inventories for the users to fill out

* there was the idea to create those drafted inventories nightly; it came from the assumtption that the line-creating process takes long to finish. if it's quick, we don't have to do it at night time
* we need two different BLs to create different sorts of inventory lines:
  * BL I - "daily inventory" - how to get the inventory lines:
    * list the locations, ordered by the date they were last inventoriesed
	* oldest first
	  * if there are >1 products in one locator, then take the date from the one that wasn't inventorized for the longest time
	* take the first (i.e. "oldest") 30 locators
	* make lines for all products from those locators
  * BL II - "high-price inventory" - how to get the inventory lines for that:
	* get all products that have a priceActual of > 1000€
	* get their locators
	* get all products from their locators
	  * sidenote: if an inventory was made in this way, ofc that inventory-date counts for BL I too
* the "30" and "1000€" shall be proccess parameters.
* there can be 2 different AD_Processes that invoke those two different BLs
* don't limit the inventory lines to a particular warehouse;
i.e. it needs to be possible not to set a warehouse in the M_Inventory (header) record,
and then the inventory lines can belong to any warehouse
* the lines shall by default be orderd by warehouse and locator.
* make sure that the "normal" existing process also still works..maybe create a commpon SPI like "InventoryLinesCreator" and have the old&new BLs implement it

**Comment by cristinamghita** [comment]
**Dev test**
* New process
![image](https://user-images.githubusercontent.com/15378036/44120228-67cbeef2-a024-11e8-86a0-1937549ed4d7.png)
* Two ways to use it:
  * parameter Qty is for setting maximum locators
  * parameter MinValue is for setting the minimum price
![image](https://user-images.githubusercontent.com/15378036/44120288-998787ee-a024-11e8-835c-27cd274fc54f.png)
And the result:
![image](https://user-images.githubusercontent.com/15378036/44120315-acec932e-a024-11e8-9cb5-e82a18ac3303.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. BL I - "daily inventory" - how to get the inventory lines:
    * list the locations, ordered by the date they were last inventoriesed: 
=> date is not displayed in the inventory lines, so i'm not sure how to test that? HUs were displayed in order lowest value (=oldest) first, so i think it's ok, but i tested with a new db and not many existing HUs, so might need to test that again
    * oldest first: the HUs with the lowest value (oldest one) was displayed first for every location, so afais this is **OK**
	  * if there are >1 products in one locator, then take the date from the one that wasn't inventorized for the longest time: again, not sure this is ok since the date is not displayed, but the HUs were displayed in order lowest value (=oldest) first, so afais this is **OK**
	* take the first (i.e. "oldest") 30 locators: have to test further bc i did not have that many locators in the test db
	* make lines for all products from those locators: **OK**
2.  BL II - "high-price inventory" - how to get the inventory lines for that:
	* get all products that have a priceActual of > 1000€: set min. value 1.000, but got lines for all products, not just the one where the PriceStd 1.001€ was set: **NOK**
	* get their locators: **OK**
	* get all products from their locators: not sure i understand this correctly: all other products from their locators? also the ones where  priceActual < 1000€?
	  * sidenote: if an inventory was made in this way, ofc that inventory-date counts for BL I too

3. the "30" and "1000€" shall be proccess parameters: atm the parameters are
* Menge (qty) with default value 0: imho that's really confusing for the user, qty of what? and maybe leave the value empty instead of 0? also trl is missing, same in en_US
* Min. Wert (min value) with default value 0,00: trl is missing, same in en_US

4. don't limit the inventory lines to a particular warehouse;
i.e. it needs to be possible not to set a warehouse in the M_Inventory (header) record,
and then the inventory lines can belong to any warehouse: **OK**

5. the lines shall by default be orderd by warehouse and locator: **OK** 

6. make sure that the "normal" existing process also still works: `Prepare Inventorylines` not working anymore, when you try to run it (with or without params) you get an error: **NOK**

<details/>
```
{timestamp: 1534938944863, status: 500, error: "Internal Server Error",…}
error
:
"Internal Server Error"
exception
:
"org.adempiere.exceptions.AdempiereException"
message
:
"Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
↵Bitte leiten Sie diese Meldung an metas weiter:↵↵Assumption failure: repoId > 0 but it was 0"
path
:
"/rest/api/process/ADP_540935/1003298/start"
status
:
500
timestamp
:
1534938944863
trace
:
[,…]
[0 … 99]
0
:
"org.adempiere.exceptions.AdempiereException: Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
"
1
:
"Bitte leiten Sie diese Meldung an metas weiter:"
2
:
""
3
:
"Assumption failure: repoId > 0 but it was 0"
4
:
"	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)"
5
:
"	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)"
6
:
"	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)"
7
:
"	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)"
8
:
"	at org.adempiere.util.Check.mkEx(Check.java:112)"
9
:
"	at org.adempiere.util.Check.throwOrLogEx(Check.java:123)"
10
:
"	at org.adempiere.util.Check.assumeGreaterThanZero(Check.java:418)"
11
:
"	at org.adempiere.warehouse.WarehouseId.<init>(WarehouseId.java:65)"
12
:
"	at org.adempiere.warehouse.WarehouseId.ofRepoId(WarehouseId.java:42)"
13
:
"	at de.metas.handlingunits.inventory.process.M_Inventory_CreateCountLinesFromHU.createStrategy(M_Inventory_CreateCountLinesFromHU.java:47)"
14
:
"	at de.metas.handlingunits.inventory.process.M_Inventory_CreateCountLinesFromHU.createStrategy(M_Inventory_CreateCountLinesFromHU.java:36)"
15
:
"	at de.metas.handlingunits.inventory.process.DraftInventoryBase.doIt(DraftInventoryBase.java:59)"
16
:
"	at de.metas.process.JavaProcess.startProcess(JavaProcess.java:295)"
17
:
"	at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:564)"
18
:
"	at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:460)"
19
:
"	at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:50)"
20
:
"	at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:224)"
21
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)"
22
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)"
23
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
24
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
25
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
26
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
27
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:506)"
28
:
"	at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:286)"
29
:
"	at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:171)"
30
:
"	at de.metas.process.ProcessExecutor.access$1100(ProcessExecutor.java:50)"
31
:
"	at de.metas.process.ProcessExecutor$Builder.executeSync(ProcessExecutor.java:651)"
32
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.executeADProcess(ADProcessInstanceController.java:332)"
33
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.startProcess(ADProcessInstanceController.java:309)"
34
:
"	at de.metas.ui.web.process.ProcessRestController.lambda$null$8(ProcessRestController.java:261)"
35
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.forProcessInstanceWritable(ADProcessInstancesRepository.java:419)"
36
:
"	at de.metas.ui.web.process.ProcessRestController.lambda$startProcess$9(ProcessRestController.java:260)"
37
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
38
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
39
:
"	at de.metas.ui.web.process.ProcessRestController.startProcess(ProcessRestController.java:259)"
40
:
"	at sun.reflect.GeneratedMethodAccessor358.invoke(Unknown Source)"
41
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
42
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
43
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
44
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
45
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
46
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
47
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
48
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
49
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
50
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
51
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
52
:
"	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
53
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
54
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
55
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
56
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
57
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
58
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
59
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
60
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
61
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
62
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
63
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
64
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
65
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
66
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
67
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
68
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
69
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
70
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
71
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)"
72
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
73
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
74
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
75
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
76
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
77
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
78
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
79
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
80
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
81
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
82
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
83
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
84
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
85
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
86
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
87
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
88
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
89
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
90
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
91
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
92
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
93
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
94
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
95
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
96
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
97
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
98
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
99
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
[100 … 118]
100
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
101
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
102
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
103
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
104
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
105
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
106
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
107
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
108
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
109
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
110
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
111
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
112
:
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
113
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
114
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
115
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
116
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
117
:
"	at java.lang.Thread.run(Thread.java:748)"
118
:
""
```
</details>

**Comment by cristinamghita** [comment]
> 2.  BL II - "high-price inventory" - how to get the inventory lines for that:
	* get all products that have a priceActual of > 1000€: set min. value 1.000, but got lines for all products, not just the one where the PriceStd 1.001€ was set: **NOK**

Is intended like that. We filter for high price products, but we create lines for all the products that exists in the locators of those high price products.

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

2. BL II - "high-price inventory" - how to get the inventory lines for that:
   * get all products that have a priceActual of > 1000€: set min. value 1.000, but got lines for all products, not just the one where the PriceStd 1.001€ was set: that behaviour is intended, see above: **OK**
3. the "30" and "1000€" shall be proccess parameters: #4614 for trl / improving the names
6. make sure that the "normal" existing process also still works: `Prepare Inventorylines` working fine again, with or without params: **OK**
