### ISSUE TITLE
Cannot create a new request

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#4461]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Creating a new request is not possible, you get an error when trying (in New request, request or bpartner window):

<details>
{timestamp: 1533554405540, status: 404, error: "Not Found",…}
error
:
"Not Found"
exception
:
"de.metas.ui.web.window.exceptions.DocumentLayoutBuildException"
message
:
"No SQL fields found"
path
:
"/rest/api/process/ADP_540780/1000478/start"
status
:
404
timestamp
:
1533554405540
trace
:
["de.metas.ui.web.window.exceptions.DocumentLayoutBuildException: No SQL fields found",…]
[0 … 99]
0
:
"de.metas.ui.web.window.exceptions.DocumentLayoutBuildException: No SQL fields found"
1
:
"	at de.metas.ui.web.window.exceptions.DocumentLayoutBuildException.wrapIfNeeded(DocumentLayoutBuildException.java:59)"
2
:
"	at de.metas.ui.web.window.descriptor.factory.standard.DefaultDocumentDescriptorFactory.getDocumentDescriptor(DefaultDocumentDescriptorFactory.java:60)"
3
:
"	at de.metas.ui.web.window.model.DocumentCollection.getDocumentEntityDescriptor(DocumentCollection.java:140)"
4
:
"	at de.metas.ui.web.window.model.DocumentCollection.createRootDocument(DocumentCollection.java:321)"
5
:
"	at de.metas.ui.web.window.model.DocumentCollection.forRootDocumentWritable(DocumentCollection.java:258)"
6
:
"	at de.metas.ui.web.window.model.DocumentCollection.forDocumentWritable(DocumentCollection.java:228)"
7
:
"	at de.metas.ui.web.request.process.WEBUI_CreateRequest.createRequestFromBPartner(WEBUI_CreateRequest.java:93)"
8
:
"	at de.metas.ui.web.request.process.WEBUI_CreateRequest.doIt(WEBUI_CreateRequest.java:66)"
9
:
"	at de.metas.process.JavaProcess.startProcess(JavaProcess.java:279)"
10
:
"	at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:564)"
11
:
"	at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:460)"
12
:
"	at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:50)"
13
:
"	at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:224)"
14
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.runOutOfTransaction(AbstractTrxManager.java:934)"
15
:
"	at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:282)"
16
:
"	at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:171)"
17
:
"	at de.metas.process.ProcessExecutor.access$1100(ProcessExecutor.java:50)"
18
:
"	at de.metas.process.ProcessExecutor$Builder.executeSync(ProcessExecutor.java:651)"
19
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.executeADProcess(ADProcessInstanceController.java:332)"
20
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.startProcess(ADProcessInstanceController.java:309)"
21
:
"	at de.metas.ui.web.process.ProcessRestController.lambda$null$8(ProcessRestController.java:261)"
22
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.forProcessInstanceWritable(ADProcessInstancesRepository.java:419)"
23
:
"	at de.metas.ui.web.process.ProcessRestController.lambda$startProcess$9(ProcessRestController.java:260)"
24
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
25
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
26
:
"	at de.metas.ui.web.process.ProcessRestController.startProcess(ProcessRestController.java:259)"
27
:
"	at sun.reflect.GeneratedMethodAccessor351.invoke(Unknown Source)"
28
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
29
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
30
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
31
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
32
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
33
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
34
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
35
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
36
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
37
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
38
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
39
:
"	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
40
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
41
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
42
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
43
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
44
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
45
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
46
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
47
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
48
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
49
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
50
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
51
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
52
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
53
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
54
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
55
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
56
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
57
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
58
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)"
59
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
60
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
61
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
62
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
63
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
64
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
65
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
66
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
67
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
68
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
69
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
70
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
71
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
72
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
73
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
74
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
75
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
76
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
77
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
78
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
79
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
80
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
81
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
82
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
83
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
84
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
85
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
86
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
87
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
88
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
89
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
90
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
91
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
92
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
93
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
94
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
95
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
96
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
97
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
98
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
99
:
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
[100 … 131]
100
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
101
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
102
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
103
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
104
:
"	at java.lang.Thread.run(Thread.java:748)"
105
:
"Caused by: org.adempiere.exceptions.AdempiereException: No SQL fields found"
106
:
"	at de.metas.ui.web.window.descriptor.sql.SqlDocumentEntityDataBindingDescriptor$Builder.buildSqlSelects(SqlDocumentEntityDataBindingDescriptor.java:294)"
107
:
"	at de.metas.ui.web.window.descriptor.sql.SqlDocumentEntityDataBindingDescriptor$Builder.getSqlSelectAll(SqlDocumentEntityDataBindingDescriptor.java:281)"
108
:
"	at de.metas.ui.web.window.descriptor.sql.SqlDocumentEntityDataBindingDescriptor$Builder.access$400(SqlDocumentEntityDataBindingDescriptor.java:237)"
109
:
"	at de.metas.ui.web.window.descriptor.sql.SqlDocumentEntityDataBindingDescriptor.<init>(SqlDocumentEntityDataBindingDescriptor.java:113)"
110
:
"	at de.metas.ui.web.window.descriptor.sql.SqlDocumentEntityDataBindingDescriptor.<init>(SqlDocumentEntityDataBindingDescriptor.java:58)"
111
:
"	at de.metas.ui.web.window.descriptor.sql.SqlDocumentEntityDataBindingDescriptor$Builder.getOrBuild(SqlDocumentEntityDataBindingDescriptor.java:264)"
112
:
"	at de.metas.ui.web.window.descriptor.sql.SqlDocumentEntityDataBindingDescriptor$Builder.getOrBuild(SqlDocumentEntityDataBindingDescriptor.java:237)"
113
:
"	at de.metas.ui.web.window.descriptor.DocumentEntityDescriptor$Builder.getOrBuildDataBinding(DocumentEntityDescriptor.java:763)"
114
:
"	at de.metas.ui.web.window.descriptor.DocumentEntityDescriptor$Builder.access$800(DocumentEntityDescriptor.java:470)"
115
:
"	at de.metas.ui.web.window.descriptor.DocumentEntityDescriptor.<init>(DocumentEntityDescriptor.java:153)"
116
:
"	at de.metas.ui.web.window.descriptor.DocumentEntityDescriptor.<init>(DocumentEntityDescriptor.java:84)"
117
:
"	at de.metas.ui.web.window.descriptor.DocumentEntityDescriptor$Builder.build(DocumentEntityDescriptor.java:530)"
118
:
"	at de.metas.ui.web.window.descriptor.factory.standard.DefaultDocumentDescriptorLoader.load(DefaultDocumentDescriptorLoader.java:128)"
119
:
"	at de.metas.ui.web.window.descriptor.factory.standard.DefaultDocumentDescriptorFactory.lambda$getDocumentDescriptor$0(DefaultDocumentDescriptorFactory.java:56)"
120
:
"	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5065)"
121
:
"	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)"
122
:
"	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)"
123
:
"	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)"
124
:
"	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)"
125
:
"	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)"
126
:
"	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060)"
127
:
"	at org.compiere.util.CCache.get(CCache.java:488)"
128
:
"	at org.compiere.util.CCache.getOrLoad(CCache.java:522)"
129
:
"	at de.metas.ui.web.window.descriptor.factory.standard.DefaultDocumentDescriptorFactory.getDocumentDescriptor(DefaultDocumentDescriptorFactory.java:56)"
130
:
"	... 102 more"
131
:
""
</details>

#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Shall work.

**Comment by metas-ts** [comment]
:cherries: picked to the `release` branch
