### ISSUE TITLE
Cannot create a new contact in Swing Client

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#4462]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Creating a new user / contact n Swing Client is not possible; when trying to save you get

<details>

```
> 2018-08-06 15:54:18.114 ERROR 19237 --- [WT-EventQueue-0] org.compiere.model.GridTab               : GridTab{TabNo=7, TabLevel=1, Name=Nutzer / Kontakt, AD_Tab_ID=496, TableName=AD_User} - row=0
> 
> org.adempiere.exceptions.DBException: ERROR: column "issystemuser" does not exist
>   Position: 1647
> 	SQL: SELECT * FROM (SELECT ? AS AD_Client_ID, ? AS AD_Org_ID, ? AS C_BPartner_ID, ? AS C_Greeting_ID, ? AS Firstname, ? AS Lastname, ? AS Name, NULL::text AS Description, NULL::text AS Comments, ? AS IsActive, ? AS IsDefaultContact, NULL AS Fresh_xmas_Gift, NULL::text AS EMail, ? AS IsMFProcurementUser, NULL::text AS ProcurementPassword, NULL::text AS Title, NULL AS Birthday, NULL::text AS Phone, NULL::text AS Phone2, NULL::text AS Fax, NULL::integer AS C_Job_ID, NULL::integer AS C_BPartner_Location_ID, ? AS IsPurchaseContact, ? AS IsPurchaseContact_Default, ? AS IsSalesContact, ? AS IsSalesContact_Default, NULL AS IsInvoiceEmailEnabled, NULL::integer AS C_Printing_Queue_Recipient_ID, ? AS IsBillToContact_Default, ? AS IsShipToContact_Default, ? AS IsNewsletter, NULL::integer AS AD_OrgTrx_ID, NULL::integer AS Supervisor_ID, ? AS Processing, NULL::text AS Password, NULL::integer AS AD_User_ID, NULL::text AS EMailUserPW, NULL::text AS EMailUser, NULL::text AS EMailVerify, NULL AS EMailVerifyDate, ? AS NotificationType, ? AS IsFullBPAccess, NULL AS Updated, NULL::integer AS UpdatedBy, NULL::text AS ContactLimitationReason, NULL AS Created, NULL::integer AS CreatedBy, NULL::text AS Registry, NULL::text AS MobilePhone, NULL::text AS Included_Tab_ID, ? AS IsInPayroll, ? AS IsAccountLocked, ? AS IsSubjectMatterContact, NULL AS ContactLimitation, NULL::text AS LockedFromIP, ? AS LoginFailureCount, NULL AS LoginFailureDate, NULL AS DelDate, NULL::text AS passwordportal, NULL::text AS Value, ? AS UnlockAccount, NULL::text AS UserPIN, NULL AS ConnectionProfile, ? AS Fresh_Gift) AD_User WHERE IsSystemUser='Y' AND EMail IS NOT NULL
> 	SQL params: [1000000, 1000000, 2156425, 10030, tessi, testi, testi, tessi, Y, false, false, true, true, true, true, false, false, false, N, N, true, false, N, false, 0, N, false]
> 	at org.compiere.model.MIndexTable.isWhereClauseMatched(MIndexTable.java:576)
> 	at org.compiere.model.MIndexTable.isMatched(MIndexTable.java:438)
> 	at org.compiere.model.MIndexTable.getAffectedIndexes(MIndexTable.java:620)
> 	at org.compiere.model.MIndexTable.getBeforeChangeWarning(MIndexTable.java:630)
> 	at org.compiere.model.GridTab.dataSave(GridTab.java:1314)
> 	at org.compiere.apps.APanel.cmd_save(APanel.java:2363)
> 	at org.compiere.apps.APanel.actionPerformed(APanel.java:1966)
> 	at org.compiere.apps.AppsAction.actionPerformed(AppsAction.java:455)
> 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> 	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
> 	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
> 	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
> 	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
> 	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
> 	at java.awt.Component.processMouseEvent(Component.java:6533)
> 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
> 	at java.awt.Component.processEvent(Component.java:6298)
> 	at java.awt.Container.processEvent(Container.java:2236)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4889)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2294)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
> 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
> 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2280)
> 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
> 	at java.awt.EventQueue$4.run(EventQueue.java:731)
> 	at java.awt.EventQueue$4.run(EventQueue.java:729)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> Caused by: org.postgresql.util.PSQLException: ERROR: column "issystemuser" does not exist
>   Position: 1647
> 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
> 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
> 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
> 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
> 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
> 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
> 	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)
> 	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1418)
> 	at org.adempiere.sql.impl.CPreparedStatementProxy.executeQuery(CPreparedStatementProxy.java:123)
> 	at org.compiere.model.MIndexTable.isWhereClauseMatched(MIndexTable.java:570)
> 	... 44 common frames omitted
> 
> 2018-08-06 15:54:18.134  INFO 19237 --- [WT-EventQueue-0] org.compiere.apps.ADialog                : SaveIgnored - null
> 2018-08-06 15:54:20.458  INFO 19237 --- [WT-EventQueue-0] org.compiere.grid.ed.VLookup             : AD_Client_ID (Text) AD_Client_ID = 1000000 - metasfresh
```
</details>

#### Which are the steps to reproduce?
Try and see.

### What is the expected or desired behavior?
Shall work.

**Comment by metas-lc** [comment]
added missing fields in User tab from BPartner and User window

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* creating a new contact in Swing works fine: OK
* creating a new contact in WebUI not working anymore: NOK

<details>

```
{timestamp: 1533715150985, status: 404, error: "Not Found",…}
error
:
"Not Found"
exception
:
"de.metas.ui.web.window.exceptions.DocumentNotFoundException"
message
:
"No document found for /W123/2156425/T496/R2188234"
path
:
"/rest/api/window/123/2156425/496/2188234"
status
:
404
timestamp
:
1533715150985
trace
:
[,…]
0
:
"de.metas.ui.web.window.exceptions.DocumentNotFoundException: No document found for /W123/2156425/T496/R2188234"
1
:
"	at de.metas.ui.web.window.model.HighVolumeReadWriteIncludedDocumentsCollection.getDocumentById(HighVolumeReadWriteIncludedDocumentsCollection.java:203)"
2
:
"	at de.metas.ui.web.window.model.Document.getIncludedDocument(Document.java:1505)"
3
:
"	at de.metas.ui.web.window.controller.WindowRestController.lambda$getData$4(WindowRestController.java:249)"
4
:
"	at de.metas.ui.web.window.model.DocumentCollection.forRootDocumentReadonly(DocumentCollection.java:218)"
5
:
"	at de.metas.ui.web.window.controller.WindowRestController.getData(WindowRestController.java:237)"
6
:
"	at de.metas.ui.web.window.controller.WindowRestController.getData(WindowRestController.java:225)"
7
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
8
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
9
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
10
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
11
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
12
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
13
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
14
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
15
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
16
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
17
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
18
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
19
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
20
:
"	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
21
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
22
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
23
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
24
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
25
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
26
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
27
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
28
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
29
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
30
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
31
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
32
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
33
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
34
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
35
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
36
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
37
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
38
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
39
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)"
40
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
41
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
42
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
43
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
44
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
45
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
46
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
47
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
48
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
49
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
50
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
51
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
52
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
53
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
54
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
55
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
56
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
57
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
58
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
59
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
60
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
61
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
62
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
63
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
64
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
65
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
66
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
67
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
68
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
69
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
70
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
71
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
72
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
73
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
74
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
75
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
76
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
77
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
78
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
79
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
80
:
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
81
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
82
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
83
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
84
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
85
:
"	at java.lang.Thread.run(Thread.java:748)"
86
:
""
```

</details>

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

creating new contact in bpartner works fine
* in Swing: OK
* in WebUI: OK

**Comment by metas-ts** [comment]
FYI,  picked https://github.com/metasfresh/metasfresh/issues/4462 to the release branch
