### ISSUE TITLE
Cannot create letter

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#4499]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you try to create a letter, an error pops up.
#### Which are the steps to reproduce?
1. Open a sales order (window where user_ID is set in the Header), and run action `Letter`
2. In the overlay, click the `Create` button:

<details/>

```
{timestamp: 1534835742348, status: 500, error: "Internal Server Error",…}
error
:
"Internal Server Error"
exception
:
"org.adempiere.exceptions.AdempiereException"
message
:
"Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
↵Bitte leiten Sie diese Meldung an metas weiter:↵↵Assumption failure: repoId > 0 but it was -1"
path
:
"/rest/api/letter/5/complete"
status
:
500
timestamp
:
1534835742348
trace
:
[,…]
[0 … 99]
0
:
"org.adempiere.exceptions.AdempiereException: Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
"
1
:
"Bitte leiten Sie diese Meldung an metas weiter:"
2
:
""
3
:
"Assumption failure: repoId > 0 but it was -1"
4
:
"	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)"
5
:
"	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)"
6
:
"	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)"
7
:
"	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)"
8
:
"	at org.adempiere.util.Check.mkEx(Check.java:112)"
9
:
"	at org.adempiere.util.Check.throwOrLogEx(Check.java:123)"
10
:
"	at org.adempiere.util.Check.assumeGreaterThanZero(Check.java:418)"
11
:
"	at de.metas.letter.BoilerPlateId.<init>(BoilerPlateId.java:49)"
12
:
"	at de.metas.letter.BoilerPlateId.ofRepoId(BoilerPlateId.java:44)"
13
:
"	at de.metas.ui.web.letter.LetterRestController.createPDFData(LetterRestController.java:243)"
14
:
"	at de.metas.ui.web.letter.LetterRestController.complete0(LetterRestController.java:222)"
15
:
"	at de.metas.ui.web.letter.LetterRestController.lambda$null$0(LetterRestController.java:205)"
16
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)"
17
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
18
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
19
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
20
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
21
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:498)"
22
:
"	at de.metas.ui.web.letter.LetterRestController.lambda$complete$1(LetterRestController.java:205)"
23
:
"	at de.metas.ui.web.letter.LetterRestController.lambda$changeLetter$3(LetterRestController.java:284)"
24
:
"	at de.metas.ui.web.letter.WebuiLetterRepository$WebuiLetterEntry.compute(WebuiLetterRepository.java:126)"
25
:
"	at de.metas.ui.web.letter.WebuiLetterRepository.changeLetter(WebuiLetterRepository.java:83)"
26
:
"	at de.metas.ui.web.letter.LetterRestController.changeLetter(LetterRestController.java:282)"
27
:
"	at de.metas.ui.web.letter.LetterRestController.complete(LetterRestController.java:205)"
28
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
29
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
30
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
31
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
32
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
33
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
34
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
35
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
36
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
37
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
38
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
39
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
40
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
41
:
"	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)"
42
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)"
43
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
44
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
45
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
46
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
47
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
48
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
49
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
50
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
51
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
52
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
53
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
54
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
55
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
56
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
57
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
58
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
59
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
60
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)"
61
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
62
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
63
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
64
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
65
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
66
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
67
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
68
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
69
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
70
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
71
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
72
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
73
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
74
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
75
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
76
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
77
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
78
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
79
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
80
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
81
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
82
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
83
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
84
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
85
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
86
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
87
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
88
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
89
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
90
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
91
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
92
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
93
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
94
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
95
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
96
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
97
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
98
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
99
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
[100 … 107]
100
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
101
:
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
102
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
103
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
104
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
105
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
106
:
"	at java.lang.Thread.run(Thread.java:748)"
107
:
""
```` 

</details>

### What is the expected or desired behavior?
Shall work: you shall be able to select a report used for the letter.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

retested the case described above: NPE, NOK

<details/>

```
{timestamp: 1535093029563, status: 500, error: "Internal Server Error",…}
error
:
"Internal Server Error"
exception
:
"org.adempiere.exceptions.AdempiereException"
message
:
"NullPointerException: java.lang.NullPointerException"
path
:
"/rest/api/letter/2/complete"
status
:
500
timestamp
:
1535093029563
trace
:
["org.adempiere.exceptions.AdempiereException: NullPointerException: java.lang.NullPointerException",…]
[0 … 99]
0
:
"org.adempiere.exceptions.AdempiereException: NullPointerException: java.lang.NullPointerException"
1
:
"	at org.adempiere.exceptions.AdempiereException.wrapIfNeeded(AdempiereException.java:89)"
2
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:865)"
3
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
4
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
5
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
6
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:498)"
7
:
"	at de.metas.ui.web.letter.LetterRestController.lambda$complete$1(LetterRestController.java:205)"
8
:
"	at de.metas.ui.web.letter.LetterRestController.lambda$changeLetter$3(LetterRestController.java:284)"
9
:
"	at de.metas.ui.web.letter.WebuiLetterRepository$WebuiLetterEntry.compute(WebuiLetterRepository.java:126)"
10
:
"	at de.metas.ui.web.letter.WebuiLetterRepository.changeLetter(WebuiLetterRepository.java:83)"
11
:
"	at de.metas.ui.web.letter.LetterRestController.changeLetter(LetterRestController.java:282)"
12
:
"	at de.metas.ui.web.letter.LetterRestController.complete(LetterRestController.java:205)"
13
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
14
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
15
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
16
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
17
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
18
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
19
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
20
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
21
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
22
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
23
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
24
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
25
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
26
:
"	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)"
27
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)"
28
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
29
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
30
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
31
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
32
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
33
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
34
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
35
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
36
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
37
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
38
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
39
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
40
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
41
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
42
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
43
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
44
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
45
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)"
46
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
47
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
48
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
49
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
50
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
51
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
52
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
53
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
54
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
55
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
56
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
57
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
58
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
59
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
60
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
61
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
62
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
63
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
64
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
65
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
66
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
67
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
68
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
69
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
70
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
71
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
72
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
73
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
74
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
75
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
76
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
77
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
78
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
79
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
80
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
81
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
82
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
83
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
84
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
85
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
86
:
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
87
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
88
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
89
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
90
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
91
:
"	at java.lang.Thread.run(Thread.java:748)"
92
:
"Caused by: java.lang.NullPointerException"
93
:
"	at de.metas.letters.api.impl.TextTemplateBL.getJasperProcess_ID(TextTemplateBL.java:197)"
94
:
"	at de.metas.letters.api.impl.TextTemplateBL.createPDF(TextTemplateBL.java:175)"
95
:
"	at de.metas.ui.web.letter.LetterRestController.createPDFData(LetterRestController.java:252)"
96
:
"	at de.metas.ui.web.letter.LetterRestController.complete0(LetterRestController.java:222)"
97
:
"	at de.metas.ui.web.letter.LetterRestController.lambda$null$0(LetterRestController.java:205)"
98
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)"
99
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
[100 … 101]
100
:
"	... 89 more"
101
:
""
```` 

</details>

**Comment by metas-dh** [comment]
see IT me03 task
