### ISSUE TITLE
Mandatory logic broken for C_FlatrateTerm.C_Currency_ID

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#4504]
### Is this a bug or feature request?
Bug
### What is the current behavior?
```
 Document - Failed evaluating mandatory logic @PriceActual@!@null@ for DocumentField{fieldName=C_Flatrate_Term.C_Currency_ID, value=IntegerLookupValue{id=102, displayName=trl{trls={en_US=EUR}, default=EUR}}, initalValue=IntegerLookupValue{id=102, displayName=trl{trls={en_US=EUR}, default=EUR}}}. Preserving FALSE{mandatory-initial}
org.adempiere.ad.expression.exceptions.ExpressionEvaluationException: Parameter 'null' not found in context
 Context: DocumentEvaluatee{Document{tableName=C_Flatrate_Term, id=1000415, windowNo=2, writable=false, valid=Invalid-Initial('not validated yet'), validOnCheckout=Invalid-Initial('not validated yet'), saveStatus=DocumentSaveStatus{saved=false, deleted=false, hasChangesToBeSaved=true, error=false, reason=not yet checked}, saveStatusOnCheckout=DocumentSaveStatus{saved=false, deleted=false, hasChangesToBeSaved=true, error=false, reason=not yet checked}}}
 Evaluator: ExpressionEvaluationContext{onVariableNotFound=Fail, params=DocumentEvaluatee{Document{tableName=C_Flatrate_Term, id=1000415, windowNo=2, writable=false, valid=Invalid-Initial('not validated yet'), validOnCheckout=Invalid-Initial('not validated yet'), saveStatus=DocumentSaveStatus{saved=false, deleted=false, hasChangesToBeSaved=true, error=false, reason=not yet checked}, saveStatusOnCheckout=DocumentSaveStatus{saved=false, deleted=false, hasChangesToBeSaved=true, error=false, reason=not yet checked}}}}
	at org.adempiere.ad.expression.api.impl.LogicExpressionEvaluator$ExpressionEvaluationContext.resolveCtxName(LogicExpressionEvaluator.java:596)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1126)
	at org.adempiere.ad.expression.api.impl.LogicExpressionEvaluator$ExpressionEvaluationContext.getValue(LogicExpressionEvaluator.java:555)
```
#### Which are the steps to reproduce?
Open window Contracts and check the trace.
### What is the expected or desired behavior?
No error in console.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* no error in console when opening contract window (neither Swing nor WebUI): OK
