### ISSUE TITLE
Picked and Non-Picked Quantities Shipment generation

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4507]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, shipments can be created via Shipment Schedule action. The user has to decide
a) with picked Quantities
b) or without
If a Sales Order has picked and non-picked Quantities, then the shipment can only be done via 2 shipment notes/ documents.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
A new action for shipment creation shall recognize that picked Quantities are available and use those. If non-picked Quantities exist then it shall take those. Alle Lines shall be added to one Shipment (depending on Aggregation settings).

**Comment by metas-dh** [comment]
Results of IT1
tested in release

1. 1 sales order with 2 orderlines, same product
2. picked partial qty for both orderlines:
* LU with 2 TUs for one
* standalone CU for the other
3. tried to create shipment from shipment schedule, with QtyPicked=Y and Complete=Y: no shipment was created, but no error msg: NOK

4. checked async:

<details>

```
18-09-17 09:57:17.735  WARN 18876 --- [WT-EventQueue-0] d.m.a.form.swing.SwingClientUIInstance   : java.lang.NullPointerException

java.lang.NullPointerException: null
	at org.compiere.grid.ed.VDocAction.dynInit(VDocAction.java:251)
	at org.compiere.grid.ed.VDocAction.<init>(VDocAction.java:96)
	at org.compiere.apps.APanel.actionButton0(APanel.java:2873)
	at org.compiere.apps.APanel.actionButton(APanel.java:2797)
	at org.compiere.apps.APanel.actionPerformed(APanel.java:1944)
	at org.compiere.grid.GridController$1.actionPerformed(GridController.java:335)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

</details>

**Comment by metas-dh** [comment]
Results of IT3
tested in mf15

1. Qty Picked shipment created correctly:
   * LU / TU / CU: **OK**
   * TU / CU: **OK**
   * CU: **OK**
   * LU / CU: to test
2. Qty as ordered shipment created correctly:
   * qty product: **OK**
   * qty TU: if earlier shipments exist without TU, then the qty TU is qty TU ordered - qty TU delivered, not 
qty TU ordered - qty TU matching the qty product delivered => old problem
   * only TU is added, no LU: OK?
3. Both:
   * Qty Picked: qty product and qty PI as picked: **OK**
   * rest qty is Qty Ordered - Qty Picked, with TU, no LU: OK?
4. Other tests:
   * shipment reactivated & completed again: Qty Pciked updated correctly in shipment schedule: **OK**
   * Qty Picked correct after Pick HU & Pick CU actions: **OK**


problems:
* qty Picked in 1st window picking terminal not always updated after pick; after picking processed only after refreshing the page
* HU Editor for selection takes a while to open (took about 12s usually)

**Comment by metas-ts** [comment]
:cherries: picked https://github.com/metasfresh/metasfresh/issues/4507 to `release`
