### ISSUE TITLE
New Action "Copy Window"

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4516]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to easily copy a window layout for WebUI.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create an action in window "Window". It shall copy all the Application Dictionary Setting for the Window (WIndow, Tab, Fields, WebUI UI Stuff ...) and create a duplicate Window that can then be used as starting point for a new customer customized window.

**Comment by metas-rc** [comment]
Note from Teo: use org.adempiere.model.InterfaceWrapperHelper.copy*

**Comment by metas-rc** [comment]
Left TODO: Add some unit tests

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

tested in Swing
1. New process "Copy Window" in "Window" (available for SysAdmin): OK (=> trl de_DE missing?)
2. Select window that shall be copied: window has to be set, mandatory: OK
3. Run process:
* tried copying window Pricesystem: 
     * result shown for process was "OK", but got no additional window that was created: NOK
     * console: `2018-09-05 10:47:23.255  INFO 28512 --- [WT-EventQueue-0] 
org.compiere.grid.ed.VLookup             : AD_Window_ID (Text) AD_Window_ID = 540320 - Preissystem`
     * could not open window Pricesystem in WebUI afterwards, error 404: Document type not found. (was OK on Swing though, so not sure the copying process was the cause!)
* tried copying window Request:
     * error: `** IllegalArgumentException: IsMandatory Invalid value - - Reference_ID=319 - N - Y`
     * console:  

<details>

```
2018-09-05 10:46:16.292 ERROR 28512 --- [ Window-1003094] de.metas.process.AD_Window_CopyWindow    : IsMandatory Invalid value -   - Reference_ID=319 - N - Y

java.lang.IllegalArgumentException: IsMandatory Invalid value -   - Reference_ID=319 - N - Y
	at org.compiere.model.PO.set_Value(PO.java:1137)
	at org.compiere.model.PO.set_ValueReturningBoolean(PO.java:1283)
	at org.compiere.model.PO.set_ValueOfColumn(PO.java:1271)
	at org.adempiere.ad.wrapper.POModelInternalAccessor.setValue(POModelInternalAccessor.java:109)
	at org.adempiere.ad.model.util.ModelCopyHelper.copy(ModelCopyHelper.java:105)
	at org.adempiere.ad.window.api.impl.ADWindowDAO.copyField(ADWindowDAO.java:812)
	at org.adempiere.ad.window.api.impl.ADWindowDAO.copyFields(ADWindowDAO.java:795)
	at org.adempiere.ad.window.api.impl.ADWindowDAO.copyTab(ADWindowDAO.java:727)
	at org.adempiere.ad.window.api.impl.ADWindowDAO.copyTabs(ADWindowDAO.java:715)
	at org.adempiere.ad.window.api.impl.ADWindowDAO.copyWindow(ADWindowDAO.java:352)
	at de.metas.process.AD_Window_CopyWindow.doIt(AD_Window_CopyWindow.java:40)
	at de.metas.process.JavaProcess.startProcess(JavaProcess.java:295)
	at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:564)
	at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:460)
	at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:50)
	at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:224)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:506)
	at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:286)
	at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:171)
	at de.metas.process.ProcessExecutor.lambda$executeAsync$0(ProcessExecutor.java:119)
	at java.lang.Thread.run(Thread.java:748)

2018-09-05 10:46:16.342  WARN 28512 --- [ Window-1003094] o.adempiere.ad.trx.api.impl.TrxManager   : AbstractTrxManager.call0 - caught class org.adempiere.exceptions.AdempiereException with message=IllegalArgumentException: IsMandatory Invalid value -   - Reference_ID=319 - N - Y
2018-09-05 10:46:16.344  WARN 28512 --- [ Window-1003094] de.metas.process.ProcessExecutor         : Got error

org.adempiere.exceptions.AdempiereException: IllegalArgumentException: IsMandatory Invalid value -   - Reference_ID=319 - N - Y
	at org.adempiere.exceptions.AdempiereException.wrapIfNeeded(AdempiereException.java:89)
	at de.metas.process.ProcessExecutionResult.propagateErrorIfAny(ProcessExecutionResult.java:656)
	at de.metas.process.JavaProcess.startProcess(JavaProcess.java:325)
	at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:564)
	at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:460)
	at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:50)
	at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:224)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:506)
	at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:286)
	at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:171)
	at de.metas.process.ProcessExecutor.lambda$executeAsync$0(ProcessExecutor.java:119)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: IsMandatory Invalid value -   - Reference_ID=319 - N - Y
	at org.compiere.model.PO.set_Value(PO.java:1137)
	at org.compiere.model.PO.set_ValueReturningBoolean(PO.java:1283)
	at org.compiere.model.PO.set_ValueOfColumn(PO.java:1271)
	at org.adempiere.ad.wrapper.POModelInternalAccessor.setValue(POModelInternalAccessor.java:109)
	at org.adempiere.ad.model.util.ModelCopyHelper.copy(ModelCopyHelper.java:105)
	at org.adempiere.ad.window.api.impl.ADWindowDAO.copyField(ADWindowDAO.java:812)
	at org.adempiere.ad.window.api.impl.ADWindowDAO.copyFields(ADWindowDAO.java:795)
	at org.adempiere.ad.window.api.impl.ADWindowDAO.copyTab(ADWindowDAO.java:727)
	at org.adempiere.ad.window.api.impl.ADWindowDAO.copyTabs(ADWindowDAO.java:715)
	at org.adempiere.ad.window.api.impl.ADWindowDAO.copyWindow(ADWindowDAO.java:352)
	at de.metas.process.AD_Window_CopyWindow.doIt(AD_Window_CopyWindow.java:40)
	at de.metas.process.JavaProcess.startProcess(JavaProcess.java:295)
	... 15 common frames omitted
```
</details>

=> if it's not possible to create a copy of a certain window, then maybe this window shall not be selectable for the process, or the error msg why copying did not work shall give more info on why copying did not work

**Comment by metas-dh** [comment]
Results of IT2
tested after applying script from metas-rc for fixing the problem with the error described above:

b. => tried copying window Request again:
* result shown for process was "OK", data set in new window taken from Request: **OK**
* Window, Tab, Fields, WebUI UI Stuff in new window is copied from original window: **OK**
* newly created AD_Window_ID for the new window: **OK**
* AD_Window_Access copied from  original window as well: **OK**
* display order in new window the same as in original window: **OK**

**Comment by metas-dh** [comment]
for the time being, it's ok to have the process working in Swing, since the window for "Window Administration" is not readily configured for WebUI yet.

=> task can be moved to Done after next Rollout, when metas-rc's script is integrated as well.

**Comment by metas-dh** [comment]
quickly checked the windows in WebUI (using window ID):
1 not found in menu, which is OK i think since there were no menu entries created: **OK**
2 window copied from price system: 
* all data included lik in original window: OK
* Zoom into / references etc. working fine: OK

3. window copied from request:


<details>

```
{timestamp: 1536321272846, status: 500, error: "Internal Server Error",…}
error
:
"Internal Server Error"
exception
:
"org.adempiere.ad.expression.exceptions.ExpressionEvaluationException"
message
:
"* Not found *: #AD_User_ID↵Expressions trace:↵ * Cached{((exists 	( select 1 from ad_user u where ad_user_ID = master.SalesRep_ID and   exists ( select 1 from AD_User_Roles ur where ur.ad_user_ID = u.ad_user_ID and   exists ( select 1 from AD_User_Roles ur2 where ur.ad_role_id = ur2.ad_role_id and ad_user_ID = @#AD_User_ID@ and isactive = 'Y'))))   AND (master.R_Status_ID IS NULL OR EXISTS (select 1 from R_Status where R_Status_ID = master.R_Status_ID and IsClosed='N'))   AND EXISTS (select 1 from R_RequestType where R_RequestType_ID = master.R_RequestType_ID and IsUseForPartnerRequestWindow = 'Y'))}"
path
:
"/rest/api/documentView/1000001"
status
:
500
timestamp
:
1536321272846
trace
:
["org.adempiere.ad.expression.exceptions.ExpressionEvaluationException: * Not found *: #AD_User_ID",…]
0
:
"org.adempiere.ad.expression.exceptions.ExpressionEvaluationException: * Not found *: #AD_User_ID"
1
:
"Expressions trace:"
2
:
" * Cached{((exists 	( select 1 from ad_user u where ad_user_ID = master.SalesRep_ID and   exists ( select 1 from AD_User_Roles ur where ur.ad_user_ID = u.ad_user_ID and   exists ( select 1 from AD_User_Roles ur2 where ur.ad_role_id = ur2.ad_role_id and ad_user_ID = @#AD_User_ID@ and isactive = 'Y'))))   AND (master.R_Status_ID IS NULL OR EXISTS (select 1 from R_Status where R_Status_ID = master.R_Status_ID and IsClosed='N'))   AND EXISTS (select 1 from R_RequestType where R_RequestType_ID = master.R_RequestType_ID and IsUseForPartnerRequestWindow = 'Y'))}"
3
:
"	at org.adempiere.ad.expression.api.impl.CachedStringExpression$EffectiveValuesEvaluatee.extractFrom(CachedStringExpression.java:220)"
4
:
"	at org.adempiere.ad.expression.api.impl.CachedStringExpression.evaluate(CachedStringExpression.java:152)"
5
:
"	at org.adempiere.ad.expression.api.impl.CachedStringExpression.evaluate(CachedStringExpression.java:55)"
6
:
"	at org.adempiere.ad.expression.api.impl.CompositeStringExpression.evaluate(CompositeStringExpression.java:177)"
7
:
"	at org.adempiere.ad.expression.api.impl.CompositeStringExpression.evaluate(CompositeStringExpression.java:67)"
8
:
"	at de.metas.ui.web.view.descriptor.SqlViewSelectionQueryBuilder.buildSqlCreateSelection_WithoutGrouping(SqlViewSelectionQueryBuilder.java:291)"
9
:
"	at de.metas.ui.web.view.descriptor.SqlViewSelectionQueryBuilder.buildSqlCreateSelectionFrom(SqlViewSelectionQueryBuilder.java:207)"
10
:
"	at de.metas.ui.web.view.SqlViewRowIdsOrderedSelectionFactory.createOrderedSelection(SqlViewRowIdsOrderedSelectionFactory.java:104)"
11
:
"	at de.metas.ui.web.view.SqlViewDataRepository.createOrderedSelection(SqlViewDataRepository.java:183)"
12
:
"	at de.metas.ui.web.view.DefaultView.lambda$new$0(DefaultView.java:158)"
13
:
"	at org.adempiere.util.lang.ExtendedMemorizingSupplier.get(ExtendedMemorizingSupplier.java:65)"
14
:
"	at de.metas.ui.web.view.DefaultView.size(DefaultView.java:252)"
15
:
"	at de.metas.ui.web.view.ViewResult.<init>(ViewResult.java:162)"
16
:
"	at de.metas.ui.web.view.ViewResult.ofView(ViewResult.java:90)"
17
:
"	at de.metas.ui.web.view.ViewRestController.createView(ViewRestController.java:148)"
18
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
19
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
20
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
21
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
22
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
23
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
24
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
25
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
26
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
27
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
28
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
29
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
30
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
31
:
"	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)"
32
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)"
33
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
34
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
35
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
36
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
37
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
38
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
39
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
40
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
41
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
42
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
43
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
44
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
45
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
46
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
47
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
48
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
49
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
50
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:79)"
51
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
52
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
53
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
54
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
55
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
56
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
57
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
58
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
59
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
60
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
61
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
62
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
63
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
64
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
65
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
66
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
67
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
68
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
69
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
70
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
71
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
72
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
73
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
74
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
75
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
76
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
77
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
78
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
79
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
80
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
81
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
82
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
83
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
84
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
85
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
86
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
87
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
88
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
89
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
90
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
91
:
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
92
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
93
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
94
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
95
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
96
:
"	at java.lang.Thread.run(Thread.java:748)"
97
:
""
```
>/details>

**Comment by metas-dh** [comment]
=> checked with metas-rc: window "Request" does not exist like that in WebUI, "Request" window in WebUI = "Request (all)" in Swing, so it's OK to not find the copied window since there is no original either
