### ISSUE TITLE
Allow custom, POReference-based document numbers

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4575]
### Is this a bug or feature request?
FR
### What is the current behavior?
document numbers are generally coming from  `AD_Sequence`

### What is the expected or desired behavior?

* we need a way to customize one particular doc types to have their respective POReference being a part of the documentNo.

### How it's implemented

* added new interface `CustomSequenceNoProvider`
* implementors can be set in `AD_Sequence` and will be invoked when the sequence number is retrieved.
  * so, they just provide an alternative sequence number..e.g. the `AD_Sequence`'s suffix and prefix are still applied to get the final DocumentNumber
  * a "sequence number" does not have to be an integer..it can be any non-empty-string
  * if the sequence number returned by the implementation causes problems, because it is e.g. a double, then there is nothing the implementation can do about it.
  * if an implementor is set for an AD_Sequence, but the implementor can't provide a SeqNo, then an exception with a user-friendly (trl'ed) text is thrown
* add an implementor that returns the respective Document's POReference as sequence number. It is only applicable if the respective data record has a non-empty POReference

#### Setup
![image](https://user-images.githubusercontent.com/1264789/45471441-5e68b100-b731-11e8-8426-1fa7784d3054.png)

#### Invoicing

![image](https://user-images.githubusercontent.com/1264789/45472044-4a25b380-b733-11e8-936c-30192b6fd20a.png)

#### Result

![image](https://user-images.githubusercontent.com/1264789/45472080-63c6fb00-b733-11e8-86bc-f8fef016559a.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

SetUp:
1. `CustomSequenceNoProvider` available in `AD_Sequence`: **OK**
2. set `CustomSequenceNoProvider` for sales invoice `AD_Sequence`
3. added Prefix and Suffix for testing

Test:
1. set POReference in sales order, 2 orderlines, create shipment for 1 orderline and check IC: POReference is set, **OK**
2. create invoice for this orderline: POReference eff. can be changed by the user in overlay: **OK**
3. leave POReference eff. empty, OK: => sales invoice has respective Document's POReference set as sequence number including Prefix & Suffix: **OK**
4. create shipment for the other oderline and check IC: POReference is set, **OK**
5. create invoice for this orderline, set POReference eff. differently in overlay, OK: => sales invoice has the POReference eff. set in overlay set as sequence number including Prefix & Suffix: **OK**

6. no POReference in sales order, no POReference in IC, set no  POReference eff. in overlay when creating the invoice: => expected a notification that the invoice could not be created bc of missing POReference, but invoice was created, with document number 1000000 (?): **NOK**

=> in my testcase not all of the document number was displayed in Jasper doc: suffix was missing: checked with metas-ts: not critical atm, if customer will have very long document numbers bc of this then we will change the Jasper accordingly.

**Comment by metas-dh** [comment]
tried to reverse one of the invoices with Document's POReference set as sequence number, got an error:

<details>

```
2018-09-19 15:43:19.445  WARN 18894 --- [rbeiten-1003591] o.adempiere.ad.trx.api.impl.TrxManager   : AbstractTrxManager.call0 - caught class org.adempiere.exceptions.DBUniqueConstraintException with message=ERROR: duplicate key value violates unique constraint "c_invoice_documentno_target"
  Detail: Key (c_bpartner_id, documentno, c_doctypetarget_id)=(2156425, PREFIXtestref123SUFFIX, 1000002) already exists.
	SQL: INSERT INTO C_Invoice (AD_Client_ID,AD_Org_ID,BPartnerAddress,C_BPartner_ID,C_BPartner_Location_ID,C_Currency_ID,C_DocType_ID,C_DocTypeTarget_ID,ChargeAmt,C_Invoice_ID,C_Order_ID,C_PaymentTerm_ID,CreateCalcCorrection,Created,CreatedBy,DateAcct,DateInvoiced,Description,DescriptionBottom,DocAction,DocStatus,DocumentNo,GrandTotal,IsActive,IsApproved,IsCommissionLock,IsCreditedInvoiceReinvoicable,IsDiscountPrinted,IsInDispute,IsPaid,IsPayScheduleValid,IsPrinted,IsSelfService,IsSOTrx,IsTaxIncluded,IsTransferred,IsUseBPartnerAddress,M_InOut_ID,M_PriceList_ID,PaymentRule,POReference,Posted,Processed,Processing,SendEMail,TotalLines,Updated,UpdatedBy) VALUES (1000000,1000000,'Test Kunde 1
teststraße 996
45678 teststadt 3',2156425,2205175,102,0,1000002,0,nextval('c_invoice_seq'),1000005,1000009,'1',TO_TIMESTAMP('2018-09-19 15:43:19','YYYY-MM-DD HH24:MI:SS'),100,TO_TIMESTAMP('2018-09-19','YYYY-MM-DD'),TO_TIMESTAMP('2018-09-19','YYYY-MM-DD'),'','','CO','DR','PREFIXtestref123SUFFIX',0,'Y','N','N','N','N','N','N','N','N','N','Y','N','N','N',1000004,2008396,'P','testref123','N','N','N','N',0,TO_TIMESTAMP('2018-09-19 15:43:19','YYYY-MM-DD HH24:MI:SS'),100) RETURNING C_Invoice_ID
2018-09-19 15:43:19.452  WARN 18894 --- [rbeiten-1003591] org.compiere.wf.MWFActivity              : MWFNode[192-(DocAuto),Action=DocumentAction=--]

org.adempiere.exceptions.DBUniqueConstraintException: ERROR: duplicate key value violates unique constraint "c_invoice_documentno_target"
  Detail: Key (c_bpartner_id, documentno, c_doctypetarget_id)=(2156425, PREFIXtestref123SUFFIX, 1000002) already exists.
	SQL: INSERT INTO C_Invoice (AD_Client_ID,AD_Org_ID,BPartnerAddress,C_BPartner_ID,C_BPartner_Location_ID,C_Currency_ID,C_DocType_ID,C_DocTypeTarget_ID,ChargeAmt,C_Invoice_ID,C_Order_ID,C_PaymentTerm_ID,CreateCalcCorrection,Created,CreatedBy,DateAcct,DateInvoiced,Description,DescriptionBottom,DocAction,DocStatus,DocumentNo,GrandTotal,IsActive,IsApproved,IsCommissionLock,IsCreditedInvoiceReinvoicable,IsDiscountPrinted,IsInDispute,IsPaid,IsPayScheduleValid,IsPrinted,IsSelfService,IsSOTrx,IsTaxIncluded,IsTransferred,IsUseBPartnerAddress,M_InOut_ID,M_PriceList_ID,PaymentRule,POReference,Posted,Processed,Processing,SendEMail,TotalLines,Updated,UpdatedBy) VALUES (1000000,1000000,'Test Kunde 1
teststraße 996
45678 teststadt 3',2156425,2205175,102,0,1000002,0,nextval('c_invoice_seq'),1000005,1000009,'1',TO_TIMESTAMP('2018-09-19 15:43:19','YYYY-MM-DD HH24:MI:SS'),100,TO_TIMESTAMP('2018-09-19','YYYY-MM-DD'),TO_TIMESTAMP('2018-09-19','YYYY-MM-DD'),'','','CO','DR','PREFIXtestref123SUFFIX',0,'Y','N','N','N','N','N','N','N','N','N','Y','N','N','N',1000004,2008396,'P','testref123','N','N','N','N',0,TO_TIMESTAMP('2018-09-19 15:43:19','YYYY-MM-DD HH24:MI:SS'),100) RETURNING C_Invoice_ID
	at org.compiere.util.DB.executeUpdate(DB.java:961)
	at org.compiere.model.PO.saveNew(PO.java:3646)
	at org.compiere.model.PO.save0(PO.java:2826)
	at org.compiere.model.PO.access$100(PO.java:139)
	at org.compiere.model.PO$1.run(PO.java:2729)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:506)
	at org.compiere.model.PO.saveEx(PO.java:2723)
	at org.adempiere.model.POWrapper.save(POWrapper.java:799)
	at org.adempiere.model.InterfaceWrapperHelper.save(InterfaceWrapperHelper.java:600)
	at org.adempiere.invoice.service.impl.AbstractInvoiceBL.copyFrom(AbstractInvoiceBL.java:299)
	at org.adempiere.invoice.service.impl.AbstractInvoiceBL.copyFrom(AbstractInvoiceBL.java:198)
	at org.compiere.model.MInvoice.copyFrom(MInvoice.java:134)
	at org.compiere.model.MInvoice.reverseCorrectIt(MInvoice.java:2186)
	at de.metas.document.engine.impl.DocumentEngine.reverseCorrectIt(DocumentEngine.java:576)
	at de.metas.document.engine.impl.DocumentEngine.processIt0(DocumentEngine.java:298)
	at de.metas.document.engine.impl.DocumentEngine.processIt(DocumentEngine.java:236)
	at de.metas.document.engine.impl.DocumentEngine.processIt(DocumentEngine.java:207)
	at de.metas.document.engine.impl.AbstractDocumentBL.processIt(AbstractDocumentBL.java:98)
	at org.compiere.model.MInvoice.processIt(MInvoice.java:1280)
	at org.compiere.wf.MWFActivity.performWork(MWFActivity.java:991)
	at org.compiere.wf.MWFActivity.run(MWFActivity.java:873)
	at org.compiere.wf.MWFProcess.startNext(MWFProcess.java:378)
	at org.compiere.wf.MWFProcess.checkActivities(MWFProcess.java:288)
	at org.compiere.wf.MWFActivity.setWFState(MWFActivity.java:302)
	at org.compiere.wf.MWFActivity.run(MWFActivity.java:893)
	at org.compiere.wf.MWFProcess.startWork(MWFProcess.java:510)
	at org.compiere.wf.MWorkflow$1.call(MWorkflow.java:684)
	at org.compiere.wf.MWorkflow$1.call(MWorkflow.java:677)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)
	at org.compiere.wf.MWorkflow.start(MWorkflow.java:676)
	at org.compiere.wf.MWorkflow.startWait(MWorkflow.java:710)
	at de.metas.process.ProcessExecutor.startWorkflow(ProcessExecutor.java:435)
	at de.metas.process.ProcessExecutor.access$600(ProcessExecutor.java:50)
	at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:219)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:506)
	at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:286)
	at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:171)
	at de.metas.process.ProcessExecutor.lambda$executeAsync$0(ProcessExecutor.java:119)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "c_invoice_documentno_target"
  Detail: Key (c_bpartner_id, documentno, c_doctypetarget_id)=(2156425, PREFIXtestref123SUFFIX, 1000002) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1418)
	at org.adempiere.sql.impl.CPreparedStatementProxy.executeQuery(CPreparedStatementProxy.java:123)
	at org.adempiere.sql.impl.CPreparedStatementProxy.executeQueryAndLogMigationScripts(CPreparedStatementProxy.java:130)
	at org.compiere.util.DB.executeUpdate(DB.java:920)
	... 54 common frames omitted

2018-09-19 15:43:19.453  WARN 18894 --- [rbeiten-1003591] org.compiere.wf.MWFActivity              : Cause

org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "c_invoice_documentno_target"
  Detail: Key (c_bpartner_id, documentno, c_doctypetarget_id)=(2156425, PREFIXtestref123SUFFIX, 1000002) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1418)
	at org.adempiere.sql.impl.CPreparedStatementProxy.executeQuery(CPreparedStatementProxy.java:123)
	at org.adempiere.sql.impl.CPreparedStatementProxy.executeQueryAndLogMigationScripts(CPreparedStatementProxy.java:130)
	at org.compiere.util.DB.executeUpdate(DB.java:920)
	at org.compiere.model.PO.saveNew(PO.java:3646)
	at org.compiere.model.PO.save0(PO.java:2826)
	at org.compiere.model.PO.access$100(PO.java:139)
	at org.compiere.model.PO$1.run(PO.java:2729)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:506)
	at org.compiere.model.PO.saveEx(PO.java:2723)
	at org.adempiere.model.POWrapper.save(POWrapper.java:799)
	at org.adempiere.model.InterfaceWrapperHelper.save(InterfaceWrapperHelper.java:600)
	at org.adempiere.invoice.service.impl.AbstractInvoiceBL.copyFrom(AbstractInvoiceBL.java:299)
	at org.adempiere.invoice.service.impl.AbstractInvoiceBL.copyFrom(AbstractInvoiceBL.java:198)
	at org.compiere.model.MInvoice.copyFrom(MInvoice.java:134)
	at org.compiere.model.MInvoice.reverseCorrectIt(MInvoice.java:2186)
	at de.metas.document.engine.impl.DocumentEngine.reverseCorrectIt(DocumentEngine.java:576)
	at de.metas.document.engine.impl.DocumentEngine.processIt0(DocumentEngine.java:298)
	at de.metas.document.engine.impl.DocumentEngine.processIt(DocumentEngine.java:236)
	at de.metas.document.engine.impl.DocumentEngine.processIt(DocumentEngine.java:207)
	at de.metas.document.engine.impl.AbstractDocumentBL.processIt(AbstractDocumentBL.java:98)
	at org.compiere.model.MInvoice.processIt(MInvoice.java:1280)
	at org.compiere.wf.MWFActivity.performWork(MWFActivity.java:991)
	at org.compiere.wf.MWFActivity.run(MWFActivity.java:873)
	at org.compiere.wf.MWFProcess.startNext(MWFProcess.java:378)
	at org.compiere.wf.MWFProcess.checkActivities(MWFProcess.java:288)
	at org.compiere.wf.MWFActivity.setWFState(MWFActivity.java:302)
	at org.compiere.wf.MWFActivity.run(MWFActivity.java:893)
	at org.compiere.wf.MWFProcess.startWork(MWFProcess.java:510)
	at org.compiere.wf.MWorkflow$1.call(MWorkflow.java:684)
	at org.compiere.wf.MWorkflow$1.call(MWorkflow.java:677)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)
	at org.compiere.wf.MWorkflow.start(MWorkflow.java:676)
	at org.compiere.wf.MWorkflow.startWait(MWorkflow.java:710)
	at de.metas.process.ProcessExecutor.startWorkflow(ProcessExecutor.java:435)
	at de.metas.process.ProcessExecutor.access$600(ProcessExecutor.java:50)
	at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:219)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:506)
	at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:286)
	at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:171)
	at de.metas.process.ProcessExecutor.lambda$executeAsync$0(ProcessExecutor.java:119)
	at java.lang.Thread.run(Thread.java:748)

2018-09-19 15:43:19.456  INFO 18894 --- [rbeiten-1003591] org.compiere.wf.MWFProcess               : (118) - OR[<<ThreadInherited>>]
2018-09-19 15:43:19.508  INFO 18894 --- [WT-EventQueue-0] org.compiere.apps.ADialog                : null - ERROR: duplicate key value violates unique constraint "c_invoice_documentno_target"
  Detail: Key (c_bpartner_id, documentno, c_doctypetarget_id)=(2156425, PREFIXtestref123SUFFIX, 1000002) already exists.
	SQL: INSERT INTO C_Invoice (AD_Client_ID,AD_Org_ID,BPartnerAddress,C_BPartner_ID,C_BPartner_Location_ID,C_Currency_ID,C_DocType_ID,C_DocTypeTarget_ID,ChargeAmt,C_Invoice_ID,C_Order_ID,C_PaymentTerm_ID,CreateCalcCorrection,Created,CreatedBy,DateAcct,DateInvoiced,Description,DescriptionBottom,DocAction,DocStatus,DocumentNo,GrandTotal,IsActive,IsApproved,IsCommissionLock,IsCreditedInvoiceReinvoicable,IsDiscountPrinted,IsInDispute,IsPaid,IsPayScheduleValid,IsPrinted,IsSelfService,IsSOTrx,IsTaxIncluded,IsTransferred,IsUseBPartnerAddress,M_InOut_ID,M_PriceList_ID,PaymentRule,POReference,Posted,Processed,Processing,SendEMail,TotalLines,Updated,UpdatedBy) VALUES (1000000,1000000,'Test Kunde 1
teststraße 996
45678 teststadt 3',2156425,2205175,102,0,1000002,0,nextval('c_invoice_seq'),1000005,1000009,'1',TO_TIMESTAMP('2018-09-19 15:43:19','YYYY-MM-DD HH24:MI:SS'),100,TO_TIMESTAMP('2018-09-19','YYYY-MM-DD'),TO_TIMESTAMP('2018-09-19','YYYY-MM-DD'),'','','CO','DR','PREFIXtestref123SUFFIX',0,'Y','N','N','N','N','N','N','N','N','N','Y','N','N','N',1000004,2008396,'P','testref123','N','N','N','N',0,TO_TIMESTAMP('2018-09-19 15:43:19','YYYY-MM-DD HH24:MI:SS'),100) RETURNING C_Invoice_ID

```
</details>
