### ISSUE TITLE
Cannot complete flatrate term conditions / transition in swing

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#4602]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When trying to complete flatrate term conditions / transition in Swing, you get an NPE, see below. Completing the same data in WebUI works fine.

<details>

```
18-09-17 09:57:17.735  WARN 18876 --- [WT-EventQueue-0] d.m.a.form.swing.SwingClientUIInstance   : java.lang.NullPointerException

java.lang.NullPointerException: null
	at org.compiere.grid.ed.VDocAction.dynInit(VDocAction.java:251)
	at org.compiere.grid.ed.VDocAction.<init>(VDocAction.java:96)
	at org.compiere.apps.APanel.actionButton0(APanel.java:2873)
	at org.compiere.apps.APanel.actionButton(APanel.java:2797)
	at org.compiere.apps.APanel.actionPerformed(APanel.java:1944)
	at org.compiere.grid.GridController$1.actionPerformed(GridController.java:335)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
</details>

#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Shall work.

**Comment by metas-ts** [comment]
:cherries: picked https://github.com/metasfresh/metasfresh/issues/4602 to `release`

**Comment by teosarca** [comment]
note to IT: happened with any document which does not have C_DocType_ID or C_DocTypeTarget_ID.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* completing flatrate term conditions / transition: works fine in Swing, no NPE: OK
* completing flatrate term conditions / transition: also working fine in WebUI: OK
