### ISSUE TITLE
Swing Picking Terminal: cannot pick 

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4632]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
Try to pick:
![image pasted at 2018-9-26 10-01](https://user-images.githubusercontent.com/1264789/46070319-c2519780-c17d-11e8-9b5a-a2d29d0e62d8.png)

and you will get

<details>

```
org.adempiere.exceptions.AdempiereException: Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
Bitte leiten Sie diese Meldung an metas weiter:

Error: Missing product and quantity for vhu=X_M_HU[M_HU_ID=1001389, Value=1001389, trxName=<<ThreadInherited>>]
	at sun.reflect.GeneratedConstructorAccessor1642.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45005)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at de.metas.util.Check.mkEx(Check.java:112)
	at de.metas.util.Check.throwOrLogEx(Check.java:123)
	at de.metas.util.Check.errorUnless(Check.java:531)
	at de.metas.util.Check.errorUnless(Check.java:515)
	at de.metas.handlingunits.trace.HUTraceEventsService.builderSetVhuProductAndQty(HUTraceEventsService.java:518)
	at de.metas.handlingunits.trace.HUTraceEventsService.createAndAddFor(HUTraceEventsService.java:221)
	at de.metas.handlingunits.trace.interceptor.M_ShipmentSchedule_QtyPicked.addTraceEvent(M_ShipmentSchedule_QtyPicked.java:46)
	at sun.reflect.GeneratedMethodAccessor706.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45005)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.executeNow0(AnnotatedModelInterceptor.java:611)
	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.executeNow(AnnotatedModelInterceptor.java:563)
	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.execute(AnnotatedModelInterceptor.java:521)
	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.execute(AnnotatedModelInterceptor.java:464)
	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.onModelChange(AnnotatedModelInterceptor.java:442)
	at org.adempiere.ad.modelvalidator.ModelInterceptor2ModelValidatorWrapper.modelChange(ModelInterceptor2ModelValidatorWrapper.java:123)
	at org.compiere.model.ModelValidationEngine.invokeModelChangeMethod(ModelValidationEngine.java:970)
	at org.compiere.model.ModelValidationEngine.invokeModelChangeMethods(ModelValidationEngine.java:947)
	at org.compiere.model.ModelValidationEngine.fireModelChange0(ModelValidationEngine.java:829)
	at org.compiere.model.ModelValidationEngine.lambda$0(ModelValidationEngine.java:784)
	at org.compiere.model.ModelValidationEngine$1.run(ModelValidationEngine.java:806)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:1)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:596)
	at org.compiere.model.ModelValidationEngine.executeInTrx(ModelValidationEngine.java:801)
	at org.compiere.model.ModelValidationEngine.fireModelChange(ModelValidationEngine.java:784)
	at org.compiere.model.PO.fireModelChange(PO.java:4846)
	at org.compiere.model.PO.saveFinish(PO.java:2901)
	at org.compiere.model.PO.saveUpdate(PO.java:3278)
	at org.compiere.model.PO.save0(PO.java:2834)
	at org.compiere.model.PO.access$1(PO.java:2807)
	at org.compiere.model.PO$1.run(PO.java:2729)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:1)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:506)
	at org.compiere.model.PO.saveEx(PO.java:2723)
	at org.adempiere.model.POWrapper.save(POWrapper.java:799)
	at org.adempiere.model.InterfaceWrapperHelper.save(InterfaceWrapperHelper.java:600)
	at de.metas.handlingunits.shipmentschedule.api.impl.HUShipmentScheduleBL.addQtyPicked(HUShipmentScheduleBL.java:143)
	at de.metas.handlingunits.shipmentschedule.api.impl.ShipmentScheduleHUTrxListener.trxLineProcessed(ShipmentScheduleHUTrxListener.java:81)
	at de.metas.handlingunits.impl.CompositeHUTrxListener.trxLineProcessed(CompositeHUTrxListener.java:134)
	at de.metas.handlingunits.hutransaction.impl.HUTransactionProcessor.processTrxLine(HUTransactionProcessor.java:223)
	at de.metas.handlingunits.hutransaction.impl.HUTransactionProcessor.processTrx(HUTransactionProcessor.java:192)
	at de.metas.handlingunits.hutransaction.impl.HUTransactionProcessor.createAndProcessTrx(HUTransactionProcessor.java:269)
	at de.metas.handlingunits.hutransaction.impl.HUTransactionProcessor.createTrx(HUTransactionProcessor.java:251)
	at de.metas.handlingunits.hutransaction.impl.HUTrxBL.createTrx(HUTrxBL.java:150)
	at de.metas.handlingunits.allocation.impl.HULoader.loadToDestination(HULoader.java:423)
	at de.metas.handlingunits.allocation.impl.HULoader.unloadSourceThenLoadDestination(HULoader.java:284)
	at de.metas.handlingunits.allocation.impl.HULoader.lambda$0(HULoader.java:185)
	at de.metas.handlingunits.allocation.impl.HUContextProcessorExecutor$1.run(HUContextProcessorExecutor.java:102)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:1)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:506)
	at de.metas.handlingunits.allocation.impl.HUContextProcessorExecutor.run(HUContextProcessorExecutor.java:79)
	at de.metas.handlingunits.allocation.impl.HULoader.processInHUContext(HULoader.java:204)
	at de.metas.handlingunits.allocation.impl.HULoader.load(HULoader.java:178)
	at de.metas.picking.service.impl.HU2PackingItemsAllocator.transferQtyFromVHUToTargetHU(HU2PackingItemsAllocator.java:431)
	at de.metas.picking.service.impl.HU2PackingItemsAllocator.lambda$1(HU2PackingItemsAllocator.java:506)
	at de.metas.picking.service.impl.HU2PackingItemsAllocator.packItem(HU2PackingItemsAllocator.java:548)
	at de.metas.picking.service.impl.HU2PackingItemsAllocator.allocateVHU(HU2PackingItemsAllocator.java:488)
	at de.metas.picking.service.impl.HU2PackingItemsAllocator.allocateTU(HU2PackingItemsAllocator.java:378)
	at de.metas.picking.service.impl.HU2PackingItemsAllocator.allocateHU(HU2PackingItemsAllocator.java:345)
	at de.metas.picking.service.impl.HU2PackingItemsAllocator.allocate0(HU2PackingItemsAllocator.java:322)
	at de.metas.handlingunits.allocation.IHUContextProcessorExecutor.lambda$0(IHUContextProcessorExecutor.java:72)
	at de.metas.handlingunits.allocation.impl.HUContextProcessorExecutor$1.run(HUContextProcessorExecutor.java:102)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:1)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:506)
	at de.metas.handlingunits.allocation.impl.HUContextProcessorExecutor.run(HUContextProcessorExecutor.java:79)
	at de.metas.handlingunits.allocation.IHUContextProcessorExecutor.run(IHUContextProcessorExecutor.java:71)
	at de.metas.picking.service.impl.HU2PackingItemsAllocator.allocate(HU2PackingItemsAllocator.java:304)
	at de.metas.picking.service.impl.HU2PackingItemsAllocator$HU2PackingItemsAllocatorBuilder.allocate(HU2PackingItemsAllocator.java:640)
	at de.metas.fresh.picking.form.swing.FreshSwingPackageItems.packItemToHU(FreshSwingPackageItems.java:518)
	at de.metas.fresh.picking.form.swing.FreshSwingPackageItems.propertyChange0(FreshSwingPackageItems.java:295)
	at de.metas.fresh.picking.form.swing.FreshSwingPackageItems.propertyChange(FreshSwingPackageItems.java:225)
	at org.adempiere.util.beans.WeakPropertyChangeListener.propertyChange(WeakPropertyChangeListener.java:168)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at de.metas.adempiere.form.terminal.swing.SwingTerminalButtonWrapper$1.actionPerformed(SwingTerminalButtonWrapper.java:80)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

</details>

### What is the expected or desired behavior?
Shall work

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15 (Swing)

Picking Terminal:
* picking possible using "Hinzufügen" action: OK
* picking possible using "Verteilen" action: OK
* QtyPicked / QtyOrdered updated correctly: OK

* picking also working fine in WebUI still: OK
