### ISSUE TITLE
Error: Param 'serviceInstanceClass' = class de.metas.bpartner.service.impl.BPartnerBL has no default constructor

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4694]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
Start the webui server and check the console
```
2018-10-23 16:56:55.966  WARN 652 [                ][          ] --- [ask-scheduler-1] m.p.r.PurchaseCandidateReminderScheduler : Failed dispatching notifications for PurchaseCandidateReminder(vendorBPartnerId=BPartnerId(repoId=2156423), notificationTime=2018-05-15T01:00). Skipped

org.adempiere.util.exceptions.ServicesException: org.adempiere.exceptions.AdempiereException: Error: Param 'serviceInstanceClass' = class de.metas.bpartner.service.impl.BPartnerBL has no default constructor
	at org.adempiere.util.exceptions.ServicesException.wrapIfNeeded(ServicesException.java:55)
	at org.adempiere.util.exceptions.ServicesException.wrapIfNeeded(ServicesException.java:51)
	at de.metas.util.Services.findAndLoadService(Services.java:269)
	at de.metas.util.Services.access$1(Services.java:233)
	at de.metas.util.Services$2.load(Services.java:128)
	at de.metas.util.Services$2.load(Services.java:1)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at de.metas.util.Services.getSingleton(Services.java:224)
	at de.metas.util.Services.get(Services.java:195)
	at de.metas.purchasecandidate.reminder.PurchaseCandidateReminderScheduler.createViewStickyFilter(PurchaseCandidateReminderScheduler.java:248)
	at de.metas.purchasecandidate.reminder.PurchaseCandidateReminderScheduler.createPurchaseCandidatesView(PurchaseCandidateReminderScheduler.java:231)
	at de.metas.purchasecandidate.reminder.PurchaseCandidateReminderScheduler.dispatchNotification(PurchaseCandidateReminderScheduler.java:204)
	at de.metas.purchasecandidate.reminder.PurchaseCandidateReminderScheduler.dispatchNotificationNoFail(PurchaseCandidateReminderScheduler.java:194)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at de.metas.purchasecandidate.reminder.PurchaseCandidateReminderScheduler.dispatchNotificationsAndReschedule(PurchaseCandidateReminderScheduler.java:177)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.adempiere.exceptions.AdempiereException: Error: Param 'serviceInstanceClass' = class de.metas.bpartner.service.impl.BPartnerBL has no default constructor
	at sun.reflect.GeneratedConstructorAccessor538.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45005)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at de.metas.util.Check.mkEx(Check.java:112)
	at de.metas.util.Check.throwOrLogEx(Check.java:123)
	at de.metas.util.Check.errorIf(Check.java:559)
	at de.metas.util.Check.errorIf(Check.java:540)
	at de.metas.util.Services.getDefaultConstructor(Services.java:534)
	at de.metas.util.Services.findServiceImplementationConstructor(Services.java:298)
	at de.metas.util.Services.access$0(Services.java:273)
	at de.metas.util.Services$1.load(Services.java:119)
	at de.metas.util.Services$1.load(Services.java:1)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at de.metas.util.Services.findAndLoadService(Services.java:250)
	... 26 common frames omitted
```

**Comment by metas-ts** [comment]
@hi @teosarca 
it doesn't happen on my machine...maybe we can check together?
