### ISSUE TITLE
Can not create a new order line using 'Add new'

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#4732]
### Is this a bug or feature request?
Bug
### What is the current behavior?
You can not add on order line using 'Add new'
#### Which are the steps to reproduce?
Create and order and add new line by pressin 'Add new'
![image](https://user-images.githubusercontent.com/15378036/47928473-23802f80-decf-11e8-8400-e6e35f1206b5.png)
```
[ERROR] [dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.adempiere.ad.callout.exceptions.CalloutExecutionException: datePromised] with root cause
java.lang.NullPointerException: datePromised
	at de.metas.order.OrderLine.<init>(OrderLine.java:44)
	at de.metas.order.OrderLine$OrderLineBuilder.build(OrderLine.java:44)
	at de.metas.order.OrderLineRepository.ofRecord(OrderLineRepository.java:88)
	at de.metas.order.OrderLineRepository$$FastClassBySpringCGLIB$$67a9a23f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at de.metas.order.OrderLineRepository$$EnhancerBySpringCGLIB$$82e510a6.ofRecord(<generated>)
	at de.metas.vertical.pharma.model.interceptor.C_OrderLine.validatePrescriptionProduct(C_OrderLine.java:82)
	at sun.reflect.GeneratedMethodAccessor926.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45005)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.adempiere.ad.callout.annotations.api.impl.AnnotatedCalloutInstance.executePointcut(AnnotatedCalloutInstance.java:152)
```
### What is the expected or desired behavior?
Shall work

**Comment by metas-dh** [comment]
Results of IT1
tested in release

* creating new orderline using `Add new`works fine, no error: OK
