### ISSUE TITLE
Error creating receipt schedule if order line was created via "add new"

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4738]
### Is this a bug or feature request?
Bug

### What is the current behavior?

Error/Stacktrace in the respective async-workpackage:

<details>

```
org.adempiere.exceptions.AdempiereException: NullPointerException: date needs to be not-null
Additional parameters:
 HowtoDisableModelInterceptor: Model interceptor method de.metas.purchasecandidate.material.interceptor.M_ReceiptSchedule_PostEvents#createAndFireEvent threw an exception.
You can disable this method with SysConfig InterceptorEnabled_de.metas.purchasecandidate.material.interceptor.M_ReceiptSchedule_PostEvents#createAndFireEvent='N' (with AD_Client_ID and AD_Org_ID=0!)
 I_C_Queue_WorkPackage: X_C_Queue_WorkPackage[C_Queue_WorkPackage_ID=1002459, trxName=null]
 IQueueProcessor: ThreadPoolQueueProcessor{name=GenerateReceiptScheduleWorkpackageProcessor, executor=BlockingThreadPoolExecutor [getPoolSize()=1]}
 trxName: <<ThreadInherited>>
	at org.adempiere.exceptions.AdempiereException.wrapIfNeeded(AdempiereException.java:90)
	at org.adempiere.exceptions.AdempiereException.wrapIfNeeded(AdempiereException.java:86)
	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.appendAndLogHowtoDisableMessage(AnnotatedModelInterceptor.java:577)
	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.executeNow(AnnotatedModelInterceptor.java:567)
	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.execute(AnnotatedModelInterceptor.java:521)
	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.execute(AnnotatedModelInterceptor.java:464)
	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.onModelChange(AnnotatedModelInterceptor.java:442)
	at org.adempiere.ad.modelvalidator.ModelInterceptor2ModelValidatorWrapper.modelChange(ModelInterceptor2ModelValidatorWrapper.java:123)
	at org.compiere.model.ModelValidationEngine.invokeModelChangeMethod(ModelValidationEngine.java:970)
	at org.compiere.model.ModelValidationEngine.invokeModelChangeMethods(ModelValidationEngine.java:947)
	at org.compiere.model.ModelValidationEngine.fireModelChange0(ModelValidationEngine.java:829)
	at org.compiere.model.ModelValidationEngine.lambda$fireModelChange$0(ModelValidationEngine.java:784)
	at org.compiere.model.ModelValidationEngine$1.run(ModelValidationEngine.java:806)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:776)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:689)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:597)
	at org.compiere.model.ModelValidationEngine.executeInTrx(ModelValidationEngine.java:801)
	at org.compiere.model.ModelValidationEngine.fireModelChange(ModelValidationEngine.java:784)
	at org.compiere.model.PO.fireModelChange(PO.java:4847)
	at org.compiere.model.PO.saveFinish(PO.java:2902)
	at org.compiere.model.PO.saveNew(PO.java:3699)
	at org.compiere.model.PO.save0(PO.java:2827)
	at org.compiere.model.PO.access$100(PO.java:140)
	at org.compiere.model.PO$1.run(PO.java:2730)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:776)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:689)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:590)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:521)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:507)
	at org.compiere.model.PO.saveEx(PO.java:2724)
	at org.adempiere.model.POWrapper.save(POWrapper.java:799)
	at org.adempiere.model.InterfaceWrapperHelper.save(InterfaceWrapperHelper.java:601)
	at de.metas.inoutcandidate.spi.impl.OrderLineReceiptScheduleProducer.createOrReceiptScheduleFromOrderLine(OrderLineReceiptScheduleProducer.java:231)
	at de.metas.inoutcandidate.spi.impl.OrderLineReceiptScheduleProducer.createOrUpdateReceiptSchedules(OrderLineReceiptScheduleProducer.java:82)
	at de.metas.inoutcandidate.api.impl.CompositeReceiptScheduleProducerExecutor.createOrUpdateReceiptSchedules(CompositeReceiptScheduleProducerExecutor.java:103)
	at de.metas.inoutcandidate.async.GenerateReceiptScheduleWorkpackageProcessor.processWorkPackage(GenerateReceiptScheduleWorkpackageProcessor.java:72)
	at de.metas.async.processor.impl.WorkpackageProcessor2Wrapper.processWorkPackage(WorkpackageProcessor2Wrapper.java:34)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.invokeProcessorAndHandleException(WorkpackageProcessorTask.java:292)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.processWorkpackage(WorkpackageProcessorTask.java:284)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.access$000(WorkpackageProcessorTask.java:84)
	at de.metas.async.processor.impl.WorkpackageProcessorTask$1.run(WorkpackageProcessorTask.java:167)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:103)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:93)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:776)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:689)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:597)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.run(WorkpackageProcessorTask.java:157)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at Thread.run(Thread.java:748)
Caused by: NullPointerException: date needs to be not-null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
	at de.metas.material.event.commons.MaterialDescriptor.asssertMaterialDescriptorComplete(MaterialDescriptor.java:108)
	at de.metas.material.event.commons.MaterialDescriptor.<init>(MaterialDescriptor.java:100)
	at de.metas.material.event.commons.MaterialDescriptor.<init>(MaterialDescriptor.java:72)
	at de.metas.material.event.commons.MaterialDescriptor.<init>(MaterialDescriptor.java:43)
	at de.metas.material.event.commons.MaterialDescriptor$MaterialDescriptorBuilder.build(MaterialDescriptor.java:64)
	at de.metas.purchasecandidate.material.interceptor.M_ReceiptSchedule_PostEvents.createOrdereMaterialDescriptor(M_ReceiptSchedule_PostEvents.java:220)
	at de.metas.purchasecandidate.material.interceptor.M_ReceiptSchedule_PostEvents.createCreatedEvent(M_ReceiptSchedule_PostEvents.java:126)
	at de.metas.purchasecandidate.material.interceptor.M_ReceiptSchedule_PostEvents.createReceiptScheduleEvent(M_ReceiptSchedule_PostEvents.java:110)
	at de.metas.purchasecandidate.material.interceptor.M_ReceiptSchedule_PostEvents.createAndFireEvent(M_ReceiptSchedule_PostEvents.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at reflect.Method.invoke(Method.java:498)
	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.executeNow0(AnnotatedModelInterceptor.java:607)
	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.executeNow(AnnotatedModelInterceptor.java:563)
	... 52 more
```

</details>

**Comment by metas-ts** [comment]
note to IT: no IT required

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* no error when creating receipt schedule if order line was created via "add new" (in async): OK
* receipt schedule is created correctly: OK
