### ISSUE TITLE
Swing: "IOException: PDF header signature not found." for invoice print / print preview

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#4740]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When doing print / print preview for invoice in Swing, you get  "IOException: PDF header signature not found.", although the print opens correctly.

console:

<details>

```
2018-11-06 15:55:40.736  WARN 30811 --- [gsdruck-1002100] de.metas.process.ProcessExecutor         : Got error

org.adempiere.exceptions.AdempiereException: IOException: PDF header signature not found.
	at org.adempiere.exceptions.AdempiereException.wrapIfNeeded(AdempiereException.java:90)
	at de.metas.report.ExecuteReportStrategyUtil.print(ExecuteReportStrategyUtil.java:118)
	at de.metas.report.ExecuteReportStrategyUtil.concatenate(ExecuteReportStrategyUtil.java:74)
	at de.metas.invoice.process.C_Invoice_SalesInvoiceJasperWithAttachedDocumentsStrategy.executeReport(C_Invoice_SalesInvoiceJasperWithAttachedDocumentsStrategy.java:93)
	at de.metas.report.ReportStarter.startProcessPrintPreview(ReportStarter.java:167)
	at de.metas.report.ReportStarter.doIt(ReportStarter.java:88)
	at de.metas.process.JavaProcess.startProcess(JavaProcess.java:296)
	at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:564)
	at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:460)
	at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:50)
	at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:224)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:776)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:689)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:590)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:521)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:507)
	at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:286)
	at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:171)
	at de.metas.process.ProcessExecutor.access$1100(ProcessExecutor.java:50)
	at de.metas.process.ProcessExecutor$Builder.executeSync(ProcessExecutor.java:651)
	at org.compiere.print.ReportCtl.startDocumentPrint(ReportCtl.java:290)
	at org.compiere.print.ReportCtl.start(ReportCtl.java:92)
	at org.compiere.print.ReportCtl.access$300(ReportCtl.java:49)
	at org.compiere.print.ReportCtl$Builder.start(ReportCtl.java:367)
	at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:244)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:776)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:689)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:590)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:521)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:507)
	at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:286)
	at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:171)
	at de.metas.process.ProcessExecutor.lambda$executeAsync$0(ProcessExecutor.java:119)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: PDF header signature not found.
	at com.lowagie.text.pdf.PRTokeniser.checkPdfHeader(Unknown Source)
	at com.lowagie.text.pdf.PdfReader.readPdf(Unknown Source)
	at com.lowagie.text.pdf.PdfReader.<init>(Unknown Source)
	at com.lowagie.text.pdf.PdfReader.<init>(Unknown Source)
	at de.metas.report.ExecuteReportStrategyUtil.print(ExecuteReportStrategyUtil.java:91)
	... 36 common frames omitted

2018-11-06 15:55:40.767  INFO 30811 --- [WT-EventQueue-0] org.compiere.apps.ADialog                : null - IOException: PDF header signature not found.
```

</details>

#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
No errors.

**Comment by teosarca** [comment]
might be that it was introduced by https://github.com/metasfresh/metasfresh/issues/4700.

@metas-ts  can u check if is a critical issue or not?

**Comment by metas-rc** [comment]
Please, check my IT results in https://github.com/metasfresh/me03/issues/704

**Comment by metas-ts** [comment]
the problem was that the "inner" jasper invocation also opened a print preview window.
fixed now in commit metasfresh/metasfresh@b0acd56

**Comment by metas-dh** [comment]
Results of IT
tested in mf15

* no error when opening print preview: OK
* same error when opening print, and the print also does not open: NOK

**Comment by metas-ts** [comment]
@metas-dh 
* it now works with "print preview" and "print" on swing
* ALT-P in the webui still works

**Comment by metas-dh** [comment]
Results of IT2
tested in release

* no more error, also not when using `Print`: OK
* print preview and print both work fine (when set up correctly): OK
* Printing in WebUI still worked fine (w/ or w/o shortcut): OK
