### ISSUE TITLE
C_Invoice_CreateExportData async WP processor runs into error with most "normal" invoices

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4743]
### Is this a bug or feature request?
Bug

Follow-up to https://github.com/metasfresh/metasfresh/issues/4621

### What is the current behavior?

<details>

```
[...]
Additional parameters:
 I_C_Queue_WorkPackage: X_C_Queue_WorkPackage[C_Queue_WorkPackage_ID=1247726, trxName=null]
 IQueueProcessor: ThreadPoolQueueProcessor{name=C_Invoice_CreateExportData, executor=BlockingThreadPoolExecutor [getPoolSize()=1]}
 trxName: <<ThreadInherited>>
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at de.metas.util.Check.mkEx(Check.java:112)
        at de.metas.util.Check.throwOrLogEx(Check.java:123)
        at de.metas.util.Check.assume(Check.java:170)
        at de.metas.util.Check.assumeNotEmpty(Check.java:322)
        at de.metas.util.Check.assumeNotEmpty(Check.java:306)
        at de.metas.invoice.export.InvoiceToExportFactory.createBiller(InvoiceToExportFactory.java:255)
        at de.metas.invoice.export.InvoiceToExportFactory.getById(InvoiceToExportFactory.java:109)
        at de.metas.invoice.export.InvoiceExportService.exportInvoices(InvoiceExportService.java:81)
        at de.metas.invoice.export.async.C_Invoice_CreateExportData.processWorkPackage(C_Invoice_CreateExportData.java:52)
        at de.metas.async.processor.impl.WorkpackageProcessor2Wrapper.processWorkPackage(WorkpackageProcessor2Wrapper.java:34)
        at de.metas.async.processor.impl.WorkpackageProcessorTask.invokeProcessorAndHandleException(WorkpackageProcessorTask.java:292)
        at de.metas.async.processor.impl.WorkpackageProcessorTask.processWorkpackage(WorkpackageProcessorTask.java:284)
        at de.metas.async.processor.impl.WorkpackageProcessorTask.access$000(WorkpackageProcessorTask.java:84)
        at de.metas.async.processor.impl.WorkpackageProcessorTask$1.run(WorkpackageProcessorTask.java:167)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:103)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:93)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:776)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:689)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:597)
        at de.metas.async.processor.impl.WorkpackageProcessorTask.run(WorkpackageProcessorTask.java:157)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

</details>

#### Which are the steps to reproduce?

create an invoice where the org-bpartner does not have a remit-to address or ESR-account

### What is the expected or desired behavior?

the WP-processor should just log that the invoice was not exportable and finish peacefully

**Comment by metas-ts** [comment]
# Test-Doku

* be sure to have an org-BPartner (or have none, if that's even possible) that can't be an XML invoice biller
  * e.g. have no ESR account
  * or have no VATaxId
  * note: also, the C_Invoice.C_BPArtner_Location not having a GLN will trigger this behavior
* create an invoice
* check
  * the workpackage was successfully processed
  * there are log messages telling the user why there is no export
![image](https://user-images.githubusercontent.com/1264789/48136563-3e242100-e2a0-11e8-8f7f-8ac6473446c3.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

still got error in workpackage: => was not yet integrated!

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

invoiced some ICs when org-bpartner was set up as described above (newish db):
* no ESR account
* have no VATaxId

* plus:, the C_Invoice.C_BPArtner_Location does not have a GLN 

=> checked WP processor: package was processed correctly, no error: OK
=> package included the resp. info i nLog why there is no export: OK
?> invoice was created correctly: OK
