### ISSUE TITLE
Prolonging contract does not working anymore

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#4966]
### Is this a bug or feature request?
But
#### Which are the steps to reproduce?

Try to prolong a contract. You will get this stack trace:
<Details>
```
timestamp: 1550494608.589
trace: [,…]
[0 … 99]
0: "org.adempiere.exceptions.AdempiereException: Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
"
1: "Bitte leiten Sie diese Meldung an metas weiter:"
2: ""
3: "Assumption failure: repoId > 0 but it was 0"
4: "	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)"
5: "	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)"
6: "	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45
7: "	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)"
8: "	at de.metas.util.Check.mkEx(Check.java:115)"
9: "	at de.metas.util.Check.throwOrLogEx(Check.java:130)"
10: "	at de.metas.util.Check.assumeGreaterThanZero(Check.java:440)"
11: "	at de.metas.pricing.PricingSystemId.<init>(PricingSystemId.java:59)"
12: "	at de.metas.pricing.PricingSystemId.ofRepoId(PricingSystemId.java:39)"
13: "	at de.metas.pricing.conditions.service.impl.PricingConditionsRepository.toPriceSpecification(PricingConditionsRepository.java:238)"
14: "	at de.metas.pricing.conditions.service.impl.PricingConditionsRepository.toPricingConditionsBreak(PricingConditionsRepository.java:198)"
15: "	at de.metas.pricing.conditions.service.impl.PricingConditionsRepository.lambda$toPricingConditions$1(PricingConditionsRepository.java:159)"
16: "	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)"
17: "	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)"
18: "	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)"
19: "	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)"
20: "	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)"
21: "	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)"
22: "	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)"
23: "	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)"
24: "	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)"
25: "	at de.metas.pricing.conditions.service.impl.PricingConditionsRepository.toPricingConditions(PricingConditionsRepository.java:160)"
26: "	at de.metas.pricing.conditions.service.impl.PricingConditionsRepository.retrievePricingConditionsById(PricingConditionsRepository.java:119)"
27: "	at de.metas.cache.CCache.lambda$getOrLoad$0(CCache.java:543)"
28: "	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5065)"
29: "	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)"
30: "	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)"
31: "	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)"
32: "	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)"
33: "	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)"
34: "	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060)"
35: "	at de.metas.cache.CCache.get(CCache.java:504)"
36: "	at de.metas.cache.CCache.getOrLoad(CCache.java:544)"
37: "	at de.metas.pricing.conditions.service.impl.PricingConditionsRepository.getPricingConditionsById(PricingConditionsRepository.java:102)"
38: "	at de.metas.pricing.conditions.service.impl.CalculatePricingConditionsCommand.getPricingConditions(CalculatePricingConditionsCommand.java:118)"
39: "	at de.metas.pricing.conditions.service.impl.CalculatePricingConditionsCommand.getDiscountType(CalculatePricingConditionsCommand.java:104)"
40: "	at de.metas.pricing.conditions.service.impl.CalculatePricingConditionsCommand.calculate(CalculatePricingConditionsCommand.java:76)"
41: "	at de.metas.pricing.conditions.service.impl.PricingConditionsService.calculatePricingConditions(PricingConditionsService.java:17)"
42: "	at de.metas.pricing.rules.Discount.calculate(Discount.java:115)"
43: "	at de.metas.pricing.rules.AggregatedPricingRule.calculate(AggregatedPricingRule.java:129)"
44: "	at de.metas.pricing.service.impl.PricingBL.calculatePrice(PricingBL.java:143)"
45: "	at de.metas.contracts.pricing.SubscriptionPricingRule.invokePricingEngine(SubscriptionPricingRule.java:121)"
46: "	at de.metas.contracts.pricing.SubscriptionPricingRule.calculate(SubscriptionPricingRule.java:79)"
47: "	at de.metas.pricing.rules.AggregatedPricingRule.calculate(AggregatedPricingRule.java:129)"
48: "	at de.metas.pricing.service.impl.PricingBL.calculatePrice(PricingBL.java:143)"
49: "	at de.metas.order.impl.OrderLinePriceCalculator.updateOrderLine(OrderLinePriceCalculator.java:99)"
50: "	at de.metas.order.impl.OrderLineBL.updatePrices(OrderLineBL.java:351)"
51: "	at de.metas.order.model.interceptor.C_OrderLine.updatePricesOverrideExistingDiscounts(C_OrderLine.java:289)"
52: "	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
53: "	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
54: "	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
55: "	at java.lang.reflect.Method.invoke(Method.java:498)"
56: "	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.executeNow0(AnnotatedModelInterceptor.java:325)"
57: "	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.executeNow(AnnotatedModelInterceptor.java:277)"
58: "	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.execute(AnnotatedModelInterceptor.java:235)"
59: "	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.execute(AnnotatedModelInterceptor.java:178)"
60: "	at org.adempiere.ad.modelvalidator.AnnotatedModelInterceptor.onModelChange(AnnotatedModelInterceptor.java:156)"
61: "	at org.adempiere.ad.modelvalidator.ModelInterceptor2ModelValidatorWrapper.modelChange(ModelInterceptor2ModelValidatorWrapper.java:123)"
62: "	at org.compiere.model.ModelValidationEngine.invokeModelChangeMethod(ModelValidationEngine.java:984)"
63: "	at org.compiere.model.ModelValidationEngine.invokeModelChangeMethods(ModelValidationEngine.java:961)"
64: "	at org.compiere.model.ModelValidationEngine.fireModelChange0(ModelValidationEngine.java:843)"
65: "	at org.compiere.model.ModelValidationEngine.lambda$fireModelChange$0(ModelValidationEngine.java:800)"
66: "	at org.compiere.model.ModelValidationEngine.lambda$executeInTrx$1(ModelValidationEngine.java:822)"
67: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:103)"
68: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:93)"
69: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:776)"
70: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:689)"
71: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:597)"
72: "	at org.compiere.model.ModelValidationEngine.executeInTrx(ModelValidationEngine.java:822)"
73: "	at org.compiere.model.ModelValidationEngine.fireModelChange(ModelValidationEngine.java:800)"
74: "	at org.compiere.model.PO.fireModelChange(PO.java:4839)"
75: "	at org.compiere.model.PO.save0(PO.java:2822)"
76: "	at org.compiere.model.PO.access$100(PO.java:140)"
77: "	at org.compiere.model.PO$1.run(PO.java:2730)"
78: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)"
79: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)"
80: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:776)"
81: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:689)"
82: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:590)"
83: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:521)"
84: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:507)"
85: "	at org.compiere.model.PO.saveEx(PO.java:2724)"
86: "	at org.compiere.model.PO.saveEx(PO.java:3016)"
87: "	at org.adempiere.model.GeneralCopyRecordSupport.copyRecord(GeneralCopyRecordSupport.java:138)"
88: "	at org.adempiere.model.MOrderLinePOCopyRecordSupport.copyRecord(MOrderLinePOCopyRecordSupport.java:72)"
89: "	at org.adempiere.model.GeneralCopyRecordSupport.copyRecord(GeneralCopyRecordSupport.java:159)"
90: "	at de.metas.contracts.subscription.impl.subscriptioncommands.ExtendContractOrder.extend(ExtendContractOrder.java:50)"
91: "	at de.metas.contracts.flatrate.process.C_Order_Copy.doIt(C_Order_Copy.java:26)"
92: "	at de.metas.process.JavaProcess.startProcess(JavaProcess.java:296)"
93: "	at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:565)"
94: "	at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:461)"
95: "	at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:51)"
96: "	at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:225)"
97: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)"
98: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)"
99: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:776)"
[100 … 195]
100: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:689)"
101: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:590)"
102: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:521)"
103: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:507)"
104: "	at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:287)"
105: "	at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:172)"
106: "	at de.metas.process.ProcessExecutor.access$1100(ProcessExecutor.java:51)"
107: "	at de.metas.process.ProcessExecutor$Builder.executeSync(ProcessExecutor.java:652)"
108: "	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.executeADProcess(ADProcessInstanceController.java:333)"
109: "	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.startProcess(ADProcessInstanceController.java:310)"
110: "	at de.metas.ui.web.process.ProcessRestController.lambda$null$7(ProcessRestController.java:259)"
111: "	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.forProcessInstanceWritable(ADProcessInstancesRepository.java:420)"
112: "	at de.metas.ui.web.process.ProcessRestController.lambda$startProcess$8(ProcessRestController.java:258)"
113: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
114: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
115: "	at de.metas.ui.web.process.ProcessRestController.startProcess(ProcessRestController.java:257)"
116: "	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
117: "	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
118: "	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
119: "	at java.lang.reflect.Method.invoke(Method.java:498)"
120: "	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
121: "	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
122: "	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
123: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
124: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
125: "	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
126: "	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
127: "	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
128: "	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
129: "	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
130: "	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
131: "	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
132: "	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
133: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
134: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
135: "	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
136: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
137: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
138: "	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
139: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
140: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
141: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
142: "	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
143: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
144: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
145: "	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
146: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
147: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
148: "	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:79)"
149: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
150: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
151: "	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
152: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
153: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
154: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
155: "	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
156: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
157: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
158: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
159: "	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
160: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
161: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
162: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
163: "	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
164: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
165: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
166: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
167: "	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
168: "	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
169: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
170: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
171: "	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
172: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
173: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
174: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
175: "	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
176: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
177: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
178: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
179: "	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
180: "	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
181: "	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
182: "	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
183: "	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
184: "	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
185: "	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
186: "	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
187: "	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
188: "	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
189: "	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
190: "	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
191: "	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
192: "	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
193: "	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
194: "	at java.lang.Thread.run(Thread.java:748)"
```
</Details>

**Comment by metas-dh** [comment]
Results of IT1
tested in live1554

Prolonging contract:
* first contract created from original order: OK
* status in order: Active
* Prolonging contract from order, no change of date:
     * new order in draft status first, with start date contract: 1 day after end date of original contract: OK
     * complete new order: new contract is created, with correct start date (see above) and same term as original, Status: Active: OK
     * status in original order: Verlängert: OK
* Prolonging contract from order, change of date:
     * new order in draft status first, with start date contract: 1 day after end date of original contract: OK
* date changed to later date end date of original contract (+3 days), complete new order:
     * new contract is created, with start date as set and same term as original, Status: Active: OK
     * status in original order: Verlängert: OK
* date changed to earlier date end date of original contract (-5 days), complete new order:
     * new contract is created, with start date as set and same term as original, Status: Active: OK
     * status in original order: Verlängert: OK
     * original contract: end date is changed accordingly, => 1 day before start date of new contract: OK
