### ISSUE TITLE
Error message when printing using pdf printer in version 5.95

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#5083]
### Is this a bug or feature request?
bug

### What is the current behavior?
tried to print to a pdf printer from printing queue using "print all" and got this error message:

trace:

<details>

2019-03-27 07:50:56.460 ERROR 144 --- [https-jsse-nio-8443-exec-8] o.a.m.RelationTypeZoomProvidersFactory   : C_Printing_Queue_PrintInfo_v does not have a single key column
2019-03-27 07:50:56.519  WARN 144 --- [https-jsse-nio-8443-exec-8] d.m.ui.web.config.WebuiExceptionHandler  : Got REST exception from handler=public de.metas.ui.web.window.datatypes.json.JSONDocumentReferencesGroup de.metas.ui.web.window.controller.WindowRestController.getDocumentReferences(java.lang.String,java.lang.String,java.lang.String,java.lang.String)

org.adempiere.exceptions.PORelationException: PO C_Printing_Queue_PrintInfo_v has 1 key columns. Needs to have exactly one.
        at org.adempiere.exceptions.PORelationException.throwWrongKeyColumnCount(PORelationException.java:31)
        at org.adempiere.model.RelationTypeZoomProvidersFactory.retrieveZoomProvidersBySourceTableName(RelationTypeZoomProvidersFactory.java:149)
        at org.adempiere.model.RelationTypeZoomProvidersFactory.lambda$getZoomProvidersByZoomOriginTableName$0(RelationTypeZoomProvidersFactory.java:136)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5065)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
        at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060)
        at de.metas.cache.CCache.get(CCache.java:504)
        at de.metas.cache.CCache.getOrLoad(CCache.java:538)
        at org.adempiere.model.RelationTypeZoomProvidersFactory.getZoomProvidersByZoomOriginTableName(RelationTypeZoomProvidersFactory.java:136)
        at org.adempiere.model.ZoomInfoFactory.retrieveZoomProviders(ZoomInfoFactory.java:525)
        at org.adempiere.model.ZoomInfoFactory.streamZoomInfos(ZoomInfoFactory.java:418)
        at org.adempiere.model.ZoomInfoFactory.streamZoomInfos(ZoomInfoFactory.java:407)
        at de.metas.ui.web.window.model.DocumentReferencesService.lambda$getDocumentReferences$1(DocumentReferencesService.java:76)
        at de.metas.ui.web.window.model.DocumentCollection.lambda$forDocumentReadonly$1(DocumentCollection.java:195)
        at de.metas.ui.web.window.model.DocumentCollection.forRootDocumentReadonly(DocumentCollection.java:232)
        at de.metas.ui.web.window.model.DocumentCollection.forDocumentReadonly(DocumentCollection.java:185)
        at de.metas.ui.web.window.model.DocumentReferencesService.getDocumentReferences(DocumentReferencesService.java:65)
        at de.metas.ui.web.window.controller.WindowRestController.getDocumentReferences(WindowRestController.java:726)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
   at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:79)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)
        at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

</details>

**Comment by teosarca** [comment]
Even if the error message is misleading, my educated guess is: 

C_Printing_Queue_PrintInfo_v
* does NOT have any PK column (i.e. AD_Column.IsKey=Y)
* has one parent column (i.e. AD_Column.IsParent=Y)

Suggestion:
Try flagging that parent column as IsKey=Y and untick IsParent.
Might work, not sure.

**Comment by teosarca** [comment]
btw, did a quick check to see if we have other cases.

I think the "C_Order_MFGWarehouse_Report_PrintInfo_v" is in the same case....

```sql
select t.TableName
from AD_Table t
where 
(select count(1) from AD_Column c where c.AD_Table_ID=t.AD_Table_ID and IsKey='Y') = 0
and (select count(1) from AD_Column c where c.AD_Table_ID=t.AD_Table_ID and IsParent='Y' and IsKey='N') = 1
```
![image](https://user-images.githubusercontent.com/1244701/55059008-6f966100-5076-11e9-8b27-9aa9424499db.png)

**Comment by teosarca** [comment]
Btw, we can also solve this case from code too,
i.e. if we have only one parent column but no key column, we can consider that column as a key.
The fix shall be in org.compiere.model.POInfo.loadInfo(String), line ~422.
