### ISSUE TITLE
Picking with bestBefore shortest/ longest option

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#5544]

**Comment by metas-ts** [comment]
@teosarca i got this with the latest master:

<details>

```
webapi_1    | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'de.metas.ui.web.quickinput.orderline.OrderLineQuickInputDescriptorFactory' defined in URL [jar:file:/opt/metasfresh-webui-api/metasfresh-webui-api.jar!/BOOT-INF/classes!/de/metas/ui/web/quickinput/orderline/OrderLineQuickInputDescriptorFactory.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.metas.ui.web.quickinput.orderline.OrderLineQuickInputDescriptorFactory]: Constructor threw exception; nested exception is de.metas.util.exceptions.ServicesException: org.adempiere.exceptions.AdempiereException: Error: Param 'serviceInstanceClass' = class de.metas.bpartner.service.impl.BPartnerBL has no default constructor
webapi_1    |   at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:279)
webapi_1    |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193)
webapi_1    |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095)
webapi_1    |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
webapi_1    |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
webapi_1    |   at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
webapi_1    |   at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
webapi_1    |   at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
webapi_1    |   at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
webapi_1    |   at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
webapi_1    |   at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
webapi_1    |   at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
webapi_1    |   at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
webapi_1    |   at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
webapi_1    |   at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
webapi_1    |   at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
webapi_1    |   at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
webapi_1    |   at de.metas.ui.web.WebRestApiApplication.main(WebRestApiApplication.java:110)
webapi_1    |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
webapi_1    |   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
webapi_1    |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
webapi_1    |   at java.lang.reflect.Method.invoke(Method.java:498)
webapi_1    |   at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
webapi_1    |   at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
webapi_1    |   at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
webapi_1    |   at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
webapi_1    | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.metas.ui.web.quickinput.orderline.OrderLineQuickInputDescriptorFactory]: Constructor threw exception; nested exception is de.metas.util.exceptions.ServicesException: org.adempiere.exceptions.AdempiereException: Error: Param 'serviceInstanceClass' = class de.metas.bpartner.service.impl.BPartnerBL has no default constructor
webapi_1    |   at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:154)
webapi_1    |   at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
webapi_1    |   at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271)
webapi_1    |   ... 25 common frames omitted
webapi_1    | Caused by: de.metas.util.exceptions.ServicesException: org.adempiere.exceptions.AdempiereException: Error: Param 'serviceInstanceClass' = class de.metas.bpartner.service.impl.BPartnerBL has no default constructor
webapi_1    |   at de.metas.util.exceptions.ServicesException.wrapIfNeeded(ServicesException.java:55)
webapi_1    |   at de.metas.util.exceptions.ServicesException.wrapIfNeeded(ServicesException.java:51)
webapi_1    |   at de.metas.util.Services.findAndLoadService(Services.java:269)
webapi_1    |   at de.metas.util.Services.access$100(Services.java:64)
webapi_1    |   at de.metas.util.Services$2.load(Services.java:128)
webapi_1    |   at de.metas.util.Services$2.load(Services.java:124)
webapi_1    |   at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
webapi_1    |   at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
webapi_1    |   at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
webapi_1    |   at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
webapi_1    |   at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
webapi_1    |   at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
webapi_1    |   at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
webapi_1    |   at de.metas.util.Services.getSingleton(Services.java:224)
webapi_1    |   at de.metas.util.Services.get(Services.java:195)
webapi_1    |   at de.metas.ui.web.quickinput.orderline.OrderLineQuickInputCallout.<init>(OrderLineQuickInputCallout.java:48)
webapi_1    |   at de.metas.ui.web.quickinput.orderline.OrderLineQuickInputCallout.newInstance(OrderLineQuickInputCallout.java:44)
webapi_1    |   at de.metas.ui.web.quickinput.orderline.OrderLineQuickInputDescriptorFactory.<init>(OrderLineQuickInputDescriptorFactory.java:65)
webapi_1    |   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
webapi_1    |   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
webapi_1    |   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
webapi_1    |   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
webapi_1    |   at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
webapi_1    |   ... 27 common frames omitted
webapi_1    | Caused by: org.adempiere.exceptions.AdempiereException: Error: Param 'serviceInstanceClass' = class de.metas.bpartner.service.impl.BPartnerBL has no default constructor
webapi_1    |   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
webapi_1    |   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
webapi_1    |   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
webapi_1    |   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
webapi_1    |   at de.metas.util.Check.mkEx(Check.java:120)
webapi_1    |   at de.metas.util.Check.throwOrLogEx(Check.java:135)
webapi_1    |   at de.metas.util.Check.errorIf(Check.java:573)
webapi_1    |   at de.metas.util.Check.errorIf(Check.java:554)
webapi_1    |   at de.metas.util.Services.getDefaultConstructor(Services.java:534)
webapi_1    |   at de.metas.util.Services.findServiceImplementationConstructor(Services.java:298)
webapi_1    |   at de.metas.util.Services.access$000(Services.java:64)
webapi_1    |   at de.metas.util.Services$1.load(Services.java:119)
webapi_1    |   at de.metas.util.Services$1.load(Services.java:115)
webapi_1    |   at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
webapi_1    |   at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
webapi_1    |   at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
webapi_1    |   at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
webapi_1    |   at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
webapi_1    |   at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
webapi_1    |   at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
webapi_1    |   at de.metas.util.Services.findAndLoadService(Services.java:250)
webapi_1    |   ... 47 common frames omitted
webapi_1    |
```

</details>
