### ISSUE TITLE
No invoice from Picking Terminal 2: NetAmtToInvoice checksum not match

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#5599]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When running `Process` action in picking terminal 2, a shipment and an invoice shall be created. During this week's e2e, only the shipments were created, but no invoice.

<details>

```
org.adempiere.exceptions.AdempiereException: NetAmtToInvoice checksum not match
 Expected: 160
 Actual: 0
 Invoice candidates count: 0
Additional parameters:
 I_C_Queue_WorkPackage: X_C_Queue_WorkPackage[C_Queue_WorkPackage_ID=1000302, trxName=null]
 IQueueProcessor: ThreadPoolQueueProcessor{name=C_Invoice_Candidate - Generate Invoices, executor=BlockingThreadPoolExecutor [getPoolSize()=1]}
 trxName: <<ThreadInherited>>
	at de.metas.invoicecandidate.api.impl.ICNetAmtToInvoiceChecker.assertExpectedNetAmtToInvoice(ICNetAmtToInvoiceChecker.java:124)
	at de.metas.invoicecandidate.api.impl.InvoiceCandBLCreateInvoices.generateInvoices(InvoiceCandBLCreateInvoices.java:827)
	at de.metas.invoicecandidate.async.spi.impl.InvoiceCandWorkpackageProcessor.processWorkPackage(InvoiceCandWorkpackageProcessor.java:116)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.invokeProcessorAndHandleException(WorkpackageProcessorTask.java:291)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.processWorkpackage(WorkpackageProcessorTask.java:283)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.lambda$run$0(WorkpackageProcessorTask.java:167)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:103)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:93)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:757)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:670)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:578)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.run(WorkpackageProcessorTask.java:161)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at Thread.run(Thread.java:748)
```

</details>

see me03 issue for links

**Comment by metas-ts** [comment]
here we have a trace to the actual problem

![image](https://user-images.githubusercontent.com/1264789/66020137-5c14f880-e4e6-11e9-97ec-48bfa6ae11e2.png)

![image](https://user-images.githubusercontent.com/1264789/66020068-1fe19800-e4e6-11e9-93cc-13e20ecf5542.png)

=> both ICs were skipped from invoicing, because they were already enqueued somewhere else.


Looking at that other work package, we find:

![image](https://user-images.githubusercontent.com/1264789/66020250-d2195f80-e4e6-11e9-8211-6ec8284a5105.png)


it was created, but not flagged as "ready for processing" by the system.

TODO: need to check the log in the hopes of finding out how this happened
