### ISSUE TITLE
Bug in Import-Ladeprogramm 

### ISSUE THREAD

**Issue by homebeaver** [metasfresh/metasfresh#657]
Nach der [Importdefinition](https://github.com/metasfresh/metasfresh/issues/656) will ich nach Anleitung [Wie importiere ich eine CSV Datei ?](http://docs.metasfresh.org/howto_collection/Wie_importiere_ich_eine_CSV_Datei.html) importieren.

Auch hier gibt es ein Problem, es wurde nichts importiert:
![b](https://cloud.githubusercontent.com/assets/3493126/20727587/5c3c36c2-b67a-11e6-8838-81edafadb886.PNG)

Diesmal mit trace:
```
org.adempiere.exceptions.AdempiereException: Failed to schedules lines to be imported
	at org.compiere.apps.form.VFileImport.cmd_importSchedule(VFileImport.java:632)
	at org.compiere.apps.form.VFileImport.access$2(VFileImport.java:592)
	at org.compiere.apps.form.VFileImport$3.doInBackground(VFileImport.java:547)
	at org.compiere.apps.form.VFileImport$3.doInBackground(VFileImport.java:1)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by teosarca** [comment]
unfortunately the stack trace, as it was logged in console until now is not enough to identify the problem.
But i've pushed a fix to improve the error reporting so next time when it happens you can fetch the complete stacktrace.

**Comment by homebeaver** [comment]
onece more:
```
2016-11-30 09:58:14.033  WARN 11788 --- [WT-EventQueue-0] org.compiere.apps.form.VFileImport       : 

org.adempiere.exceptions.AdempiereException: Failed to schedules lines to be imported
	at org.compiere.apps.form.VFileImport.cmd_importSchedule(VFileImport.java:630)
	at org.compiere.apps.form.VFileImport.access$2(VFileImport.java:590)
	at org.compiere.apps.form.VFileImport$3.doInBackground(VFileImport.java:545)
	at org.compiere.apps.form.VFileImport$3.doInBackground(VFileImport.java:1)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.adempiere.exceptions.AdempiereException: @NotFound@ @Record_ID@
	at org.adempiere.impexp.spi.impl.AsyncImportProcessBuilder.buildAndEnqueue(AsyncImportProcessBuilder.java:78)
	at org.compiere.apps.form.VFileImport.cmd_importSchedule(VFileImport.java:620)
	... 9 common frames omitted

2016-11-30 09:58:14.035  INFO 11788 --- [WT-EventQueue-0] org.compiere.apps.form.FormFrame         : Busy=false
2016-11-30 09:58:14.041  INFO 11788 --- [WT-EventQueue-0] org.compiere.apps.ADialog                : FileImportR/I - #0
```

**Comment by teosarca** [comment]
It seems nothing was enqueued to be imported.
That's because you have errors on all those lines.
Please check the error messages in the ErrMsg column.

**Comment by homebeaver** [comment]
Do you mean i_bpartner.i_errormsg ?
My TABLE i_bpartner is empty!

the problem seems to be in `VFileImport:cmd_importPrepare()`:

```
				for (final ImpDataLine line : lines)
				{
					if (!line.isToImport())
					{
						continue;
					}
```
you `continue` for all lines. I tested with

```
					} else {
						logger.error("ImportStatus={} ImportErrorMessage={}",line.getImportStatus(),line.getImportErrorMessage());
						List<ImpDataCell> celllist = line.getValues();
						for(int i=0; i<celllist.size();i++) {
							logger.error("{}:{}",i,line.getCellErrorMessage(i));
						}
					}
```
and got for all lines:

```
2016-11-30 14:11:46.943 ERROR 7672 --- [pool-3-thread-2] org.compiere.apps.form.VFileImport       : ImportStatus=New ImportErrorMessage=null
2016-11-30 14:11:46.951 ERROR 7672 --- [pool-3-thread-2] org.compiere.apps.form.VFileImport       : 0:null
2016-11-30 14:11:46.958 ERROR 7672 --- [pool-3-thread-2] org.compiere.apps.form.VFileImport       : 1:null
2016-11-30 14:11:46.965 ERROR 7672 --- [pool-3-thread-2] org.compiere.apps.form.VFileImport       : 2:null
2016-11-30 14:11:46.971 ERROR 7672 --- [pool-3-thread-2] org.compiere.apps.form.VFileImport       : 3:null
2016-11-30 14:11:46.978 ERROR 7672 --- [pool-3-thread-2] org.compiere.apps.form.VFileImport       : 4:null
2016-11-30 14:11:46.994 ERROR 7672 --- [pool-3-thread-2] org.compiere.apps.form.VFileImport       : 5:null
2016-11-30 14:11:47.000 ERROR 7672 --- [pool-3-thread-2] org.compiere.apps.form.VFileImport       : 6:null
2016-11-30 14:11:47.007 ERROR 7672 --- [pool-3-thread-2] org.compiere.apps.form.VFileImport       : 7:null
2016-11-30 14:11:47.013 ERROR 7672 --- [pool-3-thread-2] org.compiere.apps.form.VFileImport       : 8:null
```

**Comment by homebeaver** [comment]
Hey Teo, I found the reason.
The mantatory column CountryCode which was defined as const 'DE' was unfortunately set to "C_Coutry_Id" instead of "CountryCode".
For an end custumer it is hard to resolve this without an error message.
