### ISSUE TITLE
Drop the template BPartner feature and make BPartner mandatory in order, invoice, dd order

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#659]

**Comment by teosarca** [comment]
Background story:
webui auto-save feature is checking if the mandatory fields are filled and if yes, it tries to save it.
Now, the C_BPartner_ID is not mandatory and on before-save, the system tries to fetch the "template bpartner" (i.e. AD_ClientInfo.C_BPartnerCashTrx_ID).

That's not cool or at least it's not the right place for this thing.

Because we don't have a "template bpartner" set, when we create a new order on webui we get following exception in console:


```
org.adempiere.exceptions.BPartnerNoShipToAddressException: @BPartnerNoShipToAddress@ - @C_BPartner_ID@: _ (ID=new)
	at sun.reflect.GeneratedConstructorAccessor1134.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java)
	at com.zeroturnaround.jrebelbase.facade.q.invokeNewConstructor(SourceFile:439)
	at org.adempiere.exceptions.BPartnerNoShipToAddressException.<init>(BPartnerNoShipToAddressException.java:65534)
	at org.compiere.model.MOrder.setBPartner(MOrder.java:563)
	at org.compiere.model.MOrder.beforeSave(MOrder.java:1062)
	at org.compiere.model.PO.save0(PO.java:2828)
	at org.compiere.model.PO.access$1(PO.java:2821)
	at org.compiere.model.PO$1.run(PO.java:2742)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:103)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:1)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:694)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:606)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:507)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:444)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:437)
	at org.compiere.model.PO.saveEx(PO.java:2735)
	at org.adempiere.model.POWrapper.save(POWrapper.java:787)
	at org.adempiere.model.InterfaceWrapperHelper.save(InterfaceWrapperHelper.java:506)
	at de.metas.ui.web.window.model.sql.SqlDocumentsRepository.save(SqlDocumentsRepository.java:406)
	at de.metas.ui.web.window.model.Document.saveIfHasChanges(Document.java:1384)
	at de.metas.ui.web.window.model.Document.saveIfValidAndHasChanges(Document.java:1368)
	at de.metas.ui.web.window.model.DocumentCollection.commit(DocumentCollection.java:257)
	at de.metas.ui.web.window.controller.WindowRestController.commit0(WindowRestController.java:231)
	at de.metas.ui.web.window.controller.WindowRestController.lambda$1(WindowRestController.java:217)

```
