### ISSUE TITLE
Filter operator "between" broken

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#674]
Filter operator between broken

```
2016-12-06 16:07:14.950  WARN 11759 --- [WT-EventQueue-0] d.m.a.form.swing.SwingClientUIInstance   : ERROR: operator does not exist: timestamp without time zone >-< timestamp without time zone
  Hinweis: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 161

org.postgresql.util.PSQLException: ERROR: operator does not exist: timestamp without time zone >-< timestamp without time zone
  Hinweis: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 161
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2458)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2158)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:291)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:432)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:358)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:305)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:291)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:269)
        at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:236)
        at com.mchange.v2.c3p0.impl.NewProxyStatement.executeQuery(NewProxyStatement.java:327)
        at org.adempiere.sql.impl.AbstractCStatementProxy.executeQuery(AbstractCStatementProxy.java:109)
        at org.compiere.apps.search.FindPanel.getNoOfRecords(FindPanel.java:1072)
        at org.compiere.apps.search.FindPanel.cmd_ok_Advanced(FindPanel.java:826)
        at org.compiere.apps.search.FindPanel.cmd_ok(FindPanel.java:808)
        at org.compiere.apps.search.FindPanel.actionPerformed0(FindPanel.java:613)
        at org.compiere.apps.search.FindPanel.actionPerformed(FindPanel.java:595)
        at org.compiere.apps.AppsAction.actionPerformed(AppsAction.java:454)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
        at java.awt.Component.processMouseEvent(Component.java:6533)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6298)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
        at java.awt.Container.dispatchEventImpl(Container.java:2280)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
```

**Comment by metas-mk** [comment]
This Task belongs to already reported task #617 Fix operators in search panel.

**Comment by metas-dh** [comment]
Results of IT 1 

* App.Server: sp80cloudit
* Buildno: #1.85
* DB: declouddb001 : 5432 / sp80_cloud_it

* tested "between" filter operator, <->, with dates, qties, order no.s etc., in Auftrag, Lieferdispo, Rechnungsdispo: OK
* tested existing filter combinations, including <->: OK
