### ISSUE TITLE
Processing picking is not working

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#6761]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When trying to process the picking, in terminal v2, you get: 
`Error: Assumption failure: C_UOM_ID > 0 but it was 0`

<details>

```
{timestamp: "2020-05-28T15:04:15.985+02:00[Europe/Berlin]", status: 500,…}
error: "Internal Server Error"
exception: "org.adempiere.exceptions.AdempiereException"
message: "Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
↵Bitte leiten Sie diese Meldung an metas weiter:↵↵Assumption failure: C_UOM_ID > 0 but it was 0"
path: "/rest//api/process/ADP_541021/1005387/start"
status: 500
timestamp: "2020-05-28T15:04:15.985+02:00[Europe/Berlin]"
trace: [,…]
[0 … 99]
0: "org.adempiere.exceptions.AdempiereException: Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
"
1: "Bitte leiten Sie diese Meldung an metas weiter:"
2: ""
3: "Assumption failure: C_UOM_ID > 0 but it was 0"
4: "	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)"
5: "	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)"
6: "	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)"
7: "	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)"
8: "	at de.metas.util.Check.mkEx(Check.java:117)"
9: "	at de.metas.util.Check.throwOrLogEx(Check.java:132)"
10: "	at de.metas.util.Check.assumeGreaterThanZero(Check.java:442)"
11: "	at de.metas.uom.UomId.<init>(UomId.java:59)"
12: "	at de.metas.uom.UomId.ofRepoId(UomId.java:44)"
13: "	at de.metas.handlingunits.inout.impl.HUPackingMaterialDAO.retrievePackageDimensions(HUPackingMaterialDAO.java:100)"
14: "	at de.metas.shipper.gateway.dpd.DpdDraftDeliveryOrderCreator.getPackageDimensions(DpdDraftDeliveryOrderCreator.java:245)"
15: "	at de.metas.shipper.gateway.dpd.DpdDraftDeliveryOrderCreator.createDraftDeliveryOrder(DpdDraftDeliveryOrderCreator.java:140)"
16: "	at de.metas.shipper.gateway.commons.ShipperGatewayFacade.createAndSendDeliveryOrder(ShipperGatewayFacade.java:159)"
17: "	at com.google.common.collect.SingletonImmutableBiMap.forEach(SingletonImmutableBiMap.java:65)"
18: "	at de.metas.shipper.gateway.commons.ShipperGatewayFacade.createAndSendDeliveryOrdersForPackages(ShipperGatewayFacade.java:84)"
19: "	at de.metas.handlingunits.shipmentschedule.api.HUShippingFacade.generateShipperDeliveryOrderIfNeeded(HUShippingFacade.java:285)"
20: "	at com.google.common.collect.SingletonImmutableBiMap.forEach(SingletonImmutableBiMap.java:65)"
21: "	at de.metas.handlingunits.shipmentschedule.api.HUShippingFacade.generateShipperDeliveryOrdersIfNeeded(HUShippingFacade.java:244)"
22: "	at de.metas.handlingunits.shipmentschedule.api.HUShippingFacade.generateShippingDocuments0(HUShippingFacade.java:154)"
23: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$1.call(TrxCallableWrappers.java:58)"
24: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$1.call(TrxCallableWrappers.java:48)"
25: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:753)"
26: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:666)"
27: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:567)"
28: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:498)"
29: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:491)"
30: "	at org.adempiere.ad.trx.api.ITrxManager.runInThreadInheritedTrx(ITrxManager.java:222)"
31: "	at de.metas.handlingunits.shipmentschedule.api.HUShippingFacade.generateShippingDocuments(HUShippingFacade.java:145)"
32: "	at de.metas.ui.web.pickingV2.productsToPick.process.ProductsToPick_4EyesReview_ProcessAll.deliverAndInvoice(ProductsToPick_4EyesReview_ProcessAll.java:182)"
33: "	at de.metas.ui.web.pickingV2.productsToPick.process.ProductsToPick_4EyesReview_ProcessAll.doIt(ProductsToPick_4EyesReview_ProcessAll.java:145)"
34: "	at de.metas.process.JavaProcess.startProcess(JavaProcess.java:306)"
35: "	at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:573)"
36: "	at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:469)"
37: "	at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:59)"
38: "	at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:229)"
39: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:147)"
40: "	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:137)"
41: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:753)"
42: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:666)"
43: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:567)"
44: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:498)"
45: "	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:484)"
46: "	at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:291)"
47: "	at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:176)"
48: "	at de.metas.process.ProcessExecutor.access$1100(ProcessExecutor.java:59)"
49: "	at de.metas.process.ProcessExecutor$Builder.executeSync(ProcessExecutor.java:675)"
50: "	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.executeADProcess(ADProcessInstanceController.java:332)"
51: "	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.startProcess(ADProcessInstanceController.java:308)"
52: "	at de.metas.ui.web.process.ProcessRestController.lambda$null$6(ProcessRestController.java:298)"
53: "	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.forProcessInstanceWritable(ADProcessInstancesRepository.java:446)"
54: "	at de.metas.ui.web.process.ProcessRestController.lambda$startProcess$7(ProcessRestController.java:297)"
55: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
56: "	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
57: "	at de.metas.ui.web.process.ProcessRestController.startProcess(ProcessRestController.java:296)"
58: "	at sun.reflect.GeneratedMethodAccessor304.invoke(Unknown Source)"
59: "	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
60: "	at java.lang.reflect.Method.invoke(Method.java:498)"
61: "	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
62: "	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
63: "	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
64: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
65: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
66: "	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
67: "	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
68: "	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
69: "	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
70: "	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
71: "	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
72: "	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
73: "	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
74: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
75: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
76: "	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
77: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
78: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
79: "	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
80: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
81: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
82: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
83: "	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
84: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
85: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
86: "	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:79)"
87: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
88: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
89: "	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:91)"
90: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
91: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
92: "	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
93: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
94: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
95: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
96: "	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
97: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
98: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
99: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
[100 … 136]
100: "	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
101: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
102: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
103: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
104: "	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
105: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
106: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
107: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
108: "	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
109: "	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
110: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
111: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
112: "	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
113: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
114: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
115: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
116: "	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
117: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
118: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
119: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
120: "	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
121: "	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
122: "	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
123: "	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
124: "	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
125: "	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
126: "	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
127: "	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
128: "	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
129: "	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
130: "	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
131: "	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
132: "	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
133: "	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
134: "	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
135: "	at java.lang.Thread.run(Thread.java:748)"
136: ""
```

</details>

#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Should work.

**Comment by StefanRaatz** [comment]
@metas-dh I'm getting the same error when I try to pick in terminal v2. Do you have more information on how to fix the problem?

Cheers,
Stefan

**Comment by metas-dh** [comment]
i did not encounter this problem anymore in the recent weeks, so afais this was fixed in the meantime. 
@StefanRaatz unfortunately idk which issue / PR exactly fixed the problem.
