### ISSUE TITLE
Labels in material receipt cands not working

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#6765]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When trying to print labels for e.g. SSCC or IFCO in material receipt cands, you get
`Cannot convert HUReport_540412 to AdProcessId because the processHanderType=HUReport is not supported`

<details>

```
{timestamp: "2020-05-29T20:45:49.870+02:00[Europe/Berlin]", status: 500,…}
error: "Internal Server Error"
exception: "org.adempiere.exceptions.AdempiereException"
message: "Cannot convert HUReport_540412 to AdProcessId because the processHanderType=HUReport is not supported"
path: "/rest//api/process/HUReport_540412"
status: 500
timestamp: "2020-05-29T20:45:49.870+02:00[Europe/Berlin]"
trace: [,…]
0: "org.adempiere.exceptions.AdempiereException: Cannot convert HUReport_540412 to AdProcessId because the processHanderType=HUReport is not supported"
1: "	at de.metas.ui.web.process.ProcessId.toAdProcessId(ProcessId.java:151)"
2: "	at de.metas.ui.web.process.ProcessRestController.createInstanceFromRequest(ProcessRestController.java:189)"
3: "	at sun.reflect.GeneratedMethodAccessor303.invoke(Unknown Source)"
4: "	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
5: "	at java.lang.reflect.Method.invoke(Method.java:498)"
6: "	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
7: "	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
8: "	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
9: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
10: "	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
11: "	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
12: "	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
13: "	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
14: "	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
15: "	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)"
16: "	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)"
17: "	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
18: "	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
19: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
20: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
21: "	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
22: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
23: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
24: "	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
25: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
26: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
27: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
28: "	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
29: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
30: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
31: "	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:79)"
32: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
33: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
34: "	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:91)"
35: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
36: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
37: "	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
38: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
39: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
40: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
41: "	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
42: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
43: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
44: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
45: "	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
46: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
47: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
48: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
49: "	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
50: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
51: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
52: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
53: "	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
54: "	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
55: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
56: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
57: "	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
58: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
59: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
60: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
61: "	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
62: "	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
63: "	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
64: "	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
65: "	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
66: "	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
67: "	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
68: "	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
69: "	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
70: "	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
71: "	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
72: "	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
73: "	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
74: "	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
75: "	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
76: "	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
77: "	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
78: "	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
79: "	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
80: "	at java.lang.Thread.run(Thread.java:748)"
81: ""
```

</details>

#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Should work.

**Comment by metasnw** [comment]
fixed by #9847
