### ISSUE TITLE
NPE when creating CreditMemo for closed period

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#802]
Steps to reproduce: 
* I did this test in January 2017 and tried to create credit memo for invoices from last year ( via the button in Rechnung). 
* => NOK: I got a NullPointerException
* In the console I have: 

> 2017-01-11 17:56:54.011  WARN 18524 --- [tellen-13322982] org.compiere.model.MPeriod               : Jan-17: Not open for ARC (2017-01-11 00:00:00.0)
> 2017-01-11 17:57:07.038 ERROR 18524 --- [tellen-13322982] o.a.i.p.CreateCreditMemoFromInvoice      : java.lang.NullPointerException
> 
> org.adempiere.exceptions.AdempiereException: java.lang.NullPointerException
> 	at org.adempiere.exceptions.AdempiereException.wrapIfNeeded(AdempiereException.java:78)
> 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:835)
> 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:669)
> 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:570)
> 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:501)
> 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:494)
> 	at de.metas.document.engine.impl.AbstractDocActionBL.processIt(AbstractDocActionBL.java:87)
> 	at de.metas.document.engine.impl.AbstractDocActionBL.processEx(AbstractDocActionBL.java:144)
> 	at org.adempiere.invoice.service.impl.CreditMemoInvoiceCopyHandler.completeAndAllocateCreditMemo(CreditMemoInvoiceCopyHandler.java:288)
> 	at org.adempiere.invoice.service.impl.CreditMemoInvoiceCopyHandler.copyValues(CreditMemoInvoiceCopyHandler.java:100)
> 	at org.adempiere.invoice.service.impl.CreditMemoInvoiceCopyHandler.copyValues(CreditMemoInvoiceCopyHandler.java:1)
> 	at org.adempiere.invoice.service.impl.AbstractInvoiceBL.copyFrom(AbstractInvoiceBL.java:311)
> 	at org.adempiere.invoice.service.impl.AbstractInvoiceBL.creditInvoice(AbstractInvoiceBL.java:140)
> 	at org.adempiere.invoice.process.CreateCreditMemoFromInvoice.doIt(CreateCreditMemoFromInvoice.java:76)
> 	at de.metas.process.JavaProcess.startProcess(JavaProcess.java:161)
> 	at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:559)
> 	at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:457)
> 	at de.metas.process.ProcessExecutor.access$5(ProcessExecutor.java:446)
> 	at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:220)
> 	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:103)
> 	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:1)
> 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:757)
> 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:669)
> 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:570)
> 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:501)
> 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:494)
> 	at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:280)
> 	at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:168)
> 	at de.metas.process.ProcessExecutor.lambda$0(ProcessExecutor.java:116)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.NullPointerException: null
> 	at org.compiere.model.MInvoice.getDocumentInfo(MInvoice.java:954)
> 	at de.metas.document.exceptions.DocumentProcessingException.buildMsg(DocumentProcessingException.java:77)
> 	at de.metas.document.exceptions.DocumentProcessingException.<init>(DocumentProcessingException.java:42)
> 	at de.metas.document.engine.impl.AbstractDocActionBL$1.doCatch(AbstractDocActionBL.java:105)
> 	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.doCatch(TrxCallableWrappers.java:116)
> 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:781)
> 	... 28 common frames omitted

`

* From what I noticed during debugging, the problem is that here org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(TrxCallable<T>, ITrxRunConfig, String)
, at row 781, the runExpression is

> org.adempiere.exceptions.PeriodClosedException: Periode geschlossen Datum=2017-01-11 00:00:00.0, Document BaseType=Gutschrift (Debitorenkonten)

But it gets into the catch , where the Throwable doCatchException is a NullPointerException instead

**Comment by teosarca** [comment]
IMHO the problem is in org.compiere.model.MInvoice.getDocumentInfo() where "MDocType dt" is null
