### ISSUE TITLE
Adopt Request Callouts for WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#819]
Adopt Request Callouts for WebUI
When switching request type fields in currently created request window for webui, you get a NPE.
Please adopt the request callouts for webUI.

![image](https://cloud.githubusercontent.com/assets/13365687/21986068/22c70d78-dbfe-11e6-8077-ea6be96a7f43.png)

**Comment by metas-mk** [comment]
is needed for implementation of #817

**Comment by teosarca** [comment]
The server side exception was:


```
2017-01-16 15:08:22.458 ERROR 20754 --- [nio-8080-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.adempiere.ad.callout.exceptions.CalloutExecutionException: java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
        at org.compiere.model.CalloutRequest.type(CalloutRequest.java:130)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.compiere.model.CalloutEngine.lambda$createCalloutMethodExecutor$2(CalloutEngine.java:195)
        at org.compiere.model.CalloutEngine.start(CalloutEngine.java:71)
        at org.adempiere.ad.callout.api.impl.MethodNameCalloutInstance.execute(MethodNameCalloutInstance.java:120)
        at org.adempiere.ad.callout.api.impl.CalloutExecutor.execute(CalloutExecutor.java:262)
        at org.adempiere.ad.callout.api.impl.CalloutExecutor.execute(CalloutExecutor.java:119)
        at de.metas.ui.web.window.model.Document.setValue(Document.java:981)
        at de.metas.ui.web.window.model.Document.processValueChange(Document.java:882)
        at de.metas.ui.web.window.model.Document.processValueChanges(Document.java:897)
        at de.metas.ui.web.window.controller.WindowRestController.patchDocument0(WindowRestController.java:255)
        at de.metas.ui.web.window.controller.WindowRestController.lambda$patchDocument$1(WindowRestController.java:243)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:151)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$4.call(TrxCallableWrappers.java:180)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:757)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:669)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:570)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:501)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:486)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:470)
        at de.metas.ui.web.window.controller.Execution.callInNewExecution(Execution.java:88)
        at de.metas.ui.web.window.controller.WindowRestController.patchDocument(WindowRestController.java:243)
        at de.metas.ui.web.window.controller.WindowRestController.patchRootDocument(WindowRestController.java:212)
        at sun.reflect.GeneratedMethodAccessor471.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

```

**Comment by metas-dh** [comment]
Successfully tested by mk.
