### ISSUE TITLE
Logfile on application-server gets flooded 

### ISSUE THREAD

**Issue by metas-jb** [metasfresh/metasfresh#936]

**Comment by metas-ts** [comment]
that's from the console:
```
2017-02-20 13:21:56.906 ERROR 22497 --- [beiten-14680935] o.a.p.spi.impl.rules.BasePriceList       : pricingCtx PricingContext {
	pricingSystemId = -1
	M_Product_ID = 2004658
	M_PriceList_ID = 0
	M_PriceList_Version_ID = 0
	priceDateTS = 1486162799000
	priceDateNowTS = 1487593316781
	C_Country_ID = 0
	C_UOM_ID = 0
	C_Currency_ID = 0
	C_BPartner_ID = 2000226
	qty = 1.000
	isSOTrx = true
	AD_Table_ID = 0
	Record_ID = 0
	m_PP_Product_BOM_ID = 0
	m_PP_Product_BOMLine_ID = 0
	referencedObject = MOrderLine[0, Line=40, Ordered=1.000, Delivered=0, Invoiced=0, Reserved=0, LineNet=0]
	disallowDiscount = false
	trxName = TrxRun_7f40ce0f-2897-41fb-8331-17582f9857e7
	convertPriceToContextUOM = false
	isManualPrice = <null>
	properties = {}
	pricingSystem = <null>
	product = MProduct[2004658-P001903_Mischsalat Maison 1kg ]
	_priceListVersion = <null>
	country = <null>
} contains no priceList
2017-02-20 13:21:56.993  WARN 22497 --- [beiten-14680935] d.m.ordercandidate.api.impl.OLCandBL     : Caught exception while processing X_C_OLCand[C_OLCand_ID=1515052, trxName=TrxRun_7f40ce0f-2897-41fb-8331-17582f9857e7]; message=Produkt ist nicht auf der Preisliste - Zeile Nr.:40, Produkt:P001903, Datum:03.02.2017; exception={}

org.adempiere.pricing.exceptions.ProductNotOnPriceListException: @ProductNotOnPriceList@ - @Line@:40, @M_Product_ID@:P001903, @Date@:03.02.2017
	at de.metas.adempiere.service.impl.OrderLineBL.updatePrices(OrderLineBL.java:506)
	at org.compiere.model.MOrderLine.setPrice(MOrderLine.java:345)
	at org.compiere.model.MOrderLine.setPrice(MOrderLine.java:331)
	at org.compiere.model.MOrderLine.beforeSave(MOrderLine.java:965)
	at org.compiere.model.PO.save0(PO.java:2838)
	at org.compiere.model.PO.access$100(PO.java:130)
	at org.compiere.model.PO$1.run(PO.java:2752)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:764)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:676)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:577)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:508)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:501)
	at org.compiere.model.PO.saveEx(PO.java:2745)
	at org.adempiere.model.POWrapper.save(POWrapper.java:787)
	at org.adempiere.model.InterfaceWrapperHelper.save(InterfaceWrapperHelper.java:527)
	at de.metas.ordercandidate.api.impl.OLCandBL.processOLCand(OLCandBL.java:455)
	at de.metas.ordercandidate.api.impl.OLCandBL.process(OLCandBL.java:239)
	at de.metas.ordercandidate.process.ProcessOLCands$1.run(ProcessOLCands.java:60)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:764)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:676)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:577)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:508)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:501)
	at de.metas.ordercandidate.process.ProcessOLCands.doIt(ProcessOLCands.java:54)
	at de.metas.process.JavaProcess.startProcess(JavaProcess.java:162)
[...]
```

**Comment by metas-dh** [comment]
Results of IT 1
tested on sp80 swing

* imported and processed OLCand for P001903: no errors or exceptions, sales order was created correctly with the correct price from latest PLV: OK
* had also worked fine during last e2e on swing, OLCand for same product (which caused the problem in the past): OK
